### ISSUE TITLE
Issue with Postgres passwords containing "@"

### ISSUE THREAD

**Issue by vaibhavdobriyal** [ankane/pghero#100]
In case there is '@' in the password string, the password string creates an issue.

`sudo pghero config:set DATABASE_URL=postgres://postgres:password@hostname:5432/tikalidb`

Workaround is though very easy and straightforward.
Create a variable in bash and then use this variable in the above command

```
PASS=`echo "password@string'"`
sudo pghero config:set DATABASE_URL=postgres://postgres:$PASS@hostname:5432/tikalidb
```

**Comment by ankane** [comment]
Hey @vaibhavdobriyal, you'll need to use percent encoding for special characters. More info here: http://stackoverflow.com/questions/23353623/how-to-handle-special-characters-in-the-password-of-a-postgresql-url-connection

**Comment by ankane** [comment]
Cleaning up issues
