### ISSUE TITLE
Autovacuum is reported as a long-running query

### ISSUE THREAD

**Issue by fake-name** [ankane/pghero#106]
I'm not sure if I really think this is actually a problem, but it's worth discussion.

Basically, it appears that the autovacuum is reported as one of the long-running queries:

![image](https://cloud.githubusercontent.com/assets/1401239/22616074/7a586eb4-ea5a-11e6-8e88-ed821083fe91.png)

This results in the db-health overview also reporting there being an issue. In this case, my DB's autovacuum does indeed take an enormous period of time, as the database is approaching a TB in size. I'd love a solution, but the only ideas I have involve more expensive SSDs.

Anyways, it'd might be a decent idea to protect the autovacuum process, so you can't accidentally kill it via the web-ui. Also, should it be ignored for the "long-running queries" display? I'd imagine even more modestly sized databases, vacuuming would take long enough that it'd probably be reported as a long running query.

**Comment by ankane** [comment]
Hey @fake-name, thanks for bringing this up. I've excluded autovacuum from long running queries to reduce noise on the homepage. I think we should keep in live queries as I'm less concerned about accidentally killing the process (and there may be instances where this is desired).

**Comment by fake-name** [comment]
Cool beans!

**Comment by fake-name** [comment]
Any change this'll make it out into the packager.io release soon?

BTW, the duplicate index stuff is fantastic. I had no idea that unique constraints resulted in a implicit index!

**Comment by ankane** [comment]
It was pushed to Packager ~2 weeks ago with the 1.6.3 release.

**Comment by fake-name** [comment]
Huh, I wonder why I'm not seeing it yet.
