### ISSUE TITLE
Problem extending Docker container with config file

### ISSUE THREAD

**Issue by hrzbrg** [ankane/pghero#108]
Hi,

I want to start the pghero container with a config for multiple databases, so I just extended the Dockerfile that you provide as follows: 

```
FROM ankane/pghero

ADD pghero.yml /app/config/pghero.yml
```

The `pghero.yml` looks like this:

```
development:
  adapter: postgresql
  databases:
    primary:
      url: 'postgres://user:password@mydatabase.example.com:5432/db'
```

(I know, currently it only one DB, but for a start it should at least work like that.) However when I start the container it complains: 

```
[7] ! Unable to load application: RuntimeError: Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file - ["config/database.yml"]
/usr/local/bundle/gems/railties-5.0.1/lib/rails/application/configuration.rb:143:in `database_configuration': Cannot load `Rails.application.database_configuration`: (RuntimeError)
Could not load database configuration. No such file - ["config/database.yml"]
```

So I added the file under `/app/config/database.yml` unfortunately without improvement:

```
Started GET "/" for 172.17.0.1 at 2017-02-27 20:37:34 +0000
Processing by PgHero::HomeController#index as HTML
Completed 500 Internal Server Error in 1819ms



PG::ConnectionBad (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
```

It looks like it wants to connect to localhost, indicating that no config at all was read from a file.
Maybe you can give me a hint on what is wrong here.

**Comment by ankane** [comment]
You'll still need to set `DATABASE_URL` when you start the container (not ideal, but necessary right now).

**Comment by hrzbrg** [comment]
Oh, indeed, I didn't get that from the docs. Thanks!
