### ISSUE TITLE
Extended support for EXPLAIN

### ISSUE THREAD

**Issue by seanlinsley** [ankane/pghero#11]
There are a number of optional settings to pass to an `explain`:

- analyze
- verbose
- costs
- buffers
- timing
- format

www.postgresql.org/docs/9.3/static/sql-explain.html#AEN77705

How you do you think these would best fit into the UI? Perhaps we could have a check box for each?

**Comment by PikachuEXE** [comment]
@ankane I think you should mention that in README :D

**Comment by ankane** [comment]
Added a button for analyze https://github.com/ankane/pghero/commit/7f34ada0c184166bdffeaece40ea1b3d69ca2926

**Comment by ankane** [comment]
Cleaning up issues
