### ISSUE TITLE
PgHero thinks master is a replica due to hot_standby=on

### ISSUE THREAD

**Issue by dstibrany** [ankane/pghero#110]
Is it currently possible to explicitly tell pghero that a server is not a replica or could you use `select pg_is_in_recovery()` to detect if the server is a replica instead of looking for `hot_standby=on`?

The problem is that both my master server and replica have `hot_standby=on` set in case I ever have to fail over and then resync. Any way around this?

**Comment by ankane** [comment]
Hey @dstibrany, thanks for pointing this out and investigating a fix 💯  I've made the change on master.
