### ISSUE TITLE
Add Support for Client Certificate auth

### ISSUE THREAD

**Issue by justjanne** [ankane/pghero#111]
### Request:

PostgreSQL supports SSL client certificates as a modern, secure authentication system for its clients.

### Rationale:

I’m trying to remove all usage of passwords from my systems, and pghero is one of the last projects I’m using that don’t support client certificates (as far as I can see).

**Comment by ankane** [comment]
Hey @justjanne, I haven't tried this, but you should be able to configure parameters like `sslmode=verify-full` and `sslrootcert=path/to/file.pem` in the url you pass PgHero.

**Comment by justjanne** [comment]
Thanks! It works if I just set `sslkey` and `sslcert` in the connector string, and `sslmode=verify-full`.

That said, with custom setting everything in the config, and having to patch parts of the application on every update, it might be nice if some of these things would get a dedicated config option.

**Comment by ankane** [comment]
Hey @justjanne, glad it's working. Not sure I follow having to patch the application to get this to work.

**Comment by justjanne** [comment]
The patching was referring to another recent issue, which afaik isn't resolved yet, regarding running pghero in subfolders. Luckily, I don't need to care about that anymore, as k8s proxy can just rewrite the apth

**Comment by ankane** [comment]
There aren't any open tickets around subfolders.

**Comment by PauloLaScience** [comment]
Nice can you put an example of usage in documentation
Thanks in advance
