### ISSUE TITLE
not answer from curl

### ISSUE THREAD

**Issue by pbobrovnikov** [ankane/pghero#112]
Hi,

I'm run this command : 
[root@node1]# curl --user admin:admin http://127.0.0.1:3001

and command does not return a response.
help!

selinux disabled
firewalld off
Centos7

![image](https://cloud.githubusercontent.com/assets/12830151/24818945/34eb59a0-1beb-11e7-8e12-637bc9a013d6.png)

**Comment by ankane** [comment]
Try running:

```sh
sudo pghero scale web=1
sudo service pghero restart
sudo pghero logs
```

and pasting the output.
