### ISSUE TITLE
`redirect_to :back` is deprecated and will be removed from Rails 5.1.

### ISSUE THREAD

**Issue by helaan** [ankane/pghero#114]
When clicking on the option to enable query stats (or another code path that contains `redirect_to :back`), the following message is printed to the Rails log:

DEPRECATION WARNING: `redirect_to :back` is deprecated and will be removed from Rails 5.1. Please use `redirect_back(fallback_location: fallback_location)` where `fallback_location` represents the location to use if the request has no HTTP referer information. (called from redirect_to at /home/me/.gem/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_controller/metal/redirecting.rb:66)
Redirected to http://localhost:3000/pghero/

Rails 5.1 is very close by, rc's have already been released.

**Comment by ankane** [comment]
Hey @helaan, thanks for reporting. Fixed on master.
