### ISSUE TITLE
Could I track historical query stats every 10 minutes

### ISSUE THREAD

**Issue by songlang1994** [ankane/pghero#115]
Hi Andrew,

I am using Heroku Scheduler for scheduled jobs but scheduler don't support to set a 5 minutes interval. Is there any big problem if I set the interval to 10 minutes.

Thanks you.

![image](https://cloud.githubusercontent.com/assets/19236594/25883194/382870fe-357b-11e7-9bed-356135cb3b95.png)

**Comment by ankane** [comment]
Hey @songlang1994, that'll work totally fine.

**Comment by songlang1994** [comment]
Good news! Thank you very much.
