### ISSUE TITLE
Forcing to listen only on localhost (not 0.0.0.0)

### ISSUE THREAD

**Issue by hvisage** [ankane/pghero#116]
Hi there,

 I know how to change the port that pghero listens on, but I'm in need to have it listen only on localhost, not 0.0.0.0 (or all the other interfaces)

**Comment by ankane** [comment]
Hey @hvisage, I've added a `BIND` env var for this, so you can do:

```
BIND=tcp://127.0.0.1:3000
```

Are you using the Linux package or Docker image?

https://github.com/pghero/pghero/commit/cc821c91cbc715a9752d24fd339e8e0816c60b94
