### ISSUE TITLE
Query stats must be enabled for slow queries

### ISSUE THREAD

**Issue by jontonsoup** [ankane/pghero#117]
I have a db that says: 

`Query stats must be enabled for slow queries`

I'm not exactly sure what is wrong. 
1. I have pg_stats installed. 
```
ERROR:  extension "pg_stat_statements" already exists
```
2. The information about the DB is accessible from the console 

3. I am on AWS and turned on the libraries
```
pg_stat_statements.track ALL <engine-default>
shared_preload_libraries pg_stat_statements <system>
track_activity_query_size 2048 <engine-default>
```
Version: 
PostgreSQL 9.6.1 

Do you have a suggestions for the next step in debugging? This is espeically weird because I have other databases configured properly in the same PGHERO .yml that are working fine.

**Comment by ankane** [comment]
Hey @jontonsoup, be sure to reboot the RDS instance after updating the above parameters.

**Comment by jontonsoup** [comment]
@ankane thanks -- I have rebooted it. 

I was able to get it to spit back this at me: 

```
ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
********** Error **********

ERROR: pg_stat_statements must be loaded via shared_preload_libraries
SQL state: 55000
```

which is weird, given the config I have above.

My guess is that this is not related to pghero, so I'm closing. But if you have any hints on this, I would love them :)

**Comment by jontonsoup** [comment]
Update -- trashing the DB on RGS and making a new one solved this.
