### ISSUE TITLE
integration with PEV

### ISSUE THREAD

**Issue by areski** [ankane/pghero#119]
This is a suggestion, it would be nice if we could integrate with PEV(http://tatiyants.com/postgres-query-plan-visualization/)

Thanks for PGHero, it's an amazing project and it's a life saver!

**Comment by seanlinsley** [comment]
There's already a workflow to do that from the explain page: #43

>Master now has a "Visualize" button on the Explain page that gives output to paste into the Postgres Explain Visualizer. I think this is a good medium between no integration and full integration.
>
>Commit here: 2bd34ad

**Comment by seanlinsley** [comment]
I tried to embed PEV directly, but ran into build issues: https://github.com/AlexTatiyants/pev/issues/16

**Comment by areski** [comment]
Yes it's fair enough! Thanks for updating
