### ISSUE TITLE
relation "pg_hero_connections" does not exist

### ISSUE THREAD

**Issue by manuelmeurer** [ankane/pghero#12]
```
> ActiveRecord::Base.descendants
PG::UndefinedTable: ERROR:  relation "pg_hero_connections" does not exist
LINE 5:                WHERE a.attrelid = '"pg_hero_connections"'::r...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"pg_hero_connections"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

(pry) output error: #<ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "pg_hero_connections" does not exist
LINE 5:                WHERE a.attrelid = '"pg_hero_connections"'::r...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"pg_hero_connections"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

> PgHero::Connection
PG::UndefinedTable: ERROR:  relation "pg_hero_connections" does not exist
LINE 5:                WHERE a.attrelid = '"pg_hero_connections"'::r...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"pg_hero_connections"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

(pry) output error: #<ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "pg_hero_connections" does not exist
LINE 5:                WHERE a.attrelid = '"pg_hero_connections"'::r...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"pg_hero_connections"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
>
```

Happens in dev and prod environment. Version is 0.1.7.

**Comment by ankane** [comment]
PgHero creates a `PgHero::Connection` model without a table.  It's a bit of a hack but haven't found a better way to do it.  Is it causing issues for your application?

**Comment by manuelmeurer** [comment]
Yes it does since I need to call `ActiveRecord::Base.descendants` at one point and then it complaints about the missing table.
What is `Connection` really needed for? It seems like `establish_connection`, `connection_config` and other methods can be called on `ActiveRecord::Base` as well, or am I missing something?

**Comment by ankane** [comment]
The model allows you to set `ENV["PGHERO_DATABASE_URL"]` to use a different user or database than your application.  Does:

```ruby
ActiveRecord::Base.descendants.reject{|d| d == PgHero::Connection }
```

do the trick?

**Comment by manuelmeurer** [comment]
Nope, that generates the same error. I think the solution is to not inherit from `ActiveRecord::Base` but just include/extend the necessary modules like this:

    class Connection
      extend ActiveRecord::ConnectionHandling
      include ActiveRecord::Core
    end

(and maybe a few more are needed)

Then you would need to call `Connection.establish_connection` explicitly before accessing the connection the first time.
Unfortunately I don't have a lot of time to test this out right now but I think it's the right direction. :)

**Comment by kmarshall008** [comment]
Hi @manuelmeurer and @ankane,

Do you have any sense why my rails production app on heroku is having a similar issue, which is causing severe memory leaks? 

The following two SQL statements are consuming 99% of my apps memory in production app on heroku. 

    SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull,     a.atttypid, a.atttypmod FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum WHERE a.attrelid = ?::regclass AND a.attnum > ? AND NOT a.attisdropped ORDER BY a.attnum

    SELECT t.oid, t.typname, t.typelem, t.typdelim, t.typinput, r.rngsubtype, t.typtype, t.typbasetype FROM pg_type as t LEFT JOIN pg_range as r ON oid = rngtypid

My db:rake config file is as follows:
```
namespace :db do
  desc "Fix 'database is being accessed by other users'"
  task :terminate => :environment do
    ActiveRecord::Base.connection.execute <<-SQL
      SELECT
        pg_terminate_backend(pid)
      FROM
        pg_stat_activity
      WHERE
        -- don't kill my own connection!
        pid <> pg_backend_pid()
        -- don't kill the connections to other databases
        AND datname = '#{ActiveRecord::Base.connection.current_database}';
    SQL
  end
end
Rake::Task["db:drop"].enhance ["db:terminate"]
```

I think that what I need to do is create this new class, update my puma.rb file to explicitly point to it and then re-build my production app. 

But... do you think I'm barking up the right tree? 

Thanks much

**Comment by manuelmeurer** [comment]
@kmarshall008 what does this have to do with the issue I reported, let alone PgHero at all?

**Comment by ankane** [comment]
@manuelmeurer Can you try master? https://github.com/ankane/pghero/commit/3f1570c6a215a1f9c7eb77815e34ea33a1728caa

```ruby
gem 'pghero', github: 'ankane/pghero'
```

**Comment by manuelmeurer** [comment]
Works! :shipit:
