### ISSUE TITLE
PG::UndefinedTable after update

### ISSUE THREAD

**Issue by luizkowalski** [ankane/pghero#120]
I was using 1.6.5 and just updated to 2.0.0 and when I open the dashboards, I get this error:

```
PG::UndefinedTable at /
ERROR:  relation "pg_replication_slots" does not exist
LINE 1: SELECT slot_name, database, active FROM pg_replication_slots
```
I didn't find anything on the issues nor on Changelog.

**Comment by ankane** [comment]
Hey @luizkowalski, thanks for reporting. Looks like that view is only available in PostgreSQL 9.4+. Pushing a fix now.

**Comment by ankane** [comment]
Hey @luizkowalski, can you confirm it works with `master`?

**Comment by luizkowalski** [comment]
yep, perfect! thanks :D
