### ISSUE TITLE
Can't secure this other than HTTP/Devise?

### ISSUE THREAD

**Issue by myfitment** [ankane/pghero#122]
Would love to secure this in a way other than HTTP or Devise. There doesn't appear to immediately be a way to do so using standard practices in ```routes.rb```.

For example, you can secure Sidekiq like so:

    mount Sidekiq::Web => '/sidekiq', :constraints => AdminConstraint.new, :as => "sidekiq"

I guess because there's no routing in the codebase.

Is there any plans to add something like this? Not everybody uses Devise, and ENV variables complicate deployment. Definitely don't want to hardcode the auth values it in an initializer.

**Comment by ankane** [comment]
Hey @myfitment, any options that work with mount (like constraints) should work as well.

**Comment by myfitment** [comment]
It appears to be expecting a Rack middleware, which I think is why it's failing.

**Comment by ankane** [comment]
Hey @myfitment, I'm able to get `constraints` working fwiw. Maybe it's specific to your `AdminConstraint` code?

**Comment by myfitment** [comment]
Could be, I'll check and report back.

**Comment by ankane** [comment]
Cleaning up issues. Please report back if you found anything @myfitment so others can benefit.
