### ISSUE TITLE
NoMethodError: undefined method to_i for Hash (QueryStats)

### ISSUE THREAD

**Issue by rdlugosz** [ankane/pghero#123]
Hi - 

Just trying this out for the first time on one of my apps. After deploying to Heroku & doing the migrations for query_stats, I'm getting a crash when I try to load the PGHero dashboard or run the `capture_query_stats` task.

```
NoMethodError: undefined method `to_i' for #<Hash:0x007f0b2bef35c0>
Did you mean?  to_s
               to_a
               to_h
/app/vendor/bundle/ruby/2.4.0/gems/pghero-2.0.2/lib/pghero/methods/query_stats.rb:256:in `block in combine_query_stats'
/app/vendor/bundle/ruby/2.4.0/gems/pghero-2.0.2/lib/pghero/methods/query_stats.rb:250:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/pghero-2.0.2/lib/pghero/methods/query_stats.rb:250:in `combine_query_stats'
/app/vendor/bundle/ruby/2.4.0/gems/pghero-2.0.2/lib/pghero/methods/query_stats.rb:8:in `query_stats'
/app/vendor/bundle/ruby/2.4.0/gems/pghero-2.0.2/lib/pghero/methods/query_stats.rb:103:in `block in capture_query_stats'
/app/vendor/bundle/ruby/2.4.0/gems/pghero-2.0.2/lib/pghero/methods/query_stats.rb:102:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/pghero-2.0.2/lib/pghero/methods/query_stats.rb:102:in `capture_query_stats'
...
```

Seems... unexpected. Here's a [link to line 256 where it's blowing up](https://github.com/ankane/pghero/blob/a4e2621b835aac7ad065751bed94892c30da1b5e/lib/pghero/methods/query_stats.rb#L256), which is being called from [way up in line 8](https://github.com/ankane/pghero/blob/a4e2621b835aac7ad065751bed94892c30da1b5e/lib/pghero/methods/query_stats.rb#L8).

Thoughts on what might be going on here? Works in dev without query stats enabled.

**Comment by ankane** [comment]
Hey @rdlugosz, thanks for reporting 👍  I don't see why sum would be returning a hash. Only thing that comes to mind right now is something could be monkey patching `sum`.

**Comment by rdlugosz** [comment]
Agree. Seems bizarre. I'll debug a bit and report back what I find... I
don't *think* I've got any major patching going on but maybe.

**Comment by ankane** [comment]
What versions of Rails and Ruby are you on?

**Comment by rdlugosz** [comment]
Rails 4.2.8, Ruby 2.4.1. 

Possibly unrelated (but maybe not) I just discovered that I get a crash in dev (where I don't yet have stats enabled) when I click on the Connections menu option (on the left). The dashboard home loads fine.

```
NoMethodError - undefined method `+' for #<Hash:0x007fdda2c97a98>:
  statsample (2.0.2) lib/statsample.rb:58:in `sum'
  pghero (2.0.2) app/controllers/pg_hero/home_controller.rb:244:in `connections'
  actionpack (4.2.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
...
```

Again, may not be related. Going to grab a local copy of the gem so that I can debug a bit.

**Comment by rdlugosz** [comment]
Ah... wtf - didn't even notice that the first line of that dump said "statsample"... looks like that gem is colliding or something.

**Comment by rdlugosz** [comment]
Yep - looks like this is an (issue of statsample monkey patching Array with a #sum method)[https://github.com/SciRuby/statsample/issues/58].

That would also explain why this is blowing up when `#sum` is used in combining the stats.

Going to close since this is not your issue. Thanks!
