### ISSUE TITLE
CentOS / RHEL 7 packager.io: pghero v2 packages are no longer signed

### ISSUE THREAD

**Issue by majodev** [ankane/pghero#128]
It seems that the latest pghero v2 packages inside the [CentOS / RHEL 7 packager.io repo](https://packager.io/gh/pghero/pghero) are *no longer* signed:

```bash
$ yum update pghero
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centosmirror.netcup.net
 * epel: mirror.wiuwiu.de
 * extras: mirror.daniel-jost.net
 * updates: mirror.daniel-jost.net
Resolving Dependencies
--> Running transaction check
---> Package pghero.x86_64 0:1.7.0-1494644797.cc821c9.centos7 will be updated
---> Package pghero.x86_64 0:2.0.2-1502421801.851e4397.centos7 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

=================================================================================
 Package    Arch       Version                                  Repository  Size
=================================================================================
Updating:
 pghero     x86_64     2.0.2-1502421801.851e4397.centos7        pghero      36 M

Transaction Summary
=================================================================================
Upgrade  1 Package

Total size: 36 M
Is this ok [y/d/N]: y
Downloading packages:


Package pghero-2.0.2-1502421801.851e4397.centos7.x86_64.rpm is not signed
```
As this is quite a critical package with direct access to potentially any data inside a PostgreSQL database, I wanted to ask if there is a rationale behind that?

For reference, here's typical a gpg enforced yum repo config:
```bash
[pghero]
name=Repository for pghero/pghero application.
baseurl=https://rpm.packager.io/gh/pghero/pghero/centos7/master
enabled=1
gpgcheck=1
gpgkey=https://dl.packager.io/srv/pghero/pghero/key
```

**Comment by ankane** [comment]
Hey @majodev, thanks for reporting 👍 

It looks like Packager.io [updated their repositories](https://blog.packager.io/posts/24-change-of-repository-urls) recently. Try:

```sh
sudo wget -O /etc/yum.repos.d/pghero.repo \
  https://dl.packager.io/srv/pghero/pghero/master/installer/el/7.repo
sudo yum install pghero
```

**Comment by majodev** [comment]
Thanks for your response!

This would lead to the following yum repo config (`curl https://dl.packager.io/srv/pghero/pghero/master/installer/el/7.repo`):
```bash
[pghero]
name=Repository for pghero/pghero (master) packages.
baseurl=https://dl.packager.io/srv/rpm/pghero/pghero/master/el/7/$basearch
enabled=1
gpgcheck=0
repo_gpgcheck=1
gpgkey=https://dl.packager.io/srv/pghero/pghero/key
```
As you can see, `gpgcheck` is still disabled, manually enabling it leads to the same `Package pghero-2.0.2-1502421801.851e4397.centos7.x86_64.rpm is not signed` error as before.

**Comment by ankane** [comment]
Hey @majodev, I'm not super familiar w/ `yum` and its security unfortunately.

**Comment by ankane** [comment]
Closing out stale discussions

**Comment by crohr** [comment]
@majodev just for reference (I'm the Packager.io maintainer), it is tricky to enable GPG signing of the package itself since pghero's maintainer would need to upload a GPG key, and somehow provide a passphrase at build time, which is not possible. That or a passphrase-less key, but then it's not much better than no key at all. Signing the repository metadata is what is usually done and ensures that the package comes from a trusted source.

**Comment by majodev** [comment]
@crohr nevermind, it's no longer a problem for us, as we are now using the docker images. Anyways, thanks for the info.
