### ISSUE TITLE
Feature Request: Authentication

### ISSUE THREAD

**Issue by nhumrich** [ankane/pghero#129]
Would be awesome to have some type of authentication portal for this. Maybe a simple github oauth that restricts to an org?
Could work just by passing in a github application id/secret/org name?

**Comment by ankane** [comment]
Hey @nhumrich, thanks for the suggestion 👍 

If you use the Rails version, you can set up Devise with any Omniauth provider.

Otherwise, I'd recommend checking out OAuth2 proxy: https://github.com/bitly/oauth2_proxy

**Comment by nhumrich** [comment]
Cool, thanks! Feel free to close this if you want.
Or leave it around if you plan on implementing this one day. Up to you :)
