### ISSUE TITLE
CentOS / RHEL 6 packager.io: requested datatype filelists not available

### ISSUE THREAD

**Issue by Carthaca** [ankane/pghero#133]
Hi,

as suggested at [packager.io](https://packager.io/gh/pghero/pghero/builds/25/install/centos-6) I run on my RHEL 6.8

```
sudo wget -O /etc/yum.repos.d/pghero.repo \
  https://dl.packager.io/srv/pghero/pghero/master/installer/el/6.repo
```

to add the repo. A simple `sudo yum --disablerepo=* --enablerepo=pghero makecache -d 3` fails after that with:
```
Yum Version: 3.2.29
pghero/signature                                                                                                                     |  473 B     00:00 ... 
pghero/signature                                                                                                                     |  577 B     00:00 ... 
Error: requested datatype filelists not available
```

I appreciate any hint how to make that repo working again.

**Comment by Kuckkuck** [comment]
+1

**Comment by ankane** [comment]
Hey @Carthaca, thanks for reporting 👍  Unfortunately, I'm not very familiar with `yum`, so maybe someone else can weigh in.

**Comment by ankane** [comment]
There's not much we can do here, so closing this out
