### ISSUE TITLE
multiple dbs requires that you first set a single database

### ISSUE THREAD

**Issue by alex-pw** [ankane/pghero#136]
Thanks for pghero! 

I noticed that if I try to apply a yml file with multiple databases on a fresh install I get an error about a missing "config/database.yml".

If I set a single db first on the CLI and then apply the yml file with multiple dbs after that, everything is ok.  This workaround is fine.

**Comment by ankane** [comment]
Hey @alex-pw, thanks for reporting 👍  This is fixed on master. For reference: https://github.com/pghero/pghero/commit/2aff0d5383fc363f22b77960d5dfc89e17121cf9
