### ISSUE TITLE
PG::InvalidTextRepresentation: ERROR

### ISSUE THREAD

**Issue by thiagotonon** [ankane/pghero#137]
I'm using pghero 2.0 and I have a worker running historical query stats every 5 minutes.

```ruby
class Cron::PgheroQueryStats
  include Sidekiq::Worker

  sidekiq_options queue: :cron

  def perform
    PgHero.capture_query_stats
  end
end
```

After analyzing my logfile, some strange `PG::InvalidTextRepresentation: ERROR` errors appeared, and I don't now why (probably query string too big?)

`
ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR: invalid input syntax for integer: "e41d38fc6567471aea2b368a752b31d9" LINE 5: ...NULL)',16318.116,489,'2017-08-24 20:33:09.582752','e41d38fc6... ^ : INSERT INTO "pghero_query_stats" ("database","query","total_time","calls","captured_at","query_hash","user") VALUES (....'
`

Thanks!

**Comment by ankane** [comment]
Hey @thiagotonon, try upgrading to the latest version (dup of #134)
