### ISSUE TITLE
Sprockets::Rails::Helper::AssetNotPrecompiled with Rails 5.1

### ISSUE THREAD

**Issue by fabiokr** [ankane/pghero#139]
rails 5.1.3
pghero 2.0.3

```
Sprockets::Rails::Helper::AssetNotPrecompiled in PgHero::Home#index
Showing /var/lib/gems/2.3.0/gems/pghero-2.0.3/app/views/layouts/pg_hero/application.html.erb where line #7 raised:

Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( pghero/favicon.png )` to `config/initializers/assets.rb` and restart your server
```

Adding that config to my app solves it, but is this something that pghero should config itself on its engine?

**Comment by ankane** [comment]
Hey @fabiokr, thanks for reporting 👍  This was fixed in https://github.com/ankane/pghero/commit/3dd2778a17d187d5c20d3507ac7fb4874ae34942. Just released a new version with the fix.
