### ISSUE TITLE
insufficient privilege

### ISSUE THREAD

**Issue by seanlinsley** [ankane/pghero#14]
Our single most expensive query shows up as `<insufficient privilege>`:

![screen shot 2015-01-10 at 2 38 04 pm](https://cloud.githubusercontent.com/assets/688886/5693159/6b45b1a2-98d6-11e4-8bbf-5cd9e5745b5a.png)

I was able to discover the query in question by manually running `slow_queries` as the `postgres` user. Turns out it's a query run by a different database user than the one hosting PGHero. From a non-superuser account you can see this by joining the `pg_user` table:
```sql
SELECT u.usename, (total_time / 1000 / 60) as total_minutes,
  (total_time/calls) as average_time, query 
FROM pg_stat_statements p 
JOIN pg_user u ON (u.usesysid = p.userid) ORDER BY 2 DESC LIMIT 1;
 usename | total_minutes |   average_time   |          query           
---------+---------------+------------------+--------------------------
 foo     |   199.0077556 | 333.073461212308 | <insufficient privilege>
 bar     |   170.0383281 | 165.831729885244 | SELECT ...;
(1 row)
```

Where `bar` is the current account in use, and `foo` is the other account.

Assuming there's no way to solve this without running PGHero with superuser permissions, it might be good to document the error in the README / inline on the web page.

**Comment by ankane** [comment]
You're correct.  You must use a superuser to see queries executed by other users.  Added a note to the readme.  Inline would be good as well if you'd like to submit a pull request.
