### ISSUE TITLE
Some indexes are shown as "unused". 

### ISSUE THREAD

**Issue by jun1111** [ankane/pghero#140]
Hi,

In the Space tab of my PgHero, it shows all indexes (apart from one index) as being "unused". The database it is connected to is a new database that has been populated with schemas / tables through pg_restore. The auto-vacuum in the db is on, and it has run for some of the schemas. 

All the indexes shown as "unused" are single column indexes. Can you explain to me how do you decide that they have been "unused"? 

I am using the latest version of PgHero. The version of PostgreSQL is 9.6.

Thanks.

**Comment by ankane** [comment]
Hey @jun1111, if you've just populated the database, the indexes likely have never been used. Postgres keeps internal stats on index access, which PgHero uses. See the source code for the exact query.
