### ISSUE TITLE
Queries returning only 0ms

### ISSUE THREAD

**Issue by JonathanGonczoroski** [ankane/pghero#143]
Hello, I installed **pghero** on my server, and it is running fine, however, I noticed that almost all my queries, which have already run several times, the average continues 0ms. I know they take longer than that, is there any limitation or something so I do not take the time ?

**Comment by ankane** [comment]
Hey @JonathanGonczoroski, I haven't heard of a similar issue before. Queries can complete in less than 0.5 ms, in which case they will be rounded down to 0 ms.

**Comment by JonathanGonczoroski** [comment]
Thank you!!
