### ISSUE TITLE
how I could run it in a subpath ?

### ISSUE THREAD

**Issue by alex-left** [ankane/pghero#145]
now only work if I configure to listen in a domain (ex. pghero.domain.com)

But how could make if I want to install in a subpath? For example:
mydomain.com/pghero/

I don't see any variable to reference something like "base_url" or "base_path",

**Comment by ankane** [comment]
Hey @alex-left, are you using the Rails, Docker, or Linux install?

**Comment by alex-left** [comment]
linux install

**Comment by ankane** [comment]
Hey @alex-left, I've added support for a `BASE_PATH` env var and pushed a new package (version `f755cb57`). Give it a shot.

**Comment by alex-left** [comment]
great, a lot of thanks for your quick response. 
seems works fine but not with all urls,  still requesting some js without base_path, for example:

http://10.10.0.2/assets/pghero/application-3067953a47cc9b4fefa33bf65792691f8b3fca10887388f33f4085f7b6cf1940.js

**Comment by ankane** [comment]
Hey @alex-left, just found out Rails has a built-in setting for this. Try setting `RAILS_RELATIVE_URL_ROOT` env var to `/your-path` instead of using `BASE_PATH`. http://edgeguides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root

**Comment by ankane** [comment]
I was able to get it working with `cde0d4e2`.

**Comment by alex-left** [comment]
yeah! now works fine! a lot of thanks @ankane

**Comment by semente** [comment]
Hey @ankane, would be great if you document this `RAILS_RELATIVE_URL_ROOT` setting somewhere in pghero docs. Thanks ;)
