### ISSUE TITLE
Rails Engine: NoMethodError in PgHero::Home#index

### ISSUE THREAD

**Issue by josephpage** [ankane/pghero#147]
Rails **API** 5.1.4
PgHero 2.0.5

```
ActionView::Template::Error (undefined method `flash' for #<ActionDispatch::Request:0x000000000631cc60>):
10:   </head>
11:   <body>
12:     <div class="container">
13:       <div class="alert alert-<%= alert ? "danger" : "info" %>">
14:         <% if alert %>
15:           <%= alert %>
16:         <% elsif notice %>

actionpack (5.1.4) lib/action_controller/metal/flash.rb:36:in `block (2 levels) in add_flash_types'
actionpack (5.1.4) lib/abstract_controller/helpers.rb:68:in `alert'
pghero (2.0.5views) layouts/pg_hero/application.html.erb:13:in `__usr_local_bundle_gems_pghero______views_layouts_pg_hero_application_html_erb___180194808135113254_43334040'
actionview (5.1.4) lib/action_view/template.rb:157:in `block in render'
```

[Full logs attached here (16ko)](https://github.com/ankane/pghero/files/1325151/issue-147.log.txt).
Thanks !

**Comment by ankane** [comment]
Hey @josephpage, thanks for the report 👍  PgHero doesn't work with Rails API.

**Comment by josephpage** [comment]
> PgHero doesn't work with Rails API.

Ouch! Maybe we should fix that ? What are the blocking points ?

**Comment by ankane** [comment]
It's a web dashboard, not an API.

![giphy 2](https://user-images.githubusercontent.com/220358/30755087-1cc2df52-9f7a-11e7-92a5-4f7d3844532c.gif)

**Comment by josephpage** [comment]
For sure !
But developing/maintaining an API doesn't mean you don't want cool, colorful and easy to use tools to monitoring what's happening inside of it.
