### ISSUE TITLE
How to run it for development?

### ISSUE THREAD

**Issue by seban** [ankane/pghero#150]
I would like to work with this code and maybe even extend `phgero` with new features but is there any guide for developing it locally?

**Comment by ankane** [comment]
Hey @seban, thanks for your interest in contributing. Here are instructions for getting set up:

```sh
git clone https://github.com/ankane/pghero.git
git clone https://github.com/pghero/pghero.git pghero-dev
cd pghero-dev
git checkout dev
createdb pghero_dev
export DATABASE_URL=postgres:///pghero_dev
bundle exec rails generate pghero:query_stats
bundle exec rails generate pghero:space_stats
bundle exec rake db:migrate
foreman start
```

And visit [http://localhost:5000](http://localhost:5000)

**Comment by seban** [comment]
Thanks for description and adding `Contribution.md` guide. 👏 
Issue solved.
