### ISSUE TITLE
Authentication - setting up username & password

### ISSUE THREAD

**Issue by saurabhxkapoor** [ankane/pghero#153]
I tried to add username and password to my pghero docker instance by running following commands, neither of them worked. Could you point out what is wrong ?

`docker run -e PGHERO_USERNAME=administrator -e PGHERO_PASSWORD=abcd1234 DATABASE_URL=postgres://abcd:1234@xxxx-dev.xxxx.us-region-1.rds.amazonaws.com:5432/devdb ankane/pghero bin/rake`

`docker run -e PGHERO_USERNAME=administrator -e PGHERO_PASSWORD=abcd1234`

I got the below error when I tried to execute the above commands:
`error: docker: invalid reference format.`

**Comment by ankane** [comment]
Hey @saurabhxkapoor, looks like you're missing a `-e` before `DATABASE_URL`.

**Comment by saurabhxkapoor** [comment]
We tried with the following command and this time got error:

`docker run -e PGHERO_USERNAME=administrator -e PGHERO_PASSWORD=abcd1234 -e DATABASE_URL=postgres://admin:password123@aerial-db-dev.us-east-1.rds.amazonaws.com:5432/zurbochen ankane/pghero bin/rake`

Error:
/usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- /app/test (LoadError)
	from /usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /usr/local/bundle/gems/railties-5.0.1/lib/rails/test_unit/test_requirer.rb:11:in `block in require_files'
	from /usr/local/bundle/gems/railties-5.0.1/lib/rails/test_unit/test_requirer.rb:10:in `each'
	from /usr/local/bundle/gems/railties-5.0.1/lib/rails/test_unit/test_requirer.rb:10:in `require_files'
	from /usr/local/bundle/gems/railties-5.0.1/lib/rails/test_unit/minitest_plugin.rb:86:in `plugin_rails_init'
	from /usr/local/bundle/gems/minitest-5.10.1/lib/minitest.rb:80:in `block in init_plugins'
	from /usr/local/bundle/gems/minitest-5.10.1/lib/minitest.rb:78:in `each'
	from /usr/local/bundle/gems/minitest-5.10.1/lib/minitest.rb:78:in `init_plugins'
	from /usr/local/bundle/gems/minitest-5.10.1/lib/minitest.rb:129:in `run'
	from /usr/local/bundle/gems/railties-5.0.1/lib/rails/test_unit/minitest_plugin.rb:73:in `run'
	from /usr/local/bundle/gems/minitest-5.10.1/lib/minitest.rb:62:in `block in autorun'

**Comment by ankane** [comment]
Hey @saurabhxkapoor, bin/rake tries to run the tests. Be sure to copy the full command from the docs.

**Comment by Zurbotron** [comment]
Sorry, maybe we're being dense, but this is the command we're seeing in the docs:

> docker run -e PGHERO_USERNAME=link -e PGHERO_PASSWORD=hyrule ...

We weren't entirely sure what to replace the ellipses with, so we just replaced with the following line per our earlier discussion which is still maybe incorrect?

> -e DATABASE_URL=postgres://admin:password123@aerial-db-dev.us-east-1.rds.amazonaws.com:5432/zurbochen ankane/pghero bin/rake

**Comment by ankane** [comment]
@Zurbotron Check the docs here for valid commands: https://github.com/ankane/pghero/blob/master/guides/Docker.md (none of them end in `bin/rake`)

**Comment by Zurbotron** [comment]
Gotcha, thanks! It worked once we removed the bin/rake. 

A somewhat related and perhaps an equally dense question. 

We are using primary and replica DB. In this scenario you recommend creating a config file, but it's unclear to me how we make use of the config file using Docker.

Without the yml file I assume we'd have to run multiple commands as in:
docker run -e DATABASE_URL=primary ...
docker run -e DATABASE_URL=replica ...

How do we avoid that and make use of the /app/config/pghero.yml file?

**Comment by ankane** [comment]
One way is to create a new Dockerfile based on `ankane/pghero:latest` that adds the `pghero.yml` file.

**Comment by Zurbotron** [comment]
Ok, so if we create a new Dockerfile that adds the yml file, I guess I'm still not following what the commands look like that we then need to run. Do we simply run all the commands as normal excluding any references to DATABASE_URL as in the following: 

docker run -e -p 8080:8080 ankane/pghero
docker run -ti -e bin/rake pghero:capture_space_stats
docker run -ti -e bin/rake pghero:capture_query_stats

Is a legitimate alternative to using yml simply run all 3 of the above commands for each database or is that going to basically break since it will try and setup 1 pghero enviroment per DB instead of 1 pghero environment for all X DBs?

Thanks!

**Comment by ankane** [comment]
I would use the `yml` config file if you have multiple databases so you can view them all together in the web UI. If you do this, you don't need to pass the `-e DATABASE_URL`. When you run `pghero:capture_query_stats` once, PgHero will loop over the databases in the `yml` file and capture stats for each of them.
