### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by velinbudinov** [ankane/pghero#154]
Hi guys,

I've issue with accessing dashboard:

curl -v http://localhost:3001/
* About to connect() to localhost port 3001 (#0)
*   Trying ::1...
* Connection refused
*   Trying 127.0.0.1...
* connected
* Connected to localhost (127.0.0.1) port 3001 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.26.0
> Host: localhost:3001
> Accept: */*
>
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/html; charset=UTF-8
< X-Request-Id: b4cb0bbc-8960-474d-8329-5ff4220b5143
< X-Runtime: 0.375525
< Content-Length: 0
<
* Connection #0 to host localhost left intact
* Closing connection #0

logs:
[27701] Puma starting in cluster mode...
[27701] * Version 3.10.0 (ruby 2.4.2-p198), codename: Russell's Teapot
[27701] * Min threads: 1, max threads: 16
[27701] * Environment: production
[27701] * Process workers: 3
[27701] * Preloading application
[27701] * Listening on tcp://0.0.0.0:3001
[27701] Use Ctrl-C to stop
[27701] - Worker 0 (pid: 27720) booted, phase: 0
[27701] - Worker 2 (pid: 27734) booted, phase: 0
[27701] - Worker 1 (pid: 27730) booted, phase: 0

Any ideas how to fix it

Regards,

**Comment by velinbudinov** [comment]
I've tried to install it on another server (ubuntu 12.04) with PostgreSQL 9.6
Ran following command to update extension:
ALTER EXTENSION pg_stat_statements UPDATE;
NOTICE:  version "1.4" of extension "pg_stat_statements" is already installed
ALTER EXTENSION

and got 500 error again:
pghero logs
==> /var/log/pghero/production.log <==
Started GET "/" for 127.0.0.1 at 2017-10-09 10:46:31 +0300
Processing by PgHero::HomeController#index as */*
Completed 500 Internal Server Error in 752ms (ActiveRecord: 590.8ms)
  
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column "queryid" does not exist
LINE 1: ...ry_stats AS ( SELECT LEFT(query, 10000) AS query, queryid AS...
                                                             ^
HINT:  Perhaps you meant to reference the column "pg_stat_statements.query".
: WITH query_stats AS ( SELECT LEFT(query, 10000) AS query, queryid AS query_hash, rolname AS user, (total_time / 1000 / 60) AS total_minutes, (total_time / calls) AS average_time, calls FROM pg_stat_statements INNER JOIN pg_database ON pg_database.oid = pg_stat_statements.dbid INNER JOIN pg_roles ON pg_roles.oid = pg_stat_statements.userid WHERE pg_database.datname = current_database() ) SELECT query, query_hash, query_stats.user, total_minutes, average_time, calls, total_minutes * 100.0 / (SELECT SUM(total_minutes) FROM query_stats) AS total_percent, (SELECT SUM(total_minutes) FROM query_stats) AS all_queries_total_minutes FROM query_stats ORDER BY "total_minutes" DESC LIMIT 100):
  
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:620:in `async_exec'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:620:in `block (2 levels) in exec_no_cache'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:619:in `block in exec_no_cache'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
vendor/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:618:in `exec_no_cache'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:605:in `execute_and_clear'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:361:in `select'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract/database_statements.rb:42:in `select_all'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract/query_cache.rb:97:in `select_all'
vendor/bundle/ruby/2.3.0/gems/pghero-2.0.2/lib/pghero/methods/basic.rb:56:in `select_all'
vendor/bundle/ruby/2.3.0/gems/pghero-2.0.2/lib/pghero/methods/query_stats.rb:165:in `current_query_stats'
vendor/bundle/ruby/2.3.0/gems/pghero-2.0.2/lib/pghero/methods/query_stats.rb:5:in `query_stats'
vendor/bundle/ruby/2.3.0/gems/pghero-2.0.2/app/controllers/pg_hero/home_controller.rb:43:in `index'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/abstract_controller/base.rb:186:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_controller/metal/rendering.rb:30:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/callbacks.rb:131:in `run_callbacks'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_controller/metal/rescue.rb:20:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/notifications.rb:166:in `block in instrument'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/notifications.rb:166:in `instrument'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.0/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/abstract_controller/base.rb:124:in `process'
vendor/bundle/ruby/2.3.0/gems/actionview-5.1.0/lib/action_view/rendering.rb:30:in `process'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_controller/metal.rb:189:in `dispatch'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_controller/metal.rb:253:in `dispatch'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/routing/route_set.rb:31:in `serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/routing/mapper.rb:46:in `serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:46:in `block in serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:33:in `each'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:33:in `serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/routing/route_set.rb:832:in `call'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.0/lib/rails/engine.rb:522:in `call'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.0/lib/rails/railtie.rb:185:in `public_send'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.0/lib/rails/railtie.rb:185:in `method_missing'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/routing/mapper.rb:46:in `serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:46:in `block in serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:33:in `each'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:33:in `serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/routing/route_set.rb:832:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/conditional_get.rb:25:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/cookies.rb:613:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/callbacks.rb:97:in `run_callbacks'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.0/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.0/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.0/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.0/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.0/lib/rails/engine.rb:522:in `call'
vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
==> /var/log/pghero/web-1.log <==
[20164] Puma starting in cluster mode...
[20164] * Version 3.8.2 (ruby 2.3.1-p112), codename: Sassy Salamander
[20164] * Min threads: 1, max threads: 16
[20164] * Environment: production
[20164] * Process workers: 3
[20164] * Preloading application
[20164] * Listening on tcp://0.0.0.0:3001
[20164] Use Ctrl-C to stop
[20164] - Worker 0 (pid: 20185) booted, phase: 0
[20164] - Worker 2 (pid: 20191) booted, phase: 0
[20164] - Worker 1 (pid: 20189) booted, phase: 0

**Comment by ankane** [comment]
Hey @velinbudinov, you need to drop and recreate the extension.

**Comment by velinbudinov** [comment]
Thanks @ankane , that fix it :)

**Comment by romanr** [comment]
Also having this error. This too common, should be definitely added to the Guide.

**Comment by TianyangLi** [comment]
@velinbudinov - Hi, i'm experiencing the same issue. Could you please detail what you did to resolve it?
I've also tried dropping and recreating the extension to no avail...

**Comment by pol1000000** [comment]
the same problem. tried to drop and recreate extension and it doesn't work

**Comment by larinam** [comment]
Helped recreation described here:
https://github.com/ankane/pghero/issues/9#issuecomment-52211015
