### ISSUE TITLE
No support for Rails API.

### ISSUE THREAD

**Issue by rmontgomery429** [ankane/pghero#155]
I'm not sure why this is the case but assuming there is a good reason it seems like a good idea to at least mention this in the docs... no? 

I didn't learn about this limitation until very late in the process when my first attempt at navigating to `/pghero` returned: 

`No support for Rails API. See https://github.com/pghero/pghero for a standalone app.`

**Comment by ankane** [comment]
Hey @rmontgomery429, you can use PgHero with Rails API, just not the web dashboard (it's meant for APIs, not views/assets, after all).

**Comment by sk-** [comment]
@ankane Any technical reason why the dashboard is disabled. Sidekiq's dashboard works just fine in an API only app and it's also an engine.

**Comment by ankane** [comment]
@sk- Sidekiq uses a Rack app, not an engine.

**Comment by sk-** [comment]
@ankane Then would it be possible to change the dashboard to be a Rack app.

**Comment by mhenrixon** [comment]
Other engines work fine, I am using rails API with rswag (swagger docs), I also use administrate without problem for my rails API application. So... long story short, what is the problem?

**Comment by mhenrixon** [comment]
Other engines work fine, I am using rails API with rswag (swagger docs), I also use administrate without problem for my rails API application. So... long story short, what is the problem @ankane ?

**Comment by ankane** [comment]
Gems like administrate require [special instructions](https://administrate-prototype.herokuapp.com/rails_api) to work with Rails API (essentially, adding much of the middleware back manually, which pretty much defeats the purpose of the `api_only` setting). Unfortunately, this isn't something I'd like to continuously test/support.

You're welcome to fork the gem and maintain a version for the community though.
