### ISSUE TITLE
Rails 5 Assets for pghero aren't served from CloudFront CDN

### ISSUE THREAD

**Issue by Ch4s3** [ankane/pghero#156]
This may be my fault and a config issue, but just in case I'm posting here.
I'm serving my assets from CloudFtont, and my regular assets work.

My `production.rb` has 
```ruby
config.action_controller.asset_host = 'MYHOST.cloudfront.net'
```

And I'm using the rack cors gem configures as such:

```ruby
## Configure Rack CORS Middleware, so that CloudFront can serve our assets.
## See https://github.com/cyu/rack-cors

if defined? Rack::Cors
  Rails.configuration.middleware.insert_before 0, Rack::Cors do
      allow do
          origins %w[
              https://news.ink-stream.com
              http://news.ink-stream.com
          ]
          resource '/assets/*'
      end
  end
end
```

Nevertheless I get a 502 from CloudFront for pghero's assets. Am I missing something obvious?

**Comment by ankane** [comment]
Hey @Ch4s3, this sounds like an issue with your CloudFront configuration rather than PgHero.

**Comment by Ch4s3** [comment]
I think it was an ssl issue.
