### ISSUE TITLE
Erro Enconding 

### ISSUE THREAD

**Issue by hfranzin** [ankane/pghero#157]
it is possible to connect with ASCII bank, because I am having error of

"ERROR: invalid byte sequence for encoding" UTF8 ": 0xf3 0x64 0x69"

Is it skewed?
Is it possible to put the encoding as LATIN1?

**Comment by ankane** [comment]
Hey @hfranzin, I don't really follow. Can you provide more context and give an example?

**Comment by ankane** [comment]
Cleaning up stale issues
