### ISSUE TITLE
Can pg_query_stats and pg_space_stats tables be placed in pghero schema?

### ISSUE THREAD

**Issue by Zurbotron** [ankane/pghero#160]
Based on recommendation to create a pghero schema https://github.com/ankane/pghero/blob/master/guides/Permissions.md 

I thought I'd also try to create the pg_query_stats and pg_space_stats in the pghero schema rather than public schema just to keep everything together. But the following commands failed when I tried to do this:

docker run -ti -e DATABASE_URL=... ankane/pghero bin/rake pghero:capture_query_stats
docker run -ti -e DATABASE_URL=... ankane/pghero bin/rake pghero:capture_space_stats

I assume these tables just need to stay in public schema?

Thanks!

**Comment by ankane** [comment]
Hey @Zurbotron, that's correct.
