### ISSUE TITLE
Function name change(s) in PostgreSQL 10

### ISSUE THREAD

**Issue by lettergram** [ankane/pghero#163]
I'm receiving the following error due to an upgrade to postgreSQL 10:

```
PG::UndefinedFunction: ERROR: function pg_last_xlog_receive_location() does not exist LINE 1: SELECT CASE WHEN pg_last_xlog_receive_location() = pg_last_x... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts. : SELECT CASE WHEN pg_last_xlog_receive_location() = pg_last_xlog_replay_location() THEN 0 ELSE EXTRACT (EPOCH FROM NOW() - pg_last_xact_replay_timestamp()) END AS replication_lag
```

This is due to some function renaming:

https://wiki.postgresql.org/wiki/New_in_postgres_10#Renaming_of_.22xlog.22_to_.22wal.22_Globally_.28and_location.2Flsn.29

Many of the columns in pg_stat_replication table has changed.

Below is a screen shot of my issue:

![pghero-error](https://user-images.githubusercontent.com/1498748/32701142-cb6623b4-c795-11e7-943c-1055ddd37e82.png)

I've seen this error fixed using the following method(s):

https://github.com/sensu-plugins/sensu-plugins-postgres/pull/41/files

We can also do:

```
CREATE FUNCTION pg_catalog.pg_current_xlog_location() RETURNS pg_lsn AS $$
BEGIN
    RETURN pg_current_wal_lsn();
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION pg_catalog.pg_last_xlog_receive_location() RETURNS pg_lsn AS $$
BEGIN
    RETURN pg_last_wal_receive_lsn();
END;
$$ LANGUAGE plpgsql;
```

@ankane I'm alright submitting a PR, but is there a preferred method?

**Comment by ankane** [comment]
Hey @lettergram, thanks for reporting 👍 

Let's go with the first method (can check if `server_version_num >= 100000`).

**Comment by lettergram** [comment]
Added PR #164
