### ISSUE TITLE
InternalServer error with PgTemp with Sequense 

### ISSUE THREAD

**Issue by allustin** [ankane/pghero#166]
Example error

```
 ActiveRecord::StatementInvalid (PG::UndefinedFile: ERROR:  could not open file "base/17533/t8_149636": No such file or directory
PgHero_1           | : SELECT last_value FROM "pg_temp_8"."tt1_sdbl_identity_seq"):
```

latest pghero have an error with working on temp_table with sequense

temp_table does not visible for monitor process by design

**Comment by ankane** [comment]
As mentioned in the PR, please give master a shot.

**Comment by ankane** [comment]
Closing due to no response.

**Comment by allustin** [comment]
@ankane - i have missed  email from github. Sorry.

i will check this and #263
