### ISSUE TITLE
Multiple database in heroku deploy

### ISSUE THREAD

**Issue by daneoshiga** [ankane/pghero#169]
That's not clear how (or if it's possible) to monitor several databases when running pghero on heroku, since multiple database depends on change configuration file, and heroku uses just the DATABASE_URL config.

**Comment by ankane** [comment]
Hey @daneoshiga, you should be able to download the repo from Heroku and follow the Rails instructions.

**Comment by daneoshiga** [comment]
oh, it worked like a charm (after I stopped doing stupid mistakes) thanks :)
