### ISSUE TITLE
Suggest parameter values

### ISSUE THREAD

**Issue by ankane** [ankane/pghero#17]
https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server and other guides.

If you have good resources, please share!

**Comment by fernandoluizao** [comment]
https://github.com/le0pard/pgtune

**Comment by zorab47** [comment]
Is the idea to integrate the functionality from [pgtune.coffee](https://github.com/le0pard/pgtune/blob/master/source/javascripts/pgtune.coffee)? What is the best method of detecting available memory?

**Comment by fernandoluizao** [comment]
@zorab47 maybe in `/proc/meminfo`? But I think is Linux only... I don't know a portable way to detect this...

**Comment by ankane** [comment]
Closing out feature ideas to clean up GitHub Issues. I think an external link to PgTune is good enough for now.
