### ISSUE TITLE
[Feature Request] Autovacuum/Vacuum progress feedback would be totally cool!

### ISSUE THREAD

**Issue by fake-name** [ankane/pghero#170]
So PostgreSQL >= 9.6 has a [really, really neat new facility](https://www.postgresql.org/docs/9.6/static/progress-reporting.html) for getting information about the progress and state of any running autovacuum/vacuum operations.

It'd be really cool if pghero could expose this information in a pleasant way (it should be easy to generate a progress bar even, some of the states have a progress output - heap_blks_total / heap_blks_scanned, heap_blks_vacuumed).

Here's what the relevant table looks like:

```
^Cpostgres=# select * from pg_stat_progress_vacuum;
 pid  | datid |  datname   |  relid   |     phase      | heap_blks_total | heap_blks_scanned | heap_blks_vacuumed | index_vacuum_count | max_dead_tuples | num_dead_tuples
------+-------+------------+----------+----------------+-----------------+-------------------+--------------------+--------------------+-----------------+-----------------
 4100 | 16412 | webarchive | 38269410 | vacuuming heap |         8339740 |           8339740 |            2818910 |                  1 |       178956970 |        23023484
(1 row)

```

**Comment by ankane** [comment]
Hey @fake-name, totally agree! Will add this when I have some time.

**Comment by fake-name** [comment]
I can provide some examples of what the query results looks like as it progresses, if that'd help.

**Comment by ankane** [comment]
Sure, that'd be great. I'm just starting to regularly work with 9.6, so should have a chance to battle test this in the coming weeks.

**Comment by fake-name** [comment]
Roughly, it seems like there's several steps that are slow. `initializing` is fast, `scanning heap` is slow, and you get progress feedback (`heap_blks_scanned` increments in this stage).
Then, the DB sits on `vacuuming indexes` for a long time. From what I can tell, I think this basically entails rebuilding the indexes, either partially or completely. On some of my large tables (100M+ rows), it can take a *long* time. After that, it sometimes spends visible amounts of time in the `vacuuming heap` state (though for smaller tables, you can miss it entirely). This also has progress feedback (`heap_blks_vacuumed`).

The rest of the steps (`cleaning up indexes`, `truncating heap`, `performing final cleanup`) are all pretty fast, and don't really provide feedback.

I'm not too sure what `index_vacuum_count` is supposed to indicate. I think it's mostly when you run out of `maintenance_work_mem` in the `vacuuming indexes` step, and it has to chunk the index vacuum up.

```


                                                               Mon 20 Nov 2017 07:55:47 PM PST (every 2s)

 pid  | datid | datname  |  relid   |     phase     | heap_blks_total | heap_blks_scanned | heap_blks_vacuumed | index_vacuum_count | max_dead_tuples | num_dead_tuples
------+-------+----------+----------+---------------+-----------------+-------------------+--------------------+--------------------+-----------------+-----------------
 6832 | 16406 | mangacms | 38266332 | scanning heap |           29019 |              6460 |                  0 |                  0 |         8444529 |            6799
(1 row)

                                                               Mon 20 Nov 2017 07:55:49 PM PST (every 2s)

 pid  | datid | datname  |  relid   |     phase     | heap_blks_total | heap_blks_scanned | heap_blks_vacuumed | index_vacuum_count | max_dead_tuples | num_dead_tuples
------+-------+----------+----------+---------------+-----------------+-------------------+--------------------+--------------------+-----------------+-----------------
 6832 | 16406 | mangacms | 38266332 | scanning heap |           29019 |              9933 |                  0 |                  0 |         8444529 |           14765
(1 row)

                                                               
                                                                 Mon 20 Nov 2017 07:55:53 PM PST (every 2s)

 pid  | datid | datname  |  relid   |       phase       | heap_blks_total | heap_blks_scanned | heap_blks_vacuumed | index_vacuum_count | max_dead_tuples | num_dead_tuples
------+-------+----------+----------+-------------------+-----------------+-------------------+--------------------+--------------------+-----------------+-----------------
 6832 | 16406 | mangacms | 38266332 | vacuuming indexes |           29019 |             29019 |                  0 |                  0 |         8444529 |           15565
(1 row)

                                                                 Mon 20 Nov 2017 07:55:55 PM PST (every 2s)

 pid  | datid | datname  |  relid   |       phase       | heap_blks_total | heap_blks_scanned | heap_blks_vacuumed | index_vacuum_count | max_dead_tuples | num_dead_tuples
------+-------+----------+----------+-------------------+-----------------+-------------------+--------------------+--------------------+-----------------+-----------------
 6832 | 16406 | mangacms | 38266332 | vacuuming indexes |           29019 |             29019 |                  0 |                  0 |         8444529 |           15565
(1 row)

                                                              
                                                                 Mon 20 Nov 2017 07:56:03 PM PST (every 2s)

 pid  | datid | datname  |  relid   |       phase       | heap_blks_total | heap_blks_scanned | heap_blks_vacuumed | index_vacuum_count | max_dead_tuples | num_dead_tuples
------+-------+----------+----------+-------------------+-----------------+-------------------+--------------------+--------------------+-----------------+-----------------
 6832 | 16406 | mangacms | 38266332 | vacuuming indexes |           29019 |             29019 |                  0 |                  0 |         8444529 |           15565
(1 row)

```

**Comment by ankane** [comment]
Added the phase to the "Live Queries" page on master. Will continue to improve with % progress a bit later.

**Comment by fake-name** [comment]
Fancy!

If (and it's a big if) `index_vacuum_count` does indeed indicate that it's having to do multiple passes when cleaning the indexes due to insufficient `maintenance_work_mem`, that might be a reasonable thing to have one of the suggestions on the root page about.

**Comment by ankane** [comment]
Since there's been an initial version out for a while, going to close. For future readers, feel free to submit a PR if you have improvements. Thanks again for the idea @fake-name!
