### ISSUE TITLE
Debian Stretch (9.0) / Jessie (10.0) build

### ISSUE THREAD

**Issue by themusicgod1** [ankane/pghero#171]
While it's good that you have built packages for debian, the release of debian that this was built for is now "oldstable", that is to say, obsoleted.  It might be time to consider building for a slightly newer debian system (this might make it easier to build on slightly newer Ubuntu systems as well)

**Comment by ankane** [comment]
Hey @themusicgod1, thanks for the suggestion 👍  PgHero uses Packager.io, which doesn't support Debian 9 or 10 at the moment. https://packager.io/documentation/distributions/

**Comment by ankane** [comment]
Closing for now, but should be super easy to add when Packager supports it.

**Comment by hvisage** [comment]
O_o 
@ankane seems packager.io is quite "dated" in their support for newer OSes ;(
