### ISSUE TITLE
Error: "relation "<schema>.audit_id_seq" does not exist", because Sequence is in another schema

### ISSUE THREAD

**Issue by ephillipe** [ankane/pghero#172]
```
28/11/2017 11:09:47ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "configuracao.audit_id_seq" does not exist
28/11/2017 11:09:47LINE 1: ..._conexao_id_seq" UNION ALL SELECT last_value FROM "configura...
28/11/2017 11:09:47                                                             ^
```

"configuracao.audit_id_seq" really does not exist. 

I suggest using 
`SELECT currval('<sequence>');`

I have problem because PgMemento creates a **audit_id_seq**  into pgmemento schema. If this code [https://github.com/ankane/pghero/commit/54e35f0073ab6b55f131703368e3fdedf6c47034](url) use _currval_ function, I believe this problem is solved .

**Comment by ankane** [comment]
Hey @ephillipe, thanks for reporting. Are you on the latest version (2.0.8)? If not, try that. If so, can you paste the default value of the column that uses `audit_id_seq`, as well as the schema the table is in and the schema the sequence is in?

We can't use `currval` since it's local to the current session and requires you to have used `nextval` previously. From the Postgres docs for `currval`:

> Return the value most recently obtained by nextval for this sequence in the current session. (An error is reported if nextval has never been called for this sequence in this session.) Because this is returning a session-local value, it gives a predictable answer whether or not other sessions have executed nextval since the current session did.

**Comment by ephillipe** [comment]
Hi @ankane ,
I'm need revert my version to v2.0.2 to work. I'm was using the latest version when I get the exception.

One of columns with the problematic default value.
```
ALTER TABLE public.account_account
    ALTER COLUMN audit_id SET DEFAULT nextval('audit_id_seq'::regclass);
```
Note the table is in **public** schema. But **audit_id_seq** is in **pgmemento** schema.

**Comment by ankane** [comment]
Thanks @ephillipe. Unfortunately, this is a known limitation to sequence reporting right now. The generic situation is table and sequence are in different schemas AND no schema is specified in `nextval` in default column.

From what I understand, if you have two sequences with the same name in different schemas and don't specify a schema in the default value, it will use the first one in your search path. Change the search path and it'll change the sequence that's used. For this reason, there's not a sure way to know which one is referenced.

For the likely more common case where sequence names are unique across schema, I'm thinking we can fetch the schema for sequences that don't have a schema specified and use that. If more than one is returned, we can use the search path, exclude it, or throw an error.

**Comment by ephillipe** [comment]
Thanks @ankane for feedback.
If I had a way to disable this code, I could use the latest version.

**Comment by ankane** [comment]
Hey @ephillipe, just pushed what I described above to master. If you're on Rails, please give it a shot.

**Comment by ephillipe** [comment]
Hi @ankane , I'm not on Rails. I use Docker version. 
I will wait for a release and test then. Very thanks for fast response.

**Comment by ankane** [comment]
Sounds good, thanks for helping debug 💯
