### ISSUE TITLE
[general help] Need help with authentication 

### ISSUE THREAD

**Issue by rromanchuk** [ankane/pghero#173]
Any ideas why http auth wouldn't be triggered? Confirmed `ENV["PGHERO_PASSWORD"]`  and _username is present and not nil.

**Comment by ankane** [comment]
Hey @rromanchuk, make sure you don't have a typo and try restarting the PgHero server.

**Comment by ankane** [comment]
Closing due to no response.

**Comment by rromanchuk** [comment]
Nothing seems odd with this implementation https://github.com/ankane/pghero/blob/dbe31cae95ec8b428abc37303205ef689ab8a5b3/app/controllers/pg_hero/home_controller.rb#L7

I guess i need to do more sanity checks

**Comment by rromanchuk** [comment]
@ankane ignore me, sanity check confirmed working. Incognito, works fine lol.  My http auth credentials must be cacheddddddd hard in my browser.
