### ISSUE TITLE
Adjust number of puma workers

### ISSUE THREAD

**Issue by turgs** [ankane/pghero#175]
Is there a way I can tell pghero to use fewer puma workers?

**Comment by ankane** [comment]
Hey @turgs, you can use the `PUMA_WORKERS` environment variable to control the number of workers (default is 3).

**Comment by turgs** [comment]
Thanks. In the meantime, I'd done the following too which seemed to work:

```
sudo sh -c "echo 'workers 1' > /opt/pghero/config/puma.rb"
sudo sh -c "chown pghero:pghero /opt/pghero/config/puma.rb"
```
