### ISSUE TITLE
Error when running capture_query_stats or capture_space_stats commands using Docker

### ISSUE THREAD

**Issue by Zurbotron** [ankane/pghero#177]
If we run:

`docker run -e DATABASE_URL=postgres://$user:$pass@hostname:5432/dbname -p 8080:8080 ankane/pghero `

And then afterwards run either of the following commands:
```

docker run -ti -e DATABASE_URL=postgres://$user:$pass@hostname:5432/dbname ankane/pghero bin/rake pghero:capture_query_stats

docker run -ti -e DATABASE_URL=postgres://$user:$pass@hostname:5432/dbname ankane/pghero bin/rake pghero:capture_space_stats
```

We receive this error:

> docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused “exec: \“bin/rake\“: stat bin/rake: no such file or directory”.

So we can still launch pghero and view stats, but we cannot enable this additional functionality. This used to work fine, but noticed the problem a few days ago when relaunching.

**Comment by ankane** [comment]
Hey @Zurbotron, not sure why broke, but will investigate. In the meantime, you should be able to run `bundle exec rake` instead of `bin/rake`.

**Comment by ankane** [comment]
Hey @Zurbotron, `bin/rake` is working fine for me with the latest version.

**Comment by Zurbotron** [comment]
Unfortunately still getting an error with bundle exec rake when trying to collect stats (no problems spinning up pghero itself).

`[root@ip-10-205-202-221 qgy198]# docker run -ti -e DATABASE_URL=postgres://user:pass@host:5432/dbname dockerimage bundle exec rake pghero:capture_space_stats
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/local/bundle/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
`

**Comment by Zurbotron** [comment]
that said, I think we were using v2.0.8 so I'll try rebuilding image from latest version and see if that solves things. thanks.

**Comment by Zurbotron** [comment]
I'm unable to rebuild the image at the moment, but just to clarify, should the sequence of commands look like this:

`docker run -d -e "PGHERO_USERNAME=$PGHERO_USERNAME" -e "PGHERO_PASSWORD=$PGHERO_PASSWORD" -e "DATABASE_URL=postgres://$DB_USERNAME:$DB_PASSWORD@$HOST:5432/$DB_NAME" -p 80:8080 $DOCKER_IMAGE

docker run -ti -e "DATABASE_URL=postgres://$DB_USERNAME:$DB_PASSWORD@$HOST:5432/$DB_NAME" $DOCKER_IMAGE bin/rake pghero:capture_query_stats

docker run -ti -e "DATABASE_URL=postgres://$DB_USERNAME:$DB_PASSWORD@$HOST:5432/$DB_NAME" $DOCKER_IMAGE bin/rake pghero:capture_space_stats`

The first command runs just fine to spin up pghero, and we're only running into the error when trying to capture stats.

**Comment by ankane** [comment]
Hey @Zurbotron, haven't been able to repro this, so going to close. If you have more info or specific steps to repro, let me know.
