### ISSUE TITLE
After upgrading pghero from 1.1.3 to 2.1.0 giving me error

### ISSUE THREAD

**Issue by aniketstiwari** [ankane/pghero#178]
After upgrading pghero from 1.1.3 to 2.1.0 giving me error **Same sequence name in multiple schemas:**

PgHero::Error (Same sequence name in multiple schemas: tokens_id_seq):
  app/middleware/skip_trackable.rb:8:in `call'

  Rendered /home/aniketshivamtiwari/.rvm/gems/ruby-2.3.1@portal/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (6.8ms)
  Rendered /home/aniketshivamtiwari/.rvm/gems/ruby-2.3.1@portal/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (4.1ms)
  Rendered /home/aniketshivamtiwari/.rvm/gems/ruby-2.3.1@portal/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.3ms)
  Rendered /home/aniketshivamtiwari/.rvm/gems/ruby-2.3.1@portal/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (26.7ms)
  Rendered /home/aniketshivamtiwari/.rvm/gems/ruby-2.3.1@portal/gems/web-console-2.1.3/lib/web_console/templates/_markup.html.erb (0.7ms)
  Rendered /home/aniketshivamtiwari/.rvm/gems/ruby-2.3.1@portal/gems/web-console-2.1.3/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.7ms)
  Rendered /home/aniketshivamtiwari/.rvm/gems/ruby-2.3.1@portal/gems/web-console-2.1.3/lib/web_console/templates/_inner_console_markup.html.erb 

Rails - 4.2.7.1
Ruby - 2.3.1
pg -  0.17.1
postgresql -  9.6.6

**Comment by ankane** [comment]
Hey @aniketstiwari, thanks for reporting 👍  I've updated the project to handle this more gracefully on master.

**Comment by aniketstiwari** [comment]
hey  **@ankane**, thanks it is working fine now

**Comment by woqer** [comment]
Any idea when this fix will be released? I did a recently build from the docker image and I get this error

**Comment by shane-axiom** [comment]
Same! Interested to try pghero out but waiting for this to be released. Thanks!

**Comment by dpierce-aledade** [comment]
Also waiting for this to be released.  It is preventing me from using PGHero
