### ISSUE TITLE
[Feature Request] Delineate between long running queries, and idle queries left open?

### ISSUE THREAD

**Issue by fake-name** [ankane/pghero#179]
This is a random idea, but have you considered delineating between queries that are actually long *running*, and queries that are just left open and idle?

I have a project that has both some very expensive (500+ second) queries, and a web-interface that occasionally farts and leaves a idle transaction open indefinitely. Both of these show up in the overview as "*nnn* long running query(s)".

It seems to me it'd be nice to list queries that are actually active and queries that are idle in transaction separately. Yes, they're both potential issue indicators, but they're very different issue types.

**Comment by ankane** [comment]
Hey @fake-name, this has popped into my head as well :) For simplicity, I think it's good to keep them together in the web interface under long running queries. The state of each query is shown in the table, so it's easy to tell if you know what you're looking for (`idle in transactions` vs `active`), but it'd be nice to have something that anyone can understand.

**Comment by fake-name** [comment]
I don't necessarily thing it warrants a separate page or anything, but rather maybe just sort the running queries, and have a \<hr\> between the two groups, or something.

**Comment by fake-name** [comment]
It'd also be nice to be able to acknowledge the `We recommend setting a statement timeout` thing. I know there are some long running queries, and in some cases, I can't do anything about it. I don't need that to be pointed out again.

**Comment by ankane** [comment]
Thanks Conner. I don't see a strong reason to change how it is right now. I appreciate the suggestions.

**Comment by fake-name** [comment]
It's not a big deal. Thanks for considering it, at least.

Realistically, I should probably just put more effort into fixing dangling queries.
