### ISSUE TITLE
Can't view System CPU, Load, or Connections stats

### ISSUE THREAD

**Issue by lettergram** [ankane/pghero#180]
I can't seem to get any data to visualize on the pghero system charts.

![screenshot from 2017-12-31 12-53-19](https://user-images.githubusercontent.com/1498748/34463688-aa404c86-ee29-11e7-89d1-9419610d5b1c.png)

I followed all the instructions outlined in the guide for rails (which I am using):

https://github.com/ankane/pghero/blob/master/guides/Rails.md

I have created a user with the definted IAM policy:

![screenshot from 2017-12-31 12-55-22](https://user-images.githubusercontent.com/1498748/34463697-f11ed6f4-ee29-11e7-9d83-30b726325223.png)

Then, provided the access keys and the database identifier to pghero. 

There doesn't seem to be an issue with any of those components, which makes me believe there is one with pghero itself.

Is there a particular place I should look at fixing to make this work? Or some common error?

**Comment by ankane** [comment]
Hey @lettergram, I'd double check that your db instance identifier is correct.

**Comment by lettergram** [comment]
I've double checked the identifier does appear to be correct. Is there something else I should look into? I don't see any errors on the javascript side either...

**Comment by ankane** [comment]
@lettergram You can try forking the gem and debugging, but I've personally only seen this behavior when the AWS configuration is incorrect.

**Comment by lettergram** [comment]
Sounds good... I just went through and double checked all the AWS components all correct. Even appears that the IAM role is being used, just no charts being displayed...

![screenshot from 2018-01-08 17-01-26](https://user-images.githubusercontent.com/1498748/34696806-c006e77e-f495-11e7-94a4-d769ad7bae72.png)

I'll take some time to review this when I have a chance - might be a while though, so you can probably close the issue. Thanks, perhaps I missed something obvious

**Comment by ankane** [comment]
Will do, feel free to update if you find anything.
