### ISSUE TITLE
Debain 9 (stretch) on packager.io 

### ISSUE THREAD

**Issue by hvisage** [ankane/pghero#182]
I just received this email about packager.io supporting Debian 9:

> On 21 Jan. 2018, at 10:09 , Cyril Rohr <support@packager.io> wrote:
> 
> Hello,
> 
> It is already supported. Did you try building with debian-9 in your targets ?
> 
> Cyril

**Comment by ankane** [comment]
Thanks @hvisage, Debian 9 added.
