### ISSUE TITLE
Wrong graph drawn when there are not many points

### ISSUE THREAD

**Issue by mikelolasagasti** [ankane/pghero#187]
When there are not enough data points, the drawn line can do loops and other strange figures.

![irudia](https://user-images.githubusercontent.com/773148/36197935-90f99100-1175-11e8-9c51-716d41e1eebf.png)

**Comment by ankane** [comment]
Hey @mikelolasagasti, thanks for reporting 👍 I've noticed this as well. Not sure there's much we can do besides remove the splines (which I'd prefer not to do). Since this is pretty minor, going to mark as `wontfix`.
