### ISSUE TITLE
Getting undefined method type_cast for nil when starting the dashboard

### ISSUE THREAD

**Issue by EdmundLeex** [ankane/pghero#189]
Turns out `PgHero::Methods::Replication#replica?` running `SELECT pg_is_in_recovery()`. And in the result, column type is nil.

```
=> #<ActiveRecord::Result:0x508360bd @column_types={}, @columns=["pg_is_in_recovery"], @hash_rows=nil, @rows=[["f"]]>
```

I am using pg 10.0. And Rails 4.2.4. Haven't tried other versions yet.

**Comment by ankane** [comment]
Hey @EdmundLeex, I'd try upgrading to the latest patch version of Rails 4.2.

**Comment by EdmundLeex** [comment]
@ankane This may well be a rails version issue. But I tried version 4.2.4~4.2.8. They all have the same problem. And there are some other breaking changes that stopped me from going further up in rails 4.2.x. Any work around?

**Comment by ankane** [comment]
This error doesn't occur on new Rails apps, so think it's related to your setup.
