### ISSUE TITLE
Metrics over time

### ISSUE THREAD

**Issue by ankane** [ankane/pghero#19]
Chart query stats and other important metrics over time

**Comment by sj26** [comment]
Index usage over time would be amazing. I frequently modify and optimise queries, or create alternate indexes, and manually keep track of index usage stats to see if I'm effective. Having a historical set of index usage stats with a nice chart would make this much easier.

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues

**Comment by scytherswings** [comment]
Awww, I also liked the idea of this feature but my guess is that this would best be solved by a PR. I'm glad this project still has @ankane 's attention though. Thanks for all your hard work!
