### ISSUE TITLE
Explain -> ...bind message supplies 0 parameters, but prepared statement...

### ISSUE THREAD

**Issue by kwerle** [ankane/pghero#191]
pghero running in docker container (osx host) against AWS RDS Postgres 9.4

* Live queries
* Explain

[no explanation]

PG::ProtocolViolation: ERROR: bind message supplies 0 parameters, but prepared statement "" requires 2 : EXPLAIN UPDATE "my_table" SET "column" = 'value', "column" = 'value', "column" = 'value' WHERE ("table"."column" IS NULL OR "table"."column" = $1) AND "table"."column" = $2

**Comment by ankane** [comment]
Hey @kwerle, you can’t explain queries with bind parameters.

**Comment by kwerle** [comment]
Bummer.  It'd be nice if it said that- if it can tell.
