### ISSUE TITLE
docker The database user does not have permission to enable query stats 

### ISSUE THREAD

**Issue by changchichung** [ankane/pghero#193]
I build a pghero instance using docker , and follow the https://github.com/ankane/pghero/blob/master/guides/Query-Stats.md to enable query stat .

```
# enable query stats
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = all
pg_stat_statements.max = 10000
track_activity_query_size = 2048
2018-03-28 10:40:37 [postgres@srv022 ~]$ 
```
and create extension in psql console at the DB Server
```
postgres=# CREATE extension pg_stat_statements;
ERROR:  extension "pg_stat_statements" already exists
postgres=# 
```
but still the same messages "The database user does not have permission to enable query stats "

any suggestions to fix ?

**Comment by ankane** [comment]
Hey @changchichung, please check out the Contributing Guide.
