### ISSUE TITLE
[Idea] MySQL Support?

### ISSUE THREAD

**Issue by madejejej** [ankane/pghero#194]
Hey,

Thanks for creating this awesome Ruby gem! 

I know that the name `pghero` speaks for itself, but I'm wondering how hard would it be to add support for MySQL? I think it'd bring massive value to the community. 

I'm happy to volunteer but I'd like to hear your opinion first. And I'm not a DB expert :-).

**Comment by ankane** [comment]
Hey @madejejej, I don't have much experience managing MySQL, but I'd encourage you to start a similar project for it. I don't think you need to be an expert to do it (I'm definitely not a Postgres expert) - just put something out there and iterate on it.
