### ISSUE TITLE
Please package for new Ubuntu release 18.04 LTS(bionic)

### ISSUE THREAD

**Issue by pikkmees** [ankane/pghero#208]
Hi, Can anyone compile installation package for new Ubuntu 18.04 version, as It's were for earler one:
https://github.com/ankane/pghero/blob/master/guides/Linux.md
Can I help in somehow?

**Comment by ankane** [comment]
Hey @pikkmees, it doesn't look like pkgr.io supports Ubuntu 18.04 yet, but it should be trivial once it does: https://packager.io/gh/pghero/pghero/builds/118/logs/ubuntu-18.04

**Comment by aehlke** [comment]
Anyone have a workaround?

**Comment by ankane** [comment]
Looks like support was added in the past two months. Updated Linux instructions.
