### ISSUE TITLE
Service missing in Ubuntu 14 package

### ISSUE THREAD

**Issue by ralovely** [ankane/pghero#211]
Hi,

On a vanilla Ubuntu 14.04 EC2 instance,
after running the install commands from the Linux guide,
pghero itself is there and fine, but the service file isn't:

```
ubuntu:~$ sudo service pghero status
pghero: unrecognized service
```

In the package, I can find a `/opt/pghero/vendor/pkgr/scaling/upstart/pghero`
`initctl list | grep pghero` returns empty.

Could you point the best way to enable the service ?

Thank you.

**Comment by ankane** [comment]
Hey @ralovely, I'd double check you installed the right package for that version of Ubuntu.
