### ISSUE TITLE
Remove sprockets based javascript dependency (Rails)

### ISSUE THREAD

**Issue by tconst** [ankane/pghero#215]
The javascript in PgHero utilizes sprockets for compilation, which presents an issue for Rails apps that do not use sprockets.  With Webpacker support in Rails now it is not a requirement to have sprockets anymore.

**Comment by ankane** [comment]
Hey @tconst, thanks for the suggestion 👍  Since PgHero needs asset compilation and Sprockets is still the default, I don't think this will happen.

**Comment by n-rodriguez** [comment]
> Since PgHero needs asset compilation and Sprockets is still the default, I don't think this will happen.

It won't last forever : https://github.com/rails/rails/pull/33079

**Comment by n-rodriguez** [comment]
Thanks for the very good job btw :+1:

**Comment by n-rodriguez** [comment]
> are you guys using both still?

yes

**Comment by filipkis** [comment]
As Rails 6 is now out and webpacker is the default, any chance of reconsidering this. Here is a good example of how another gem switched to supporting webpacker as well. Maybe that can be an inspiration: https://github.com/activeadmin/activeadmin/pull/5855
