### ISSUE TITLE
default_url_options for multiple DB redirect

### ISSUE THREAD

**Issue by ralovely** [ankane/pghero#216]
Hi,

In a multiple DB setup, the gem will [redirect to the first database](https://github.com/ankane/pghero/blob/master/app/controllers/pg_hero/home_controller.rb#L327): 
In a Linux install, the redirect url will look like `http://localhost:3001/primary`.

Is there a way to control the redirection url ?
Or maybe override the `default_url_options` (defined [in the controller itself](https://github.com/ankane/pghero/blob/master/app/controllers/pg_hero/home_controller.rb#L333)) ?

Thank you.

**Comment by ralovely** [comment]
Using the proxy to do a rewrite will work as well.
Closing the issue. Thanks.

**Comment by scalp42** [comment]
@ralovely could you share an example?

**Comment by bielids** [comment]
I'm still running into this problem. How can I get around that using an NGINX proxy?

**Comment by ankane** [comment]
Check out #409.
