### ISSUE TITLE
Pg hero not able to install in centos

### ISSUE THREAD

**Issue by michaelkingston6785** [ankane/pghero#217]
Hi,

when i am installing pghero in centos . I am getting below exception. Can you clarify on the roor cause the exception. 
aws:
$ sudo pghero scale web=1
cp: cannot create regular file â/etc/systemd/systemâ: No such file or directory

centos 6.9.
$ pghero scale web=1
/usr/bin/pghero: line 320: systemctl: command not found
/usr/bin/pghero: line 321: systemctl: command not found

Before creating an issue, please check out the Contributing Guide:

https://github.com/ankane/pghero/blob/master/CONTRIBUTING.md

Thanks!

**Comment by ankane** [comment]
Hey @michaelkingston6785, CentOS 6 isn't officially supported anymore by PgHero. If you followed the instructions in the readme, you most likely installed the version for CentOS 7. You can get the latest build for 6 here:

```
sudo wget -O /etc/yum.repos.d/pghero.repo \
  https://dl.packager.io/srv/pghero/pghero/master/installer/el/6.repo
sudo yum install pghero
```
