### ISSUE TITLE
Connections from other VMs in Heroku hobby db?

### ISSUE THREAD

**Issue by adzap** [ankane/pghero#22]
I am using Heroku with Ruby 2.1.5 and looking at the below snapshot of the connections you can see that these can't be my connections.

![image](https://cloud.githubusercontent.com/assets/6318/7509996/e6b15a34-f4da-11e4-8b27-8e14af7a35fb.png)

i.e. there is code running in Ruby 1.9 and 2.2 and also sidekiq which I am not using.

Should I expect to see connections from other apps not belonging to me when using this gem on heroku and the hobby ($9/mth) database?

**Comment by ankane** [comment]
@adzap not sure, probably best to check with Heroku

**Comment by adzap** [comment]
Yes will do. Thought you might have come across it.

**Comment by ankane** [comment]
Cool, keep us posted.

**Comment by adzap** [comment]
From Heroku

> Yep the Hobby tier Postgres servers are multi-tenant, with database-level isolation (each Hobby add-on is a different user+database on that Postgres instance). Each user has a 20 connection quota and there might be many connections on that server depending on the other tenants.

So with this and digging into the gem to see what query is run to show the connections, I can see that the combination of the shared PG instance and the connection query, which does not limit to the current database, will show all connections for the whole instance including other apps and customers.

Is it intentional to show all connections to the pg instance rather than limit it to the current database?

**Comment by ankane** [comment]
Since Postgres starts to perform poorly with too many connections regardless of database, I think we have to keep it at a PG instance level.  However, I can see this being confusing for users of multi-tenant databases.  It's really just noise in that situation.

**Comment by adzap** [comment]
I understand it is still useful. However it is noise up to a point, but it can be confusing. If any of those connections were plausibly from my app (e.g other puma workers or scripts in the in right Ruby version) then I couldn’t differentiate. 

Perhaps adding the database next to the connection, or grouping by database, is one possible way it could help. Even for those who are not multi-tenant but are looking at the instance as a whole it might be useful to know where the connections are concentrated.

**Comment by ts-silvio** [comment]
Glad I found that issue. Was also really confused by this.

**Comment by ankane** [comment]
Just following up: Connections now have the database name next to them, but planning to also divide it into "your DB" vs "other DBs" to make it more clear.

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues
