### ISSUE TITLE
Sugestion: Split pghero_query_stats in two tables

### ISSUE THREAD

**Issue by fernandoluizao** [ankane/pghero#222]
I'm thinking if it would be possible to remove the **query** column from **pghero_query_stats** and create a new table with the following structure:
```
query_hash: bigint
query: text
```
This way the size of pghero_query_stats will be dramatically reduced, as the queries repeats over and over.

Toughts?

**Comment by ankane** [comment]
Hey @fernandoluizao, thanks for the suggestion 👍 Currently, the query text of each capture is used on the query details page to breakdown the [origin of queries](https://github.com/ankane/shorts/blob/master/The-Origin-of-SQL-Queries.md), so this would lose that ability, and I don't think it's worth the complexity to support two patterns.

If the table is growing too big, I'd recommend truncating it on a regular interval, or partitioning.

**Comment by fernandoluizao** [comment]
I hadn't thought of that, because I don't use comments in the queries ... I agree that it would increase complexity.

Thanks for your attention, I'll close this.
