### ISSUE TITLE
Time units are hard to interpret for extremely long execution times.

### ISSUE THREAD

**Issue by fake-name** [ankane/pghero#223]
I have some large tables (2+ TB) that take an extremely long time to `VACUUM`.

Currently, PgHero reports the vacuum query has been executing for "73,371,120 ms".

This is kind of hard to understand. Looking at it, I know it's a \~\~long\~\~ time, but I at least, cannot translate that to more sensible units.

It'd be really nice if the duration output would print the duration in more readable units. 

Perhaps:

 - If the execution is over 30 seconds, report it in fractional seconds, rather then seconds
    (e.g. 45.117 seconds, rather then 45,117 ms)
 - If the execution is over 120 seconds, report minutes:seconds
 - Past an hour, include that,
 - Etc...

I do regularly have `VACUUM` operations that can take up to a week.

**Comment by ankane** [comment]
Thanks for this suggestion as well. There are now three time formats:

- `1.1 s` for under 1 min
- `12:34:56` for under 1 day
- `5d 12:34:56` for over 1 day
