### ISSUE TITLE
[Idea] single screen for all databases

### ISSUE THREAD

**Issue by netanel246** [ankane/pghero#224]
A screen that aggregates all databases so you can immediately view the status of all your databases instead of having to check each database by itself

**Comment by NhoNho** [comment]
Would be great indeed. It could look like a build radiator:

https://www.google.com/search?q=build+radiator&tbm=isch

**Comment by ankane** [comment]
Hey @netanel246, I like this idea, but with the current design, I think it'll timeout once you have a few databases. One way around this would be to check the state in the background and cache it for the dashboard, but I think this likely adds too much complexity to the project.
