### ISSUE TITLE
[Idea] Capturing Dead tuple & Live tuple ratio in maintenance tab

### ISSUE THREAD

**Issue by garry-9590** [ankane/pghero#227]
Since, the triggering condition for auto vacuum is either max freeze age (which is already considered while showing the health of auto vacuuming) or dead tuples to live tuples ratio, it will be useful to show this ratio in the maintenance tab along with the timestamp of last autovacuum run.  These statistics can also be validated against the following equation to identify the auto vacuuming threshold and if autovacuum does not trigger after this breach, it is a cause of concern.

`autovacuuming threshold = autovacuum_vacuum_threshold + (autovacuum_vacuum_scale_factor * estimated number of rows in the table)`

**Comment by maknahar** [comment]
Would it make more sense to put it in space tab right beside size each relation?

**Comment by ankane** [comment]
Hey @garry-9590, thanks for the suggestion, and sorry for the long delay. There's a PR that may do what you're thinking in #292, but in the interest of keeping the product simple, I'm hesitant to add. A warning will show up on the main page if autovacuum falls too far behind. Are there other situations where this can cause issues and/or is useful to have?

**Comment by ankane** [comment]
With the latest release, you can now add `?dead_rows=t` to the url on the maintenance page to see this ratio.
