### ISSUE TITLE
Last version with 9.1 support?

### ISSUE THREAD

**Issue by leoc** [ankane/pghero#231]
Hi, thanks for this great software.

I have to work with an arcane postgres 9.1 system and did not find anything about version compatibility in the CHANGELOG.

Could someone recall from memory, whether there has been a version compatible with PG 9.1?

Thank you so much!

**Comment by ankane** [comment]
Hey @leoc, my memory may be off, but I think PgHero has always been 9.2+.

**Comment by leoc** [comment]
I suspected that. :-)

Thank you! Loved your quick response and your smiling avatar! Have a wonderful day!
