### ISSUE TITLE
Docker images with different sizes?

### ISSUE THREAD

**Issue by marceloboeira** [ankane/pghero#243]
First of all, thanks for the amazing project, it's helping out a lot!

<img width="910" alt="screenshot 2018-11-28 at 14 36 10" src="https://user-images.githubusercontent.com/1898225/49155358-09454000-f31b-11e8-9126-e1f4cd45d987.png">

For consistency, are the latest and v2.2.0 the same? their size and publication date are different...

Also, how's the docker image currently built? or where is the Dockerfile (couldn't find it on the repo).

It it this one? -> https://github.com/ankane/pghero_solo/blob/master/Dockerfile

**Comment by ankane** [comment]
Yeah, that's the repo. Latest will sometimes point to master.
