### ISSUE TITLE
Timeouts on pg_get_indexdef

### ISSUE THREAD

**Issue by mklaber** [ankane/pghero#246]
We've had pghero stability issues from the get-go. Finally had time to dig in a bit more and found that [this query](https://github.com/ankane/pghero/blob/master/lib/pghero/methods/indexes.rb#L128-L155) is routinely getting blocked. In particular, it's the call to `pg_get_indexdef` that gets blocked. (If I remove `pg_get_indexdef` from the select statement, the query returns quickly.)

I haven't been able to find much documentation about `pg_get_indexdef` on the interwebs. I can't imagine pghero would use a function that's susceptible to locks under normal conditions so I suspect it has something to do with how the `pghero` user gets set up, perhaps?

(The instability this causes presents itself as `ActiveRecord::ConnectionTimeoutError (could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use):` which I think happens because there are a bunch of these `pg_get_indexdef` queries in process.)

We're running PostgresSQL 9.6.9 on Amazon RDS and pghero version 2.2.

**Comment by ankane** [comment]
Hey @mklaber, how many indexes do you have?

**Comment by mklaber** [comment]
It looks like it's getting blocked by an `INSERT` that has a `RowExclusiveLock` and `AccessExclusiveLock`... seems like it shouldn't be doing anything that would get locked out?

**Comment by ankane** [comment]
Haven't tested it, but It's likely the ACCESS EXCLUSIVE lock is blocking it. From the Postgres docs:

> This mode guarantees that the holder is the only transaction accessing the table in any way.

**Comment by mklaber** [comment]
That seems to have been the case. (The locks were coming from some `DROP` and `CREATE` index statements before and after the `INSERT`.)

I guess the question is whether there should be clearer error handling in the app? (Having said that, I'm fairly certain I have a gateway timeout setting lower than the app's so haven't actually seen how it responds to errors.)

I'll close out this issue.
