### ISSUE TITLE
connect_timeout=2 too aggressive?

### ISSUE THREAD

**Issue by PaulMakepeace** [ankane/pghero#250]
I have a database on the other end of a LAN SSH port forward and for whatever reason the connection setup is more than two seconds. Adding `?connect_timeout=10` to the `DATABASE_URL` solved the timeout. ([source](https://github.com/ankane/pghero/blob/master/lib/pghero/database.rb#L78))

Is there a reason for such a short timeout? If not, perhaps consider leaving it unset?

Original error:

```
Processing by PgHero::HomeController#index as */*
Completed 500 Internal Server Error in 2034ms

PG::ConnectionBad (timeout expired
):
```

**Comment by ankane** [comment]
Hey @PaulMakepeace, the main motivation for adding a timeout was to prevent indefinite hanging if a connection can't be established. Ideally, it fails as soon as there's a low likelihood of a connection being established. There isn't anything specially about the current value, but I think for 99% of apps, 2 seconds is more than enough time to establish a connection. In other cases, I think the solution you used is solid.

**Comment by PaulMakepeace** [comment]
Yeah I'd definitely agree you'd need a timeout! I think 2s is on the low side - we aren't connecting over a satellite or anything laggy; just an SSH tunnel which doesn't seem like a 1% use case(?) 5s? 10s more reasonable?

**Comment by ankane** [comment]
Bumped to 5.

**Comment by PaulMakepeace** [comment]
👍
