### ISSUE TITLE
[Idea] Improve detection of duplicate indexes

### ISSUE THREAD

**Issue by dalbani** [ankane/pghero#251]
Hi,
In relation with https://github.com/geoserver/geoserver/pull/3294, I discovered that the folks at PostgreSQL provide an SQL query to list possible duplicate indexes: https://wiki.postgresql.org/wiki/Index_Maintenance#Duplicate_indexes.
It seems to find more occurrences than the current implementation in https://github.com/ankane/pghero/blob/master/lib/pghero/methods/indexes.rb#L171.
Do you think this query would be more appropriate?

**Comment by ankane** [comment]
Hey @dalbani, thanks for the suggestion. I think it's important to understand how they're different. Do you have examples of the differences?

**Comment by ankane** [comment]
Closing since there was no response
