### ISSUE TITLE
Unable to install pghero the repo is not there

### ISSUE THREAD

**Issue by abdulkave** [ankane/pghero#252]
Hi,

Unable to install pghero look like the  repo is not there on.
https://dl.packager.io/srv/pghero/pghero/master/installer/el/7.repo
Please help for the same.

Thanks!
Abdul

**Comment by ankane** [comment]
Hey @abdulkave, this issue is really light on details. The link is working fine for me. If you think it's a PgHero issue, please describe the problem in more detail. Otherwise, check out the Contributing Guide for where to get help.

**Comment by abdulkave** [comment]
Thank You Andrew.
I found some issue with NAT getaway it's working absolutely fine.
