### ISSUE TITLE
[idea] Limit number of open connections

### ISSUE THREAD

**Issue by elbryan** [ankane/pghero#253]
I think it would be nice to be able to specify the maximum number of connections pghero can open. I hit a problem in my system that occurs when (for instance) a transaction is locking a table. In this case pghero tries to get information from the table but Postgres queues the request. Unfortunately, in few minutes pghero will keep on creating new connections that will again queued until the number of maximum connections is exhausted. This prevents others from utilizing the RDBMS and ultimately led me to turn pghero off.

is there a setting/configuration that I am missing or is indeed a desired behaviour?

**Comment by ankane** [comment]
Hey @elbryan, you can add `?pool=1` to your database URL to change the pool size. I believe the default is 5 in Rails (per process).

**Comment by elbryan** [comment]
@ankane thanks for the super quick answer.. it's strange because I have literally seen hundreds of connections in waiting on Postgres.. if 5 is the default settings than this is somehow not honoured (or I am doing it wrong).

**Comment by ankane** [comment]
I'm not sure how to go about reproducing. I'd try forking the gem and adding debugging to see if you can figure out what's going on.

**Comment by elbryan** [comment]
I think I found out the issue and, indeed, it was me.
I am running PGHero on Marathon (on top of Mesos). The application therefore is constantly monitored by Marathon itself (via so-called "health checks"). If a query is enforcing exclusive access to a table, all subsequent queries will be put in "waiting", including pghero's. This ultimately makes pghero stale, waiting for its queries to be resolved. During this time, the health checks from Marathon will timeout, making it believe that the container is in a unhealthy state, hence restarting it. Upon restart, of course pghero doesn't reuse the same connection pool and will create a new connection. This will add to the existing one and so on and on in a vicious circle.

I will hence close this ticket because there is nothing wrong with pghero but the problem lies in the way my system orchestrates its execution. For the sake of completeness of information, tinkering with Marathon health checks has allegedly solved the problem.
