### ISSUE TITLE
Clarify "query stats are stored in your app’s database"

### ISSUE THREAD

**Issue by KickButtowski80** [ankane/pghero#255]
I tried to setup the gem but when I run rake pghero:capture_query_stats , it tells me no current_database is available 

Can you please clarify the following ?

"By default, query stats are stored in your app’s database. Change this with:

ENV["PGHERO_STATS_DATABASE_URL"]"

**Comment by ankane** [comment]
Hey @KickButtowski80, if you're on Linux or Docker, you likely missing the `DATABASE_URL` environment variable.

**Comment by ankane** [comment]
If you're on Rails, it means the Rails app database.

**Comment by KickButtowski80** [comment]
Thank you for your response
I am in c9 and Rails

**Comment by ankane** [comment]
What's the stack trace on the error?
