### ISSUE TITLE
Parallel workers show up as duplicate queries in active queries view

### ISSUE THREAD

**Issue by fake-name** [ankane/pghero#258]
![image](https://user-images.githubusercontent.com/1401239/53693314-a9b06380-3d53-11e9-90ed-a2561e693606.png)

I have one query executing. All the additional instances are the parallel workers for that one query:

![image](https://user-images.githubusercontent.com/1401239/53693323-c2b91480-3d53-11e9-8075-b56e2543c10f.png)

I'm not sure how you'd go about resolving this, but it can be annoying. 

Basically, in this case, the one main query (PID 15209) is using 6 parallel workers to actually generate the results:

```
Finalize GroupAggregate  (cost=8793073.15..15080472.74 rows=14508480 width=82)
  Group Key: url
  Filter: (count(*) > 1)
  ->  Gather Merge  (cost=8793073.15..14209963.94 rows=43525440 width=82)
        Workers Planned: 6
        ->  Partial GroupAggregate  (cost=8792073.05..8919022.25 rows=7254240 width=82)
              Group Key: url
              ->  Sort  (cost=8792073.05..8810208.65 rows=7254240 width=74)
                    Sort Key: url
                    ->  Parallel Seq Scan on web_pages  (cost=0.00..7758224.40 rows=7254240 width=74)
```
The workers in this case are PIDs 27743, 27744, 27745, 27746, 27747, 27748.

I'm on postgresql 11.2, fwiw.

**Comment by fake-name** [comment]
This seems to occur for any parallel queries:

![image](https://user-images.githubusercontent.com/1401239/53693447-5b9c5f80-3d55-11e9-83ce-d53087c3b2db.png)

Also, apparently index creation is parallelized now too!

**Comment by ankane** [comment]
Hey @fake-name, this is expected since each gets its own process.

**Comment by fake-name** [comment]
I understand that, but is there any way to show that they're really one logical query?

It seems an ideal representation would be something like a tree-view with the main query as the root, and then the workers as a level of indentation. 

For that matter, I wonder what happens if you kill one of the query workers without killing the query itself.

**Comment by ankane** [comment]
Hey @fake-name, sorry for the delay. The tree view sounds interesting but don't think it's worth the extra complexity right now.
