### ISSUE TITLE
[Idea] Index Usage Over Time

### ISSUE THREAD

**Issue by sj26** [ankane/pghero#259]
Related to #19, I'd like to be able to track index usage stats over time so I can tell which indexes are used most and, more importantly, when an index stops being used. Would you accept a PR for this feature? I'm guessing it's a new worker `capture_index_stats` or something, to capture data to display maybe starting on the space page for an index?

**Comment by ankane** [comment]
Hey @sj26, thanks for the suggestion and sorry for the delay. I can see this being useful in certain situations, but from my experience, resetting stats and waiting a week or two usually works, so don’t want to add the additional complexity right now. That being said, you should be able to use PgHero methods to build this for your app.
