### ISSUE TITLE
Error in pghero.yml multiple databases example

### ISSUE THREAD

**Issue by omm1979** [ankane/pghero#262]
Hi, let me tell you it's a great tool to monitoring postgresql databases, my problem is when I have more than 1 database to monitor as the setup guide says, I configure just 1 postgresql instance:
sudo pghero config:set DATABASE_URL=postgres://user:password@hostname:5432/dbname

It is running correctly, but now I want to monitor 2 o more databases, my config file is:

![image](https://user-images.githubusercontent.com/43590372/55588461-5ac46800-571d-11e9-9059-de592b9d021d.png)

But when I followed the guide of Multiple Database:
https://github.com/ankane/pghero/blob/master/guides/Linux.md#multiple-databases

As it shows I created the file in /etc/pghero/conf.d/pghero.yml:
![image](https://user-images.githubusercontent.com/43590372/55588735-19808800-571e-11e9-96d8-83db0fbe5009.png)

And run:
```
cat pghero.yml | sudo pghero run sh -c "cat > config/pghero.yml"
sudo service pghero restart
```

But I got the next Error:
![image](https://user-images.githubusercontent.com/43590372/55589057-e12d7980-571e-11e9-9625-3696efe5ec47.png)

Some advices?, Did I do something wrong?, I'll apreciate your help, thanks, regards.

**Comment by ankane** [comment]
Hey @omm1979, unfortunately, I don't have the bandwidth to debug app-specific issues. Check out the Contributing Guide for where to get help.
