### ISSUE TITLE
cannot access temporary tables of other sessions

### ISSUE THREAD

**Issue by allustin** [ankane/pghero#263]
We have `500 Internal Server Error`

on some database with exception

```
ActiveRecord::StatementInvalid (PG::FeatureNotSupported: ERROR:  cannot access temporary tables of other sessions
```

seems like it referensed to #167 and #166

**Comment by allustin** [comment]
In application we have `seq` created on temp_table

full stacktrace is to long, but we this

> 
> | ActiveRecord::StatementInvalid (PG::FeatureNotSupported: 
> ERROR:  cannot access temporary tables of other sessions
> | : SELECT last_value FROM "pg_temp_7"."tt102_sdbl_identity_seq" UNION ALL SELECT last_value FROM "pg_temp_11"."tt43_sdbl_identity_seq"
> UNION ALL SELECT last_value FROM "pg_temp_11"."tt68_sdbl_identity_seq" 
> UNION ALL SELECT last_value FROM "pg_temp_11"."tt69_sdbl_identity_seq" UNION ALL SELECT last_value FROM "pg_temp_11"."tt70_sdbl_identity_seq" UNION ALL SELECT last_value FROM "pg_temp_11"."tt71_sdbl_identity_seq" UNION ALL SELECT last_value FROM "pg_temp_11"."tt72_sdbl_identity_seq" UNION ALL SELECT last_value FROM "pg_temp_11"."tt73_sdbl_identity_seq" UNION ALL SELECT last_value FROM "pg_temp_11"."tt74_sdbl_identity_seq" UNION ALL SELECT last_value FROM "pg_temp_11"."tt75_sdbl_identity_seq" UNION ALL SELECT last_value FROM "pg_temp_11"."tt76_sdbl_identity_seq" UNION ALL SELECT last_value FROM "pg_temp_11"."tt77_sdbl_identity_seq" UNION ALL SELECT last

On 

> 
> | activerecord (5.2.1) lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `select_all'
> | /usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero/methods/basic.rb:40:in `select_all'
> | /usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero/methods/sequences.rb:42:in `block in sequences'
> | /usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero/methods/sequences.rb:39:in `each'
> | /usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero/methods/sequences.rb:39:in `each_slice'
> | /usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero/methods/sequences.rb:39:in `sequences'
> | /usr/local/bundle/bundler/gems/pghero-80960454505dcontrollers/pg_hero/home_controller.rb:45:in `index'

I found this code - https://github.com/ankane/pghero/blob/master/lib/pghero/methods/sequences.rb#L40 

seems like there we must exclude temptables from seq collector, but i'am not sure

**Comment by ankane** [comment]
Hey @allustin, thanks for reporting 👍 Fixed on master.
