### ISSUE TITLE
Being able to see rails migration recommendations for unused indexes in non rails environment

### ISSUE THREAD

**Issue by kwent** [ankane/pghero#266]
Hi @ankane,

I'm using the Docker version.

Would be nice to be able to see rails migration recommendations for unused indexes in non rails environment.

Probably through an ENV ?

Thanks!

**Comment by ankane** [comment]
Added support for `ENV["PGHERO_SHOW_MIGRATIONS"]` on master. Will go out with the next release. https://github.com/pghero/pghero/commit/273bebc9470906112b2260e72d9ba47d9ada9430
