### ISSUE TITLE
[Idea] Configure location of pghero.yaml via ENV

### ISSUE THREAD

**Issue by azanar** [ankane/pghero#273]
**Use case**: I am using the [ankane/pghero](https://hub.docker.com/r/ankane/pghero) docker image in a Kubernetes cluster.

I would like to be able to define a `/app/config/pghero.yaml` file as a Kubernetes resource, to be mounted into the container.

**Limitation**: Unfortunately, Kubernetes can only mount directories, which means masking the other contents of `/app/config/`. This includes `/app/config/puma.rb`:

```/usr/local/bundle/gems/puma-3.12.0/lib/puma/dsl.rb:41:in `read': No such file or directory @ rb_sysopen - config/puma.rb (Errno::ENOENT)```

**Idea**: It would be lovely to be able to provide an alternate path to locate `pghero.yaml` or be able to define it as an environmental variable. As an example declaration: 

```ENV['PGHERO_YML_FILE'] = '/mnt/pghero.yaml'```

This would enable mounting a volume containing it wherever, and supporting this quirk of Kubernetes.

Happy to hear thoughts.

**Comment by ankane** [comment]
Thanks for the clear explanation @azanar. Going with `ENV["PGHERO_CONFIG_PATH"]` as proposed in #244.

**Comment by ankane** [comment]
Just pushed a new version to Docker Hub under `ankane/pghero:latest`. Let me know how it works for you.

**Comment by azanar** [comment]
@ankane works great. thank you!
