### ISSUE TITLE
Duration some times get negative value in live query

### ISSUE THREAD

**Issue by VladislavePolyakov** [ankane/pghero#275]
Hi,
https://github.com/ankane/pghero/blob/0714d085655928e2051c3eff8bcf30af3ca378e1/lib/pghero/methods/queries.rb

In this query from pg_stat_activity you get duration by age(NOW(), COALESCE(query_start, xact_start)) AS duration
And some times get negative value like -5ms
I think this because function now() run early then get values from xact_start
Is it posible make positive value in any times?

![image](https://user-images.githubusercontent.com/36959111/59259207-ff918300-8c41-11e9-8cb3-53fca7ce9291.png)
![image](https://user-images.githubusercontent.com/36959111/59259910-4b90f780-8c43-11e9-9675-4ac9025d3dd1.png)

Thanks!

**Comment by ankane** [comment]
Hey @VladislavePolyakov, does using `clock_timestamp()` instead of `now()` always keep it positive?

**Comment by VladislavePolyakov** [comment]
![image](https://user-images.githubusercontent.com/36959111/59261489-38cbf200-8c46-11e9-9bd6-6e9e314b20ff.png)
yes it helped
