### ISSUE TITLE
Time slider in the Queries tab doesn't work

### ISSUE THREAD

**Issue by Looooong** [ankane/pghero#277]
### What is the problem?

The bug exists in my app using PgHero 2.2.0 and also on the [demo page](https://pghero.dokkuapp.com/datakick/queries). Changing the time slider doesn't work as expected:

+ Changing `start_at` doesn't seem to affect query stats.
+ Changing `end_at` to any value other than **Now** results in _"No data available for this time"_.

### What is the expected behaviour?

Chaging time slider should affect on how the query stats are filtered by `captured_time`.

### What else to be improved?

Using time slider can only filter data captured within 24 hours from the current time. In my app, query stats have been captured for 8 months. However, not all the data are shown in the Queries tab. I wish to be able to see the data lasted longer than 24 hours or all-time data on the Queries tab.

**Comment by ankane** [comment]
Hey @Looooong, thanks for pointing out the issue with the demo (fixed now). This is the expected behavior when the capture query stats task isn't run.

**Comment by Looooong** [comment]
Well, in my app, I have capture query stats task ran every 5 minutes and the Queries tab behaves just like the demo.

**Comment by ankane** [comment]
I'd confirm new rows are being inserted.

**Comment by Looooong** [comment]
Yes, the new rows are inserted. My point is that the Queries tab doesn't show full stats history, but only the recent 5 minutes stat, despite the fact that my `pghero_query_stats` contains all the data from multiple previous stats captures. Here is what the UI looks like on my app:

![Screenshot from 2019-07-29 13-34-24](https://user-images.githubusercontent.com/8206622/62026599-a5ef1300-b205-11e9-96be-a0a51c913923.png)

**Comment by ankane** [comment]
PgHero is designed to only show the last 24 hours. You can fork the app if you'd prefer a longer time period.

I'm not sure why stats aren't showing up in your situation, but I'm not sure how to reproduce.

**Comment by Looooong** [comment]
Finally, I get why the stats don't show up. It's because I'm using multi-tenancy database, and I was looking at the wrong schema. So the recent 5 minutes stats are provided by postgres, not by captured stats. I'm closing this issue now.

**Comment by Looooong** [comment]
Currently, I'm using [Apartment gem](https://github.com/influitive/apartment) for multi-tenancy databases. Let say I have `public` schema and `private` schema. The `public` schema is where the query stats are stored, but the `private` schema is what the Apartment gem switch to when serving web request. The problem is that when viewing the query stats on PgHero UI, the server actually get the historical query stats from `private` schema, which doesn't include the data, because of this raw SQL command:

https://github.com/ankane/pghero/blob/ccf9b477322856b2f89ba5a6858328a9759ac2a8/lib/pghero/methods/query_stats.rb#L211-L221

I suggest to change this command a little bit:

```ruby
select_all_stats <<-SQL
  WITH query_stats AS ( 
    SELECT [...]
    FROM #{PgHero::QueryStats.table_name}
```

With this we can customize the table to store/get query stats (assume that changes are made to all similar code as well. And, with some configuration, Apartment gem automatically changes the table name of `PgHero::QueryStats` by appending `public.`, for example, `public.pghero_query_stats`, so this should work for me as well.

**Comment by elmeriniemela** [comment]
> PgHero is designed to only show the last 24 hours. You can fork the app if you'd prefer a longer time period.

What is the purpose of historical query stats if this is the case? I'm currently trying to display all this week's queries in the UI, but I can only get the last 24h in the UI. The historical query stats table contains queries much older than that, they are just not displayed.
