### ISSUE TITLE
comparison of Array with Array failed

### ISSUE THREAD

**Issue by ACPK** [ankane/pghero#278]
When I visit "/pghero/connections", I get the following error:

    ArgumentError: comparison of Array with Array failed

The error seems to be on line #355 of pghero/app/controllers/pg_hero/home_controller.rb.

          top_connections.sort_by { |k, v| [-v, k] }

**Comment by ankane** [comment]
Hey @ACPK, can you paste the full backtrace?

**Comment by ankane** [comment]
Closing due to no response

**Comment by ACPK** [comment]
rocessing by PgHero::HomeController#connections as HTML
   (23.7ms)  SELECT datname AS database, usename AS user, application_name AS source, client_addr AS ip, COUNT(*) AS total_connections FROM pg_stat_activity GROUP BY 1, 2, 3, 4 ORDER BY 5 DESC, 1, 2, 3, 4 /*pghero*/ /*application:InviteEducation,controller:home,action:connections*/
Completed 500 Internal Server Error in 26ms (ActiveRecord: 23.7ms)

ArgumentError - comparison of Array with Array failed:
  pghero (2.2.1) app/controllers/pg_hero/home_controller.rb:385:in `group_connections'
  pghero (2.2.1) app/controllers/pg_hero/home_controller.rb:278:in `connections'
  actionpack (4.2.11.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.11.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.11.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.11.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  marginalia (1.8.0) lib/marginalia.rb:111:in `record_query_comment'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:312:in `block in halting'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  audited (4.9.0) lib/audited/sweeper.rb:14:in `around'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:455:in `block in make_lambda'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:312:in `block in halting'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.11.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.11.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.11.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.11.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.11.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.11.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.11.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.11.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  searchkick (3.1.3) lib/searchkick/logging.rb:209:in `process_action'
  activerecord (4.2.11.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.11.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.11.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.11.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.11.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.11.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.11.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.11.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.11.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
  railties (4.2.11.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.11.1) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.11.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.11.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.11.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
  omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
  omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
  omniauth (1.6.1) lib/omniauth/strategy.rb:407:in `call_app!'
  omniauth-saml (1.7.0) lib/omniauth/strategies/saml.rb:135:in `other_phase'
  omniauth (1.6.1) lib/omniauth/strategy.rb:188:in `call!'
  omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
  omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
  omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
  omniauth (1.6.1) lib/omniauth/builder.rb:63:in `call'
  apartment (0.24.3) lib/apartment/elevators/generic.rb:22:in `call'
  apartment (0.24.3) lib/apartment/reloader.rb:18:in `call'
  rack (1.6.13) lib/rack/etag.rb:24:in `call'
  rack (1.6.13) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.13) lib/rack/head.rb:13:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.13) lib/rack/session/abstract/id.rb:252:in `context'
  rack (1.6.13) lib/rack/session/abstract/id.rb:247:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.11.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.11.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.11.1) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.11.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  sqreen (1.22.0) lib/sqreen/rails_middleware.rb:13:in `call'
  sqreen (1.22.0) lib/sqreen/error_handling_middleware.rb:15:in `call'
  better_errors (1.0.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (1.0.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (1.0.1) lib/better_errors/middleware.rb:56:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.11.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.11.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.11.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.11.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  logstop (0.2.6) lib/logstop/formatter.rb:17:in `method_missing'
  activesupport (4.2.11.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.11.1) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call_with_quiet_assets'
  request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.13) lib/rack/methodoverride.rb:22:in `call'
  sqreen (1.22.0) lib/sqreen/middleware.rb:13:in `call'
  rack (1.6.13) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.11.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.13) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.13) lib/rack/sendfile.rb:113:in `call'
  sqreen (1.22.0) lib/sqreen/shrink_wrap.rb:13:in `call'
  honeybadger (4.6.0) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
  honeybadger (4.6.0) lib/honeybadger/agent.rb:399:in `with_rack_env'
  honeybadger (4.6.0) lib/honeybadger/rack/error_notifier.rb:30:in `call'
  honeybadger (4.6.0) lib/honeybadger/rack/user_feedback.rb:31:in `call'
  honeybadger (4.6.0) lib/honeybadger/rack/user_informer.rb:21:in `call'
  railties (4.2.11.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.11.1) lib/rails/application.rb:165:in `call'
  rack (1.6.13) lib/rack/content_length.rb:15:in `call'
  puma (4.2.0) lib/puma/configuration.rb:228:in `call'
  puma (4.2.0) lib/puma/server.rb:670:in `handle_request'
  puma (4.2.0) lib/puma/server.rb:473:in `process_client'
  puma (4.2.0) lib/puma/server.rb:331:in `block in run'
  puma (4.2.0) lib/puma/thread_pool.rb:134:in `block in spawn_thread'



Started POST "/pghero/__better_errors/70291770439420/variables" for ::1 at 2021-07-21 16:19:16 -0400
