### ISSUE TITLE
Historical Query Stats job fails to run

### ISSUE THREAD

**Issue by brainimus** [ankane/pghero#28]
The following error is received when attempting to run the historical query stats scheduled task:
```
$ sudo pghero run pghero:capture_query_stats
sh: 1: exec: pghero:capture_query_stats: not found
```

The instructions to install PgHero on Linux (Ubuntu 14.04) were followed.  It appears that PgHero us up and running correctly but the scheduled job produces the error both when run by cron and when run manually.

**Comment by ankane** [comment]
Thanks for reporting Brian.  Try:

```sh
pghero run rake pghero:capture_query_stats
```

I'll update the docs.

**Comment by brainimus** [comment]
Hey Andrew,  I actually tried a few things after poking around a bit.  Still had no luck.

```
$ sudo pghero run rake --trace pghero:capture_query_stats
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
```

```
$ sudo pghero run 'rake pghero:capture_query_stats'
/usr/bin/pghero: line 281: [: /opt/pghero/vendor/pkgr/processes/rake: binary operator expected
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
```

I went digging through the shell script a bit to see if I could locate the issue but I don't know enough about packager(?) to know how it determines paths and dependencies.

**Comment by ankane** [comment]
My bad, should be fixed now.  Try [updating the package](https://github.com/ankane/pghero/blob/master/guides/Linux.md#upgrading) and running:

```sh
sudo pghero run rake pghero:capture_query_stats
```

**Comment by brainimus** [comment]
It looks like that got us moving.  Thanks for your assistance!
