### ISSUE TITLE
% symbol in postgres password returning InvalidURIError

### ISSUE THREAD

**Issue by rodrigo-fss** [ankane/pghero#280]
I believe the % symbol is interpreted as URL escape characters, so im getting this error
`split': bad URI(is not URI?): (URI::InvalidURIError)`

I found a similar error in another lib that may help you guys solve the problem
https://github.com/gogs/gogs/issues/1526

thnx

**Comment by ankane** [comment]
Hey @rodrigo-fss, special characters must be percent-encoded like with `psql`.
