### ISSUE TITLE
[Idea] Audit for invalid constraints, indices, and foreign keys

### ISSUE THREAD

**Issue by geoffharcourt** [ankane/pghero#284]
We had a really bizarre issue today where we created a corrupted foreign key (pointing to a column that doesn't exist and not yet validated) that caused delete operations that the FK pointed at to take 50,000x longer. I'm surprised this is even possible, but an audit of unvalidated foreign keys (certainly possible if folks were building them with strong_migrations and forgot the last step) and incomplete indices would really help surface an issue that might not expose itself through application exceptions.

**Comment by ankane** [comment]
Hey @geoffharcourt, I didn't realize that was possible either, but happy to include a check for it. PgHero already check for invalid indexes. Feel free to submit a PR.

**Comment by geoffharcourt** [comment]
Looking at something like `Methods::Constraints` with this SQL:

```sql
SELECT con.conname AS constraint_name,
       rel.relname AS table_name,
       frel.relname AS foreign_table_name,
       convalidated AS is_validated
       FROM pg_catalog.pg_constraint con
            INNER JOIN pg_catalog.pg_class rel
                       ON rel.oid = con.conrelid
            INNER JOIN pg_catalog.pg_namespace nsp
                       ON nsp.oid = connamespace
            INNER JOIN pg_catalog.pg_class frel
                       ON frel.oid = con.confrelid
       WHERE nsp.nspname = 'public'
       AND convalidated = False;
```

**Comment by ankane** [comment]
Hey @geoffharcourt, thanks for the query. Added an `invalid_constraints` method to master. Will add it to the UI as well before the next release.

**Comment by ankane** [comment]
UI added. Thanks again for the suggestion! Please test it out if you have a chance and let me know if you have feedback.
