### ISSUE TITLE
[Idea] pg_flame

### ISSUE THREAD

**Issue by ohaddahan** [ankane/pghero#285]
I recently found out about:
https://github.com/mgartner/pg_flame

Seems like a great complementary feature for the existing `EXPLAIN` analysis.

**Comment by ankane** [comment]
Hey @ohaddahan, thanks for the suggestion. You should be able to use the output from the "Visualize" button directly in that tool.

**Comment by ohaddahan** [comment]
@ankane Yeah I know that I was thinking of adding it as a dependency and using it inside PGHero instead of manually pasting it into it.
I think it's useful , but whatever you prefer.

**Comment by ankane** [comment]
Yeah, I think it's better as a separate tool.
