### ISSUE TITLE
[Idea] Expose some prometheus metrics

### ISSUE THREAD

**Issue by luizm** [ankane/pghero#294]
Hi there

Pghero is really useful but sometimes has a lack of time to check the recommendation, If We could get the metrics, perhaps using prometheus I could create an alarm to notify me if I have, for example, indexes not be using or absent.

Thank you.

**Comment by ankane** [comment]
Hi @luizm, thanks for the suggestion. You can use the Ruby methods to access the underlying data. This feature is a bit outside the scope of what I'd like to support right now, but someone could write another gem that does this.

**Comment by luizm** [comment]
> You can use the Ruby methods to access the underlying data. This feature is a bit outside the scope of what I'd like to support right now, but someone could write another gem that does this.

Sure, is there an example of a project that do it? I'd take a look.

**Comment by ankane** [comment]
I'm not aware of any gems that extend PgHero right now.
