### ISSUE TITLE
PgHero Overview broken since upgrade to Postgres 12

### ISSUE THREAD

**Issue by shaulbehr** [ankane/pghero#296]
Hi,
We recently upgraded our postgres servers to version 12.
Since then, pghero cannot show the Overview screen (returns HTTP 500). All the other links down the sidebar (`/live_queries`, `/space`, etc.) work fine. But Overview is broken.
Could this be linked to postgres 12? Or some other issue that's crept into our environment?
How do we go about fixing this?

**Comment by ankane** [comment]
Hey @shaulbehr, can you paste the error message and stack trace?

**Comment by shaulbehr** [comment]
@ankane On the browser client there is no information beyond an HTTP 500 reponse. Where would I find logs on the host?

**Comment by ankane** [comment]
For Rails, logs are with the other Rails logs. For Docker, logs go to stdout. For Linux, instructions are in the Linux docs.

**Comment by shaulbehr** [comment]
Aha. Here ya go:
```
Started GET "/prod-lightsailcommondata" for 10.0.1.51 at 2020-01-21 08:28:32 +0000
Processing by PgHero::HomeController#index as HTML
  Parameters: {"database"=>"prod-lightsailcommondata"}
Completed 500 Internal Server Error in 57ms (ActiveRecord: 23.7ms)

ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column d.adsrc does not exist
LINE 1: ...um) WHERE NOT a.attisdropped AND a.attnum > 0 AND d.adsrc LI...
                                                             ^
: SELECT n.nspname AS table_schema, c.relname AS table, attname AS column, format_type(a.atttypid, a.atttypmod) AS column_type, pg_get_expr(d.adbin, d.adrelid) AS default_value FROM pg_catalog.pg_attribute a INNER JOIN pg_catalog.pg_class c ON c.oid = a.attrelid INNER JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace INNER JOIN pg_catalog.pg_attrdef d ON (a.attrelid, a.attnum) = (d.adrelid, d.adnum) WHERE NOT a.attisdropped AND a.attnum > 0 AND d.adsrc LIKE 'nextval%'):
```

**Comment by ankane** [comment]
Upgrading your version of PgHero should fix the issue: https://github.com/ankane/pghero/issues/276

**Comment by shaulbehr** [comment]
Thank you, that did it :-)
