### ISSUE TITLE
Custom asset_host not supported with override_csp

### ISSUE THREAD

**Issue by Gargron** [ankane/pghero#297]
If you have an asset host configured in Rails such as that you serve CSS and JS from a different subdomain, and you have the override_csp option enabled in pgHero, no CSS or JS will be loaded because the CSP blocks it.

**Comment by ankane** [comment]
Hey @Gargron, thanks for the report. Give master a shot.

**Comment by ankane** [comment]
Decide to revert since it adds too much complexity for this feature. You can create an initializer to set your own CSP policy with:

```ruby
PgHero::HomeController.after_action do
  response.headers["Content-Security-Policy"] = "default-src https://yourhost.com 'unsafe-inline'"
end
```

(and avoid setting `override_csp`)
