### ISSUE TITLE
Segmentation fault under postgres 9.5

### ISSUE THREAD

**Issue by mjbommar** [ankane/pghero#30]
First off, thank you for an awesome product!  It's hard to imagine going back to a world before...

On to the unfortunate issue:

### Previous State:
pghero setup on trusty 14.04 with apt.postgresql.org postgresql-9.3; no issue running for over a week.  

### Upgrade:
Upgraded from 9.3 to 9.5-alpha1 via apt.postgresql.org apt and `pg_dump`/`pg_restore`.  All other application behavior is as expected without error. 

### Segmentation fault and log
However, a segmentation fault occurs on the following query issued by pghero.  Seems to be related to clicking the "Queries" tab in pghero.   Cannot provide the core dump due to proprietary information.

This seems like misbehavior from postgres per se, but since it affects pghero and you are likely more capable of understanding and reproducing with shareable core dump for core development, I am filing here to start.

```
2015-07-06 00:37:52 UTC [24260-2] LOG:  server process (PID 10695) was terminated by signal 11: Segmentation fault
2015-07-06 00:37:52 UTC [24260-3] DETAIL:  Failed process was running: SELECT pid, state, application_name AS source, age(now(), xac
t_start) AS duration, waiting, query, xact_start AS started_at FROM pg_stat_activity WHERE query <> '<insufficient privilege>' AND s
tate <> 'idle' AND pid <> pg_backend_pid() AND now() - query_start > interval '60 seconds' ORDER BY query_start DESC
```

**Comment by ankane** [comment]
Closing, as this seems related to the alpha build.
