### ISSUE TITLE
How do I clear stats?

### ISSUE THREAD

**Issue by peterbe** [ankane/pghero#301]
I'm ready to start afresh. My `pghero_stats` database is now ~8GB. 

```
django@peterbecom-ubuntu-4gb-nyc1-01:~$ psql pghero_stats
psql (9.5.19)
Type "help" for help.

pghero_stats=# select table_name, pg_relation_size(table_name), pg_size_pretty(pg_relation_size(table_name))
pghero_stats-# from information_schema.tables
pghero_stats-# where table_schema = 'public'
pghero_stats-# order by 2 desc limit 10;
     table_name     | pg_relation_size | pg_size_pretty
--------------------+------------------+----------------
 pghero_space_stats |       3751051264 | 3577 MB
 pghero_query_stats |       1964818432 | 1874 MB
(2 rows)
```

Do I dare to just truncate those tables?

**Comment by ankane** [comment]
Hey @peterbe, truncating should be fine. The docs also have instructions for how to delete old query stats.

**Comment by peterbe** [comment]
> Hey @peterbe, truncating should be fine. The docs also have instructions for how to delete old query stats.

"The docs"?? Are there docs? Awesome! But where do I find them?
I see nothing about documentation here: https://github.com/ankane/pghero/blob/master/README.md

I did find [this page](https://github.com/ankane/pghero/blob/master/guides/Query-Stats.md) but no mention about how to delete old query stats.

**Comment by ankane** [comment]
The readme links to the docs for each installation type.

**Comment by peterbe** [comment]
Sorry for being dim but where in https://github.com/ankane/pghero/blob/master/guides/Linux.md does it say how to clear the stats?
I still haven't found it. Perhaps I'm staring at it but can't see it.

**Comment by marckohlbrugge** [comment]
@peterbe It's in the Rails doc: https://github.com/ankane/pghero/blob/master/guides/Rails.md

```sh
rake pghero:clean_query_stats
```

or

```rb
PgHero.clean_query_stats
```

**Comment by lacostenycoder** [comment]
> > Hey @peterbe, truncating should be fine. The docs also have instructions for how to delete old query stats.
> 
> "The docs"?? Are there docs? Awesome! But where do I find them?
> I see nothing about documentation here: https://github.com/ankane/pghero/blob/master/README.md
> 
> I did find [this page](https://github.com/ankane/pghero/blob/master/guides/Query-Stats.md) but no mention about how to delete old query stats.

I had the same problem and ended up on this issue to find the answer, so.... 
https://github.com/ankane/pghero/pull/378
