### ISSUE TITLE
Unreadable Sequences

### ISSUE THREAD

**Issue by imcvampire** [ankane/pghero#302]
The dashboard throws 

```
Unreadable Sequences
This is likely due to missing privileges. Make sure your user has the SELECT privilege for each sequence.
```

after creating a user following https://github.com/ankane/pghero/blob/master/guides/Permissions.md

**Comment by ankane** [comment]
Hey @imcvampire, try running:

```sql
GRANT SELECT ON ALL SEQUENCES IN SCHEMA pghero TO pghero;
```

If that works, will add it to the instructions.

**Comment by imcvampire** [comment]
@ankane It works. Thank you!

And please add it to README too!

**Comment by ankane** [comment]
Added. You'll likely want to grant permissions for future sequences as well.

```sql
ALTER DEFAULT PRIVILEGES FOR ROLE <migrations-user> IN SCHEMA public GRANT SELECT ON SEQUENCES TO pghero;
```
