### ISSUE TITLE
PG Stats Not Enabled

### ISSUE THREAD

**Issue by ACPK** [ankane/pghero#303]
We migrated from RDS Postgres to RDS AuroraPostgres, and we now get that PG stats are not enabled.

We have changed `shared_preload_libraries` to` pg_stat_statements`, enabled query stats, and restarted the server.

Addition, I ran `SELECT * FROM pg_available_extension_versions`  and saw that `pg_stat_statements` version 1.6 is enabled.

However, I did notice the following error when running `SELECT * FROM public.pg_stat_statements LIMIT 1`.

[2020-03-12 15:23:11] [42P01] ERROR: relation "public.pg_stat_statements" does not exist
[2020-03-12 15:23:11] Position: 15

**Comment by ankane** [comment]
Hey @ACPK, check out [this doc](https://github.com/ankane/pghero/blob/master/guides/Query-Stats.md) for instructions and common issues. I haven't seen or heard of any issues specific to Aurora.
