### ISSUE TITLE
How to clear DB stats?

### ISSUE THREAD

**Issue by gen0cide** [ankane/pghero#307]
Hey everyone,

Not sure if this is either an idea or a bug, but I'm having an issue and I'm not sure how to fix it. 

## System Information
System is a Rails 5.x Application using a `mount` engine exactly as documented in the Rails guide. 

## Background
Originally, I had setup the capture stats commands inside of a reoccuring ActiveJob:

```ruby
class UpdateDatabaseStatsJob < ApplicationJob
  queue_as :default

  def perform(*_args)
    PgHero.capture_query_stats
    PgHero.capture_space_stats
  end
end
```

Where I messed up is that I set that re-occurring cron to every 1 minute. That ran for some time. I have since corrected it to reflect the recommendations on the guide:

* `capture_query_stats` every 5 minutes
* `capture_space_stats` every 1 day

and I ran:

```
Loading production environment (Rails 5.2.4.2)
[1] pry(main)> PgHero.clean_query_stats
=> true
[2] pry(main)> PgHero.clean_space_stats
=> true
[3] pry(main)>
```

But when I look at the web interface, it's still showing a MASSIVE amount of data being stored for those tables. I've attached a screenshot of the Spaces tab inside the web UI showing the size these tables are taking up, compared to the next largest tables in my DB.

![image](https://user-images.githubusercontent.com/1515437/78169406-31105080-7406-11ea-9da6-12876eb483fa.png)

Am I doing something wrong? Is there something else I need to do? Ultimately I just want to correct this :)

Thanks,

Alex

**Comment by ankane** [comment]
Postgres doesn't reclaim space when you delete rows (as those methods do). You'll probably want to truncate the tables (which does reclaim space) and start again.
