### ISSUE TITLE
Make pghero_query_stats in a different schema

### ISSUE THREAD

**Issue by himat** [ankane/pghero#310]
Hi, if I want to enable `pghero_query_stats`, then can I make that table in a separate schema from my usual `public` schema?
If I do this, how do I tell pghero that it's in a different schema (still in this same database).

**Comment by ankane** [comment]
Hey @himat, try adding `?schema_search_path=other_schema,public` to the stats database url.

**Comment by aka13-404** [comment]
Just to ease searching for it, this is related to "Query stats must be enabled for slow queries", when using any schema.
