### ISSUE TITLE
How can I prevent pg_stat_statements_reset from being run?

### ISSUE THREAD

**Issue by ericgross** [ankane/pghero#313]
I am running on Heroku (postgres 12) where I don't have superuser permissions - so this is failing.

Is it possible to prevent pg_hero from trying to reset this data?

**Comment by rdlugosz** [comment]
Tagging on to follow and to add that this worked on Heroku Postgres prior to the PG 12 upgrade.

**Comment by ericgross** [comment]
Yes - this used to work for me.

**Comment by ankane** [comment]
This isn't currently supported. I just tried reseting stats on a fresh Heroku Postgres 12 database and it worked, so it should be possible to set up.

**Comment by ankane** [comment]
There should be resources online for how to update Postgres permissions. Check out the Contributing Guide for where to get additional help.
