### ISSUE TITLE
Misinterpretation of pg_index.indkey column results in overestimate of index bloat

### ISSUE THREAD

**Issue by bonesmoses** [ankane/pghero#314]
In `index_item_sizes` portion of the index bloat query, indexes with multiple columns do not retain all attributes from the `btree_index_atts` subquery. This is due to a misunderstanding of the contents of the `pg_index.indkey` column.

From the documentation:

> This is an array of indnatts values that indicate which table columns this index indexes. For example a value of 1 3 would mean that the first and the third table columns make up the index key. A zero in this array indicates that the corresponding index attribute is an expression over the table columns, rather than a simple column reference.

Thus if columns 2 and 3 are indexed, indkey will reflect '2 3'. However, in `pg_attribute`, the index attributes will be 1 and 2. Thus joining the two tables will result in only one attribute result (2==2), and it will be incorrect (table col2 != index col2).

There are generally two ways to fix this:

1. Alter the JOIN to `pg_attribute` to use `indexrelid` instead, and subsequently modify the JOIN to `pg_stats` similarly.
2. Replace the `regexp_split_to_table` call with `generate_series` bounded by `pg_index.indnatts`. If an index has 3 columns, the attributes in `pg_attribute` will be listed as 1, 2, and 3. This means the `indkey` split isn't strictly necessary.

**Comment by ankane** [comment]
Hey @bonesmoses, thanks for taking a look. At first glance, I'm not sure I see the issue. It seems like `indkey` references the table columns and the `pg_attribute` join happens on the table (`indrelid`).

```sql
WITH tmp AS (
  SELECT relname, indrelid, regexp_split_to_table(indkey::text, ' ')::smallint AS attnum
  FROM pg_index
  INNER JOIN pg_class ON pg_class.oid = pg_index.indexrelid
  WHERE relname not like 'pg_%'
)
SELECT relname, tmp.attnum, attname FROM tmp
INNER JOIN pg_attribute ON pg_attribute.attrelid = tmp.indrelid AND pg_attribute.attnum = tmp.attnum;

```

**Comment by ankane** [comment]
Cleaning up issues. Let me know if you have thoughts on the above.

**Comment by bonesmoses** [comment]
I apologize for not checking this in more depth. I glanced at the query and it had sufficient similarity to this one:

https://github.com/pgexperts/pgx_scripts/blob/master/bloat/index_bloat_check.sql

That I assumed it had the same issue. Unfortunately I didn't pay close enough attention to the predicate where they made their initial mistake:

```
JOIN btree_index_atts AS ind_atts ON pg_attribute.attrelid = ind_atts.indexrelid AND pg_attribute.attnum = ind_atts.attnum
```

Whereas they used `indexrelid`, you properly used `indrelid`. Thanks for closing this while I dug out from an unrelated mountain of work. :)

**Comment by ankane** [comment]
No worries, was good to have another set of eyes on it. Josh Berkus gets the credit for writing it.
