### ISSUE TITLE
Permissions issue when connecting with newly created ROLE pghero 

### ISSUE THREAD

**Issue by choesang** [ankane/pghero#315]
Hi,
I am working on a Postgres 9.6. 
I have executed the query as defined in the Permissions page with a SUPERUSER privilege. Below is an excerpt from the query with bold text as my values.

I get a HttpStatus 500, when connecting to the database is used with pghero user but works fine with my other db user. I must be doing something blatantly wrong, but dont know what. 

-- create user
CREATE ROLE pghero WITH LOGIN PASSWORD '**my-private-secret-key**';
GRANT CONNECT ON DATABASE **platform_wl** TO pghero;
ALTER ROLE pghero SET search_path = pghero, pg_catalog, public;
GRANT USAGE ON SCHEMA pghero TO pghero;
GRANT SELECT ON ALL TABLES IN SCHEMA pghero TO pghero;

-- grant permissions for current sequences
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO pghero;

-- grant permissions for future sequences
ALTER DEFAULT PRIVILEGES FOR ROLE **pghero** IN SCHEMA public GRANT SELECT ON SEQUENCES TO pghero;

**Comment by ankane** [comment]
Hey @choesang, you should be able to find an error message in the logs. Please check out the Contributing Guide for where to get additional help.

**Comment by choesang** [comment]
@ankane Thank you for the hint. It was a permission denied exception for relation pghero_query_stats. I then looked at the table privileges of the user pghero and found that it has no privileges for tables in public schema. 
```
select  *
from information_schema.role_table_grants
where grantee='pghero';
```

I have added this explicit privileges (USAGE and SELECT) on public schema. I wonder how it works for you without explicitly granting this privilege?

```
GRANT USAGE ON SCHEMA public TO pghero;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO pghero;
```

**Comment by choesang** [comment]
I get it now. You create the tables pghero_space_stats and pghero_query_stats in pghero schema. It was not easy to understand from the documentation that you create those tables using the newly created role. I assumed that since granted the privileges using a SUPERUSER, i also create those 2 tables with that user.
