### ISSUE TITLE
Unable to run as non-superuser, functions never called

### ISSUE THREAD

**Issue by joekohlsdorf** [ankane/pghero#316]
The steps outlined here https://github.com/ankane/pghero/blob/master/guides/Permissions.md to run queries with a restricted user do not work.

The problem is that the defined functions are never called in the code, for example here:
https://github.com/ankane/pghero/blob/74f73d32523cc51cc37495dc740636380d56ea6f/lib/pghero/methods/query_stats.rb#L179

You run `SELECT * FROM pg_stat_statements;` but it should be `SELECT * FROM pg_stat_statements();` to use the function.

To not make it extremely confusing I suggest to use the same function names as pgAnalyze, for example `get_stat_statements()` and check for their existence before running the query.

**Comment by ankane** [comment]
Hey @joekohlsdorf, there are views that wrap the functions:

```sql
CREATE VIEW pghero.pg_stat_statements AS SELECT * FROM pghero.pg_stat_statements();
```

I appreciate the suggestion, but if the view names are consistent with the Postgres table names, there's no need to check for their existence, which makes things simpler.
