### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by ankane** [ankane/pghero#318]
PgHero 3.0

- [ ] (breaking) Make `capture_query_stats`  only reset stats for database instead of instance in Postgres 12+
- [ ] (breaking) Make `reset_query_stats` only reset stats for current database (use new `reset_instance_query_stats` method to reset for entire instance)
- [ ] Only suggest removing large unused indexes on space page
- [ ] Drop support for Rails < 6 and Ruby < 2.7
- [ ] Drop support for pg_query < 2
- [ ] Drop support for EOL Linux distributions
- [ ] Switch visualize link to Postgres Explain Visualizer 2 - #369
- [ ] (maybe) Normalize query stats to save space

Ideas

- [x] Add system stats for other providers (no API for: Heroku, Digital Ocean)
  - [x] Google Cloud SQL
  - [x] Azure
- [x] Add support for `google-cloud-monitoring-v3` gem
- [x] Add support for Postgres 13 (`pg_stat_statements` no longer has `total_time`)
- [ ] Use `pg_stat_statements` version instead of Postgres version for `query_stats` - `pg_stat_statements_version` branch
- [ ] Remove connections check for Postgres 14 (when released)

Hold

- [ ] Add `leader_pid` to `running_queries` for Postgres 13+ (`leader_pid` is [not reset](https://rjuju.github.io/postgresql/2020/02/06/new-in-pg13-leader_pid.html) after query completes)

Probably not

- [ ] Show security alerts based on Postgres version (no external connections - include `core server` and possibly `contrib module` issues from [this data](https://www.postgresql.org/support/security/) with the gem). Downside: could give false sense of security since it'll be outdated.

**Comment by nacengineer** [comment]
How do you run the rake tasks as a different user in an existing rails application, i.e. use the non superuser user to run tasks.

**Comment by bheemreddy181** [comment]
@ankane Is there a way we can disable the `Explain` part from the board?

**Comment by ankane** [comment]
@nacengineer For Rails, you can set `PGHERO_DATABASE_URL` to the non-superuser user or generate a config file (see docs for how).

@bheemreddy181 There's not a way to disable any pages. The docs should have instructions for authentication for each installation type.

**Comment by bheemreddy181** [comment]
@ankane did you ever thought about PGHero Authenticaton at database level like DB A is only authorised for Team A and DB B is authorised only for team B ?

**Comment by ankane** [comment]
@bheemreddy181 You can set up separate instances of PgHero with different configurations for separate teams. PgHero doesn't have any built-in authorization.

**Comment by rromanchuk** [comment]
It would be nice if this could support IAM RDS based connections, ive been using an ec2 role with this dependency with https://github.com/haines/pg-aws_rds_iam and it's been working well

**Comment by ankane** [comment]
Hey @rromanchuk, are you seeing an issue when trying to use it PgHero?

**Comment by atkawa7** [comment]
Support query **[fingerprint](https://pganalyze.com/blog/pg-query-2-0-postgres-query-parser#fingerprints-in-pg_query-a-better-way-to-check-if-two-queries-are-identical)**

**Comment by andyatkinson** [comment]
@bheemreddy181 We disabled a couple features we didn't want to use, using the config file. I proposed it as a PR but @ankane didn't want to support it, but feel free to look at my fork for inspiration. You posted quite a while back though so perhaps you pursued another solution in the meantime. https://github.com/ankane/pghero/pull/379

**Comment by lucasarrielenjoei** [comment]
Recently we are having I/O problem cost in AWS and we have to disable capture_query_stats to get information from pg_stat_statements, more specific the info from blk_read_time and blk_write_time, the query's that are having a lot of I/O usage was not necessary the worst time queries. So we are asking to save the information about this fields in the pghero_query_stats. Just having this info in this tables , means that we don't need to disable capture_query_stats for data analyses.

**Comment by ankane** [comment]
@atkawa7 I don't fully understand the suggestion, but feel free to create an issue with more details.

@lucasarrielenjoei I don't think it's common enough to support, but you can probably fork and add for your own applications.

Also, moved the 3.0 plan to #415, so closing this thread.
