### ISSUE TITLE
Install for Ubuntu 20.04

### ISSUE THREAD

**Issue by peterbe** [ankane/pghero#320]
Either it's missing from https://github.com/ankane/pghero/blob/master/guides/Linux.md or it's not supported.

**Comment by ankane** [comment]
Hey @peterbe, PgHero uses packager.io to build Linux packages, which doesn't support Ubuntu 20.04 yet. Will add it when it does.

**Comment by peterbe** [comment]
Thanks!

**Comment by ankane** [comment]
Hey @peterbe, the Ubuntu 20.04 package is now available (thanks to @crohr).
