### ISSUE TITLE
Google Cloud Monitoring Lib broken

### ISSUE THREAD

**Issue by trevorrjohn** [ankane/pghero#321]
Hi,

I tried to follow the instructions to configure my CloudSQL database, however it looks like the code is using an old version of the `google-cloud-monitoring` gem. It might be worth adding to the readme that you need to pin the version to `< 1.0`, (I believe this is the breaking version). 

https://googleapis.dev/ruby/google-cloud-monitoring/latest/file.MIGRATING.html

**Comment by ankane** [comment]
Hey @trevorrjohn, thanks for reporting. It looks like 1.0 was released earlier this month.
