### ISSUE TITLE
setup (systemd, database_url) 

### ISSUE THREAD

**Issue by till** [ankane/pghero#323]
I installed pghero today using your yum instructions — kudos, it works beautifully.

It seemed like the package doesn't include a systemd unit, so here it is:

```
[Unit]
Description=pghero
After=network.target
Wants=network-online.target

[Service]
Type=simple

User=pghero
Group=pghero

ExecStart=/usr/bin/pghero run web
Restart=always

[Install]
WantedBy=multi-user.target
```

It seems to work. If I can PR that to some place, let me know.

---

Another thing is that for a noob like myself, the `DATABASE_URL` was a struggle. Especially since my passwords have lots of weird characters.

I had to do something like (this is for Ansible):

```yaml
"postgres://{{ pg_hero_user }}:{{ pg_hero_passwd | urlencode() }}@127.0.0.1/?sslmode=disable"
```

**Comment by ankane** [comment]
Hey @till, thanks for sharing! PgHero uses packager.io for Linux packages - I'm not sure if there's a way to add a systemd unit. Also, added a note to the Docker and Linux docs about special characters.

**Comment by till** [comment]
@ankane Never heard of packager.io. But looks interesting. It seems like CentOS7 is supported, which requires systemd. [So they note on their website.](https://doc.packager.io/documentation/distributions/) Is there a manifest of some kind that you use to build the packages?

**Comment by till** [comment]
Ah! Looks like you need this file:
https://doc.packager.io/documentation/customizing-the-build/

And then maybe explicitly add a target? Not sure what you configured in their UI so far.

**Comment by ankane** [comment]
The config is [here](https://github.com/pghero/pghero/blob/master/.pkgr.yml) (separate repo).

**Comment by till** [comment]
@ankane so, part of this was a misunderstanding: Cyril from support helped me out though. It looks like the initial scale creates all units. And it seemed like I missed that — I was looking for a unit right away. :) Should we add a note about that to the docs?

They seem to add one for:

 - `pghero`
 - `pghero-web`
 - `pghero-web-X` (x = amount of `scale`)

So, `systemctl status pghero` and reload/restart works for me.

**Comment by ankane** [comment]
Thanks for looking into it. Feel free to submit a PR to improve the docs.

**Comment by ankane** [comment]
Cleaning up issues
