### ISSUE TITLE
Question : Query stats

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/pghero#325]
Hi @ankane 

We are trying to enable https://github.com/ankane/pghero/blob/master/guides/Docker.md#historical-query-stats using docker scheduler.

We started seeing that pghero is trying to access `pg_stat_statements_reset` table 

Can we know what could be the possible reason for it to access that table?

I could see that it is trying to clean from here https://github.com/ankane/pghero/blob/master/lib/pghero/methods/query_stats.rb#L109

**Comment by bheemreddy181** [comment]
if possbile can we make [this](https://github.com/ankane/pghero/blob/master/lib/pghero/methods/query_stats.rb#L59) optional as we use this several other purposes on our end.

**Comment by ankane** [comment]
Hey @bheemreddy181, stats are reset after they're captured, and with the current approach, won't be accurate if that's disabled.

You could take snapshots of the `pg_stat_statements` table without resetting it and have different logic to calculate the stats, but this approach is a bit more complicated and not something I'd like to support right now. You could implement this yourself and still use the PgHero UI if you insert the differences between snapshots into the `pghero_query_stats` table.

**Comment by bheemreddy181** [comment]
Cool thanks.
