### ISSUE TITLE
Empty Queries

### ISSUE THREAD

**Issue by jwilson114** [ankane/pghero#326]
I followed the install instruction to set up using Rails however the queries tab is empty and returns "unknown query". When I look in the database I can see there is data within the pg_stats_statement, pghero_query_stats and pghero_space_stats tables. The rails database user is a superuser and all the recommended setup sets were cxompleted. When I pun PgHero.query_stats from the console data is returned. What I have missed in the setup? Many thanks

**Comment by ankane** [comment]
Hey @jwilson114, can you take a screenshot of what you're seeing?

**Comment by jwilson114** [comment]
Hy @ankane, Thanks so much for getting back to me. Ive attached a screenshot

<img width="1132" alt="Screen Shot 2020-07-12 at 5 08 54 pm" src="https://user-images.githubusercontent.com/20564995/87241052-80810680-c462-11ea-80da-f782d31ea0e2.png">

**Comment by ankane** [comment]
It looks like something may be adding a trailing slash to your routes - `/queries/` instead of `/queries`.

**Comment by jwilson114** [comment]
Thanks so much @ankane thats sorted it. Great app as well.

**Comment by ankane** [comment]
Great to hear. What was the cause of the trailing slash? I think others who run into this may find it helpful.

**Comment by ankane** [comment]
Cleaning up issues
