### ISSUE TITLE
Questions around Query slider

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/pghero#328]
Using docker installations mentioned [here](https://github.com/ankane/pghero/blob/master/guides/Docker.md#customization--multiple-databases) I was able to setup pg hero successfully and I am using `cron` to run pghero:capture_query_stats but not able to see slider in the queries tab.

Am I missing something here ?

**Comment by ankane** [comment]
Hey @bheemreddy181, the slider will appear once the table is set up. Please check out the Contributing Guide for where to get help.

**Comment by bheemreddy181** [comment]
Hey @ankane I could see the table setup is successful and I could see the stats being captured for every 5 mins, but still the slider seems missing.

**Comment by bheemreddy181** [comment]
Hey @ankane help me if am wrong you are talking about this table correct 
```
CREATE TABLE "pghero_query_stats" (
  "id" bigserial primary key,
  "database" text,
  "user" text,
  "query" text,
  "query_hash" bigint,
  "total_time" float,
  "calls" bigint,
  "captured_at" timestamp
);
CREATE INDEX ON "pghero_query_stats" ("database", "captured_at");
```
I could see the stats getting captured correctly 

<img width="976" alt="Screen Shot 2020-07-21 at 20 58 42" src="https://user-images.githubusercontent.com/3464623/88125478-00128200-cb95-11ea-89ea-0bef8b7354c2.png">

**Comment by ideeeveee** [comment]
@bheemreddy181 I am facing the same issue with the slider not being available even when the table is present with the necessary data. Did you get a solution to this?

**Comment by bheemreddy181** [comment]
@ideeeveee Nope I am still waiting to spin up a production version for this - I hope the new installation will fix the problem
