### ISSUE TITLE
pghero gives me a blank webpage

### ISSUE THREAD

**Issue by baphill** [ankane/pghero#329]
Hi,

Before creating an issue, please check out the Contributing Guide:

https://github.com/ankane/pghero/blob/master/CONTRIBUTING.md

Thanks!

**Comment by baphill** [comment]
I installed according to instructions for centos7.  I run the curl and it comes back with nothing. The pghero is running according to systemctl command.  Was there a prerequisite function I should have installed?

**Comment by baphill** [comment]
root@postgres pgsql]# curl -v http://localhost:3001/
* About to connect() to localhost port 3001 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3001 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:3001
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/html; charset=UTF-8
< X-Request-Id: ea9b9f85-d725-4850-a242-27e315e83bcb
< X-Runtime: 0.012699
< Content-Length: 0
< 
* Connection #0 to host localhost left intact

**Comment by ankane** [comment]
@baphill What do the logs say?

**Comment by baphill** [comment]
rack (2.2.3) lib/rack/urlmap.rb:74:in `block in call'
rack (2.2.3) lib/rack/urlmap.rb:58:in `each'
rack (2.2.3) lib/rack/urlmap.rb:58:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 192.168.122.1 at 2020-07-28 12:20:43 -0400
Processing by PgHero::HomeController#index as HTML
Completed 500 Internal Server Error in 2ms (Allocations: 408)
  
PG::ConnectionBad (FATAL:  Ident authentication failed for user "postgres"
):

**Comment by ankane** [comment]
That means there's an issue with your database connection info (`DATABASE_URL`). Check out the Contributing Guide for where to get additional help if needed.
