### ISSUE TITLE
'Queries' pane unusable on Google Cloud SQL

### ISSUE THREAD

**Issue by aodj** [ankane/pghero#333]
I realise that this topic has been covered in other issues for "insufficient permissions" but I wanted to specifically post this issue to head off any other users that might desire to use pghero on Google's Cloud SQL platform. 

As far as I can tell, due to the restrictive nature of the `default` user that gets made when the Cloud SQL instance is created, it's not possible to see any of the queries run by other users. Almost all the entries in the `public.pg_stat_statements` view show as `<insufficient privilege>`

![Screenshot 2020-08-25 at 17 26 37](https://user-images.githubusercontent.com/1374905/91287495-591a9a80-e77f-11ea-93a0-8b22b2082ac3.png)

I don't know of any work around that would allow me to view the queries (ie: messing with roles, in-as-much as the `default` user can) so just wanted to hopefully prevent anyone else wanting to use pghero on Google Cloud SQL. 

_shakes fist at Google_

**Comment by ankane** [comment]
Hey @aodj, have you tried the `postgres` user? https://cloud.google.com/sql/docs/postgres/users

**Comment by ankane** [comment]
From the docs:

> NOTE: When using EXTENSION pg_stat_statements, SQL statements from all users are visible to users with the cloudsqlsuperuser ROLE (in PostgreSQL version 10 and higher). Don't use plain text passwords in queries. 

https://cloud.google.com/sql/docs/postgres/create-manage-users

**Comment by aodj** [comment]
Hi @ankane, thanks for your prompt reply!

> Hey @aodj, have you tried the `postgres` user? https://cloud.google.com/sql/docs/postgres/users

Yes, 

```psql
SELECT count(*) FROM public.pg_stat_statements WHERE query = '<insufficient privilege>';
 count
-------
   357
```

We are using PostgreSQL 9.6 currently, are you sure that moving to 10+ would help?

**Comment by ankane** [comment]
I haven't tried it, but that's what the Cloud SQL docs say.

**Comment by ankane** [comment]
Cleaning up issues
