### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by pascualguerreroc** [ankane/pghero#334]
Hi, I'm getting this issue
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://dl.packager.io/srv/deb/pghero/pghero/master/ubuntu  20.04 InRelease' doesn't support architecture **'armhf'**

**Comment by ankane** [comment]
Hey @pascualguerreroc, PgHero uses packager.io for Linux packages, which doesn't support ARM as far as I know.
