### ISSUE TITLE
[Idea] Extending Controller to add features

### ISSUE THREAD

**Issue by raivil** [ankane/pghero#335]
Hey,

I'm looking to extend Pghero logging features by adding more attributes to logs. Example: user_id, host, etc.

This can be achieve by using lograge or other logging gem. However, some attributes are not available to the `PgHero::HomeController`.

I'm using pghero on a custom rails app, and the `ApplicationController` has the following code:
```
  def append_info_to_payload(payload)
    super
    payload.merge!({my_attribute: "somevalue"})
  end
```

One idea would be to add a empty concern to `HomeController` and then overriding that concern on the app side.

```
module PgHero
  class HomeController < ActionController::Base
     include PgHero::Controllers::Concerns::MyPgHeroConcern
```

Thoughts? Do you have any other idea on this?

Best,

**Comment by ankane** [comment]
Hey @raivil, you should be able to create an initializer with:

```ruby
PgHero::HomeController.include(SomeConcern)
```

(may also need to incorporate the Rails reloader for it to work in development)

I don't think it's common enough to officially support.
