### ISSUE TITLE
Health endpoint

### ISSUE THREAD

**Issue by kwent** [ankane/pghero#336]
Hi,

Would be nice to have a healtcheck endpoint especially useful in a container environment to make sure application is loaded and healthy. ( We could use `/` but when behind auth, it does not work ) and `/health` or `/healthz` is a better convention.

Regards

**Comment by ankane** [comment]
Good idea. Added on master. Will go out with the next release: https://github.com/pghero/pghero/commit/5440157827a3fbc3c807d5b797a34955a278f215
