### ISSUE TITLE
PgHero ignoring GiST index when building suggestions?

### ISSUE THREAD

**Issue by pvande** [ankane/pghero#337]
Postgres Version: 11
PgHero Version: 2.7.1 (Docker)

![image](https://user-images.githubusercontent.com/2350/92611898-21771c80-f26e-11ea-9932-565acadd4d79.png)

A minor annoyance, but PgHero is suggesting I create a new index for a column already covered by a dedicated GiST index (and a composite index, which is also valid for the query).  Explaining the query also shows that the planner is actually _using_ the dedicated GiST index; this leads me to conclude that PgHero is coming to this recommendation from its own analysis, and may not be considering the GiST index.

(Worth nothing is that the `tree_path` column in this table is of type `ltree`, which is treated is [more usefully indexed with GiST](https://www.postgresql.org/docs/9.1/ltree.html#AEN141171).)

**Comment by ankane** [comment]
Hey @pvande, thanks for reporting! I was able to confirm with a test case (https://github.com/ankane/pghero/compare/ltree_index). However, the fix would involve an additional query just to check for that column type, which I don't think makes sense to add right now.

**Comment by pvande** [comment]
Thanks for taking some time to look into this!

I agree that adding a check to test specifically for a type defined by a particular extension would not make sense.  Unfortunately, this does not appear to be an issue that only affects `ltree` columns, nor does it appear to only affect `GiST` indices.  With a few minor modifications to your branch above, I tried 

```
# ActiveRecord::Migration.create_table :users, force: true do |t|
#   t.string :email
#   t.column :path, :ltree
#   t.column :range, :int4range
#   t.index :email, using: :hash
#   t.index :path, using: :gist
#   t.index :range, using: :gist
# end

"SELECT * FROM users WHERE id = 1"
Found Index: {:table=>"users", :columns=>["id"]}
Index Defined As: {:schema=>"public", :table=>"users", :name=>"users_pkey", :columns=>["id"], :using=>"btree", :unique=>true, :primary=>true, :valid=>true, :indexprs=>"", :indpred=>"", :definition=>"CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id)"}
Covering Index: ["id"]
Explanation: Covered by index on (id)

"SELECT * FROM users WHERE path = 'b'"
Found Index: {:table=>"users", :columns=>["path"]}
Index Defined As: {:schema=>"public", :table=>"users", :name=>"index_users_on_path", :columns=>["path"], :using=>"gist", :unique=>false, :primary=>false, :valid=>true, :indexprs=>"", :indpred=>"", :definition=>"CREATE INDEX index_users_on_path ON public.users USING gist (path)"}
Covering Index: (None)
Explanation: (None)

"SELECT * FROM users WHERE range = '[0, 0]'"
Found Index: {:table=>"users", :columns=>["range"]}
Index Defined As: {:schema=>"public", :table=>"users", :name=>"index_users_on_range", :columns=>["range"], :using=>"gist", :unique=>false, :primary=>false, :valid=>true, :indexprs=>"", :indpred=>"", :definition=>"CREATE INDEX index_users_on_range ON public.users USING gist (range)"}
Covering Index: (None)
Explanation: (None)
```

**Comment by ankane** [comment]
Thanks for looking deeper into it. I've fixed the hash index case. Let me think about if it makes sense to consider all gist indexes as covering.

**Comment by ankane** [comment]
Alright, I think it's safe to assume a GiST index will cover if it doesn't have an opclass. The main case I was worried about is in the commit (incorrect covering for `=` query on text column with `gist_trgm_ops` index). Let me know your thoughts.

**Comment by pvande** [comment]
This looks like an improvement, but it still seems a bit patchy.  GIN, BRIN, and SP-GiST indices are all ignored out of hand, and the exceptions seem a bit arbitrary.  That caused me to look a bit further into the documentation myself, and … well, I've definitely learned things!

The first thing I've learned is that most GiST indices do _not_ implicitly support equality tests ([as generalized here](https://www.postgresql.org/docs/13/indexes-types.html)).  There are, however, opfamilies (like `gist_ltree_ops`, `network_ops`, and `range_ops`) that _do_ support equality tests.

The second thing that I've learned is that this is all information [available for query](https://www.postgresql.org/docs/8.1/indexes-opclass.html).

``` sql
SELECT
  am.amname AS index_type,
  opf.opfname AS op_family,
  op.oprkind AS op_kind,
  op.oprname AS operator,
  amoplefttype::regtype AS left_type,
  amoprighttype::regtype AS right_type,
  amoppurpose AS purpose
FROM
  pg_am am,
  pg_amop amop,
  pg_opfamily opf,
  pg_operator op
WHERE
  opf.opfmethod = am.oid AND
  amop.amopfamily = opf.oid AND
  amop.amopopr = op.oid
ORDER BY
  index_method,
  op_family,
  op_kind,
  left_type,
  right_type
;
```

On the one hand, properly utilizing this information would require a great deal of type inference on the query itself.  On the other hand, with the appropriate opclasses for the index, along with the index type, and the operators being used, you could *probably* get away without comparing type information at all (if you assume that the query is valid; I'm not sure I've thought this through completely, however).

``` sql
SELECT
  schemaname AS schema,
  t.relname AS table,
  ix.relname AS name,
  ARRAY(
    SELECT opcname
    FROM UNNEST(i.indclass) x(a)
    INNER JOIN pg_opclass ON (x.a = pg_opclass.oid)
  ) AS op_classes,
FROM pg_index i
INNER JOIN pg_class t ON t.oid = i.indrelid
INNER JOIN pg_class ix ON ix.oid = i.indexrelid
WHERE schemaname IS NOT NULL
ORDER BY 1, 2
;
```

Actually checking the opclasses to validate the coverage of an index seems like it addresses your concerns _vis a vis_ not recommending `gist_trgm_ops`, while also identifying when existing non-B-tree indices already exist.  But please, check my math — this is definitely an area of Postgres I'm new to!

**Comment by ankane** [comment]
The current code assumes a GiST indexes without an opclass in their definition support basic operations (=, >, >=, etc), but not sure if that's a good assumption.

Feel free to submit a PR if there are simple things we can do to improve.

**Comment by pvande** [comment]
According to what I've seen from the Postgres docs (and contrary to what I would have naïvely believed), that assumption is probably not valid.

I'll take a stab at a PR.
