### ISSUE TITLE
PGHero cannot find pg_stat_statements -> likely because it's installed in another schema than `public`

### ISSUE THREAD

**Issue by NielsKSchjoedt** [ankane/pghero#338]
Is there any way to specify the schema in which pg_stat_statements is installed?

When you, as me, have a database with many schemas, extensions are often installed in a separate "shared" schema, in my case that is called `extensions`.

**Comment by ankane** [comment]
Hey @NielsKSchjoedt, PgHero doesn't specify a schema, so just make sure the schema is in the search path for the PgHero user.

**Comment by NielsKSchjoedt** [comment]
Thanks for the reply. I added `&schema_search_path=public,extensions` to the database connection URL. While this seems to work, I an now getting a different error:

```
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR: column "queryid" does not exist LINE 1: ...ry_stats AS ( SELECT LEFT(query, 10000) AS query, queryid AS... ^ HINT: Perhaps you meant to reference the column "pg_stat_statements.query".
```

Any thoughts?

**Comment by ankane** [comment]
Check out https://stackoverflow.com/questions/45610833/queryid-column-missing-in-pg-stat-statements-table

**Comment by ankane** [comment]
Cleaning up issues
