### ISSUE TITLE
SQL auto-indent and syntax highlighting

### ISSUE THREAD

**Issue by seanlinsley** [ankane/pghero#34]
It would be nice if SQL queries were automatically indented, and had SQL syntax highlighting applied, so they're easier to identify.

What it currently looks like: (note the first query is a raw string in our app, which is why it's indented)

<img width="773" alt="screen shot 2015-09-08 at 11 56 12 am 1" src="https://cloud.githubusercontent.com/assets/688886/9741775/e4653f04-5621-11e5-97e5-cbe40a4ee18a.png">

I'd be happy to implement this, if you think it's a worthwhile change @ankane

**Comment by ankane** [comment]
Thanks for the proposal Sean.  I personally find it easier to identify queries if they're in the format they were passed to the database.

**Comment by seanlinsley** [comment]
I don't understand; you'd prefer to have 200+ character SQL strings wrap over multiple lines instead of having them broken onto multiple lines with syntax highlighting? Could you help me understand your reasoning?

Even if you wouldn't use the features, do you think there's room in this gem for them?

**Comment by ankane** [comment]
While there are better ways to determine the origin of a query, you can easily tell the first query came from a raw string in your app.  You lose this ability if the format is changed.

**Comment by seanlinsley** [comment]
There could be a button to switch between the raw and formatted version, and / or this could be an optional feature.
