### ISSUE TITLE
pghero > 2.5.1 not working with PostgreSQL 13

### ISSUE THREAD

**Issue by bb** [ankane/pghero#341]
Hi Andrew,

thanks for creating pghero!

I just upgraded PostgreSQL from 11.9 to 13.0. Now pghero version 2.7.2 and master stopped working.

I see the following error:
```
ERROR: column "total_plan_time" does not exist LINE 1: ... query, queryid AS query_hash, rolname AS user, ((total_plan... ^
```

Relevant lines from the stack trace using master (version 2.7.2 has exactly the same line numbers):
```
/bundler/gems/pghero-ee2d70bb4eb5/lib/pghero/methods/basic.rb:44 in select_all
/bundler/gems/pghero-ee2d70bb4eb5/lib/pghero/methods/query_stats.rb:248 in current_query_stats
/bundler/gems/pghero-ee2d70bb4eb5/lib/pghero/methods/query_stats.rb:5 in query_stats
/bundler/gems/pghero-ee2d70bb4eb5/app/controllers/pg_hero/home_controller.rb:58 in index
```

The postgres version given by `select version()` is
`PostgreSQL 13.0 (Ubuntu 13.0-1.pgdg16.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit`. I upgraded via Ubuntu's `pg_upgradecluster`. Extension `pg_stat_statements` is installed.

Rolling back pghero to **version 2.5.1 has no issue** with this PostgreSQL version.

Any idea?

**Comment by ankane** [comment]
Try updating the pg_stat_statements extension:

```sql
ALTER EXTENSION pg_stat_statements UPDATE;
```

**Comment by bb** [comment]
Thanks for the quick reply. Now it works with both master and 2.7.2.

Sorry for the noise.

**Comment by ankane** [comment]
No worries, I imagine many people upgrading will run into this. I may switch PgHero to use the version from `pg_stat_statements` instead of the Postgres version (in [a branch](https://github.com/ankane/pghero/compare/pg_stat_statements_version) for now).

**Comment by bb** [comment]
Sounds like a plan. A hint in the changelog or readme or UI might be another option. Because why would I want to stay on an old extension version unknowingly?

**Comment by ankane** [comment]
> Because why would I want to stay on an old extension version unknowingly?

Yeah, that's my hesitation in merging it. For now, I've added a note the query stats docs (85e6bd00e2e2dfb01340da5769ccb0b4e056a85c) and updated the title of this issue. Also created [a branch](https://github.com/ankane/pghero/compare/pg_stat_statements_update) with a friendly error message about updating.

**Comment by bb** [comment]
LGTM 👍
I'd prefer the pg_stat_statements_update branch over the silently working one.
