### ISSUE TITLE
Syntax error when using Sqlite3 as query stats Database

### ISSUE THREAD

**Issue by leduytung** [ankane/pghero#342]
Hi guys,
I have trouble when using Sqlite3 as another Database to store query stats.
After setup and migrate, the rake bin/rake pghero:capture_query_stats is pass.
But when I start docker, I see the error **ActiveRecord::StatementInvalid (SQLite3::SQLException: near "(": syntax error)**,
from **lib/pghero/methods/basic.rb:44:in `select_all'**

I tried with another PGHERO_STATS_DATABASE_URL using Postgres endpoint, and it's work!
Is there any missing case when query working with Sqlite3?
Thanks!

**Comment by ankane** [comment]
Hey @leduytung, PgHero requires Postgres for the stats database. It could use other data stores as well, but I don't think it's a common enough need to support.

**Comment by leduytung** [comment]
Thank for your response, I will try with Postgres
