### ISSUE TITLE
[Question] Permissions required for explain

### ISSUE THREAD

**Issue by mscrivo** [ankane/pghero#343]
Hi,

I apologize for this question ahead of time, but have not been able to find any info on it, and have not gotten a response on StackOverflow, so I'm asking here and hopefully it's useful to others as well.

With PgHero setup according to the [permissions guide](https://github.com/ankane/pghero/blob/master/guides/Permissions.md), is it possible to augment the permissions to allow the pghero user to run explains? or does it have to be a superuser?

Thanks

**Comment by ankane** [comment]
Hey @mscrivo, the PgHero user is just a normal database user, so you can assign privileges the same way you would with other database users.

**Comment by mscrivo** [comment]
Thanks @ankane .. so it's just a matter of granting select/execute permissions for the pghero user? Thought it was more complex than that. My apologies.

**Comment by mscrivo** [comment]
Yeah that's all that was need ... closing the issue, thanks!
