### ISSUE TITLE
[Enhancement] Some data modification operations wedge pghero for the duration of their execution.

### ISSUE THREAD

**Issue by fake-name** [ankane/pghero#344]
Basically, I'm fiddling with my database structure, and have some queries that modify table structure running (currently, at least a `ALTER INDEX <nnn> SET TABLESPACE <mmm>` on a several hundred GB index.

From what I can tell, this acquires an exclusive lock on some of the metadata tables pghero also uses. This means that trying to browse to the pghero web interface blocks for the duration of the query. If you are running table modification queries that take many hours, this can basically mean pghero is inaccessible for the duration.

It seems like it'd be nice to explicitly specify query timeouts in the queries pghero executes, and handle failures in a manner that at least means you get some indication that pghero is running and alive, rather then just resulting in a HTTP timeout.

**Comment by ankane** [comment]
Hey @fake-name, sorry for the delay. Which query was timing out?

For timeouts, you should be able to set statement and lock timeouts on the database user that PgHero uses.

**Comment by fake-name** [comment]
I'm not sure which query, exactly, since some DDL can basically block everything, so I can't introspect running queries (because doing so blocks!)

**Comment by ankane** [comment]
If you set a lock timeout on the PgHero database user, it should show up in the exception backtrace.

**Comment by ankane** [comment]
Cleaning up issues, but let me know if you figure out where it's locking
