### ISSUE TITLE
Enabling System Stats not possible if `gcp_database_id` contains numeric characters

### ISSUE THREAD

**Issue by lisolu** [ankane/pghero#345]
Postgres Version: 11
PgHero Version: 2.7.2 (Docker)

When trying to enable System stats for Google Cloud SQL in our PGhero deployment, it would always fail with

```
Completed 500 Internal Server Error in 380ms (Allocations: 105862)

PgHero::Error (Invalid database id):
...
```
Our database id is sth. like `my-project:postgres11-xyz`, i.e. it contains numeric characters.

After looking at the source code I am pretty sure the following line causes this error:
lib/pghero/methods/system.rb (line 147)
```
raise Error, "Invalid database id" unless gcp_database_id =~ /\A[a-z\-:]+\z/i
```

Would it be possible to just add `0-9` to the regex, i.e 
```
raise Error, "Invalid database id" unless gcp_database_id =~ /\A[a-z0-9\-:]+\z/i
```
and allow alpha-numeric database ids?

**Comment by ankane** [comment]
Hey @lisolu, makes sense to me. Fixed on master.

**Comment by Yinabled** [comment]
@ankane It seems like this issue wasn't resolved with b63d0b0 - at least on my end, it seems as if a `gcp_database_id` with numeric characters (e.g. `abcd-efgh-1234:abcde`) still leads to an "Invalid database id" error, whereas one without numeric characters does not. it's a bit puzzling since the regex seems correct - any ideas?

**Comment by lisolu** [comment]
I ran into the same issue when upgrading right before the holidays and then completely forgot about it...I had a look at the image (tag v2.7.3) and it seems that - despite the tag - it still uses pghero-2.7.2, i.e. in /app/Gemfile.lock you have
```
...
pghero (2.7.2)
      activerecord (>= 5)
...
```
and pghero-2.7.2 under /usr/local/bundle/gems/.

**Comment by Yinabled** [comment]
Got it - @lisolu did you manage to resolve the issue somehow, or is the only option to wait for a new release that uses pghero-2.7.3+?

**Comment by ankane** [comment]
Hey @Yinabled and @lisolu, nice catch. I just pushed an updated version to the `pghero:latest` Docker image (and the Linux package should finish building shortly).
