### ISSUE TITLE
Question : Mount as a Individual Ruby app

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/pghero#347]
Can we mount this as a individual Ruby application without using the docker image. I mean just by using the Ruby gem and mount on plain rails app ?

**Comment by ankane** [comment]
Hey @bheemreddy181, for Rails apps, there are instructions in the docs. For non-Rails Ruby apps, you can use the Ruby API (also in the docs), but would need to build your own dashboard.

**Comment by bheemreddy181** [comment]
@ankane the question was rather than building a standalone PGHero using a docker image can we build it as a stand-alone Ruby app using PGHero gem and use the same level of configuration used on the docker config

**Comment by ankane** [comment]
The docs have instructions for 3 ways to install PgHero and only one involves Docker. Check out the Contributing Guide for where to get additional help.
