### ISSUE TITLE
showing more than 1 day of data?

### ISSUE THREAD

**Issue by jackdempsey** [ankane/pghero#350]
Hey Kane! 

We just brought PgHero into Fin and are loving it. Thanks for all the hard work on this over the years. 

QQ: I could have sworn we used to be able to see multiple days of data, maybe up to 2 weeks back, on queries. We're just seeing the past 24 hrs though, even though there's more in the db. 

We noticed this https://github.com/ankane/pghero/blob/3fb8945ed2d72331bac227c6a272db1ecc2be2d4/app/assets/javascripts/pghero/application.js#L25 

Did something change to only show the last day or can we configure things to look further back?

thanks!

**Comment by ankane** [comment]
Hey, great to hear. Query stats have always been 24 hours (system stats can go back 2 weeks, and links for query stats will work as long as the records aren't deleted). I'm not sure I want to add an option for it right now, but you can probably fork the gem and change that line.

**Comment by jackdempsey** [comment]
Ok great, thanks!
