### ISSUE TITLE
[Question] : Are these true duplicate indexes 

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/pghero#354]
Hey Ankane, 

Question on duplicate indexes

![Screen Shot 2021-01-21 at 4 00 32 PM](https://user-images.githubusercontent.com/3464623/105417913-eb757c00-5c01-11eb-8535-25c630efd209.png)

`index_accounting.activities_on_source_id (source_id)` and `index_accounting_activities_on_source_id_covering (source_id, accounting_date, activity_type_id, payment_id, activity_id)` are these really a true duplicate set ?

the second index is created with several other variables, primary index still gives us a better read compared to the second one. I want to hear your thoughts on this?

**Comment by ankane** [comment]
Hey @bheemreddy181, for most apps, I don't think it'll make a difference, but I'd go with what you're seeing over the general advice PgHero gives.

**Comment by bheemreddy181** [comment]
Can we create a category duplicate indexes and true duplicate indexes - do you think that will add value?

**Comment by ankane** [comment]
I don't think it'd would for most applications, so wouldn't want to add.

**Comment by bheemreddy181** [comment]
Sounds good then thanks for sharing your thoughts on this.
