### ISSUE TITLE
[Question] : Slow queries list does not update immediately 

### ISSUE THREAD

**Issue by abhishek77in** [ankane/pghero#358]
Hi,

After I have identified and fixed the slow query, the query still appears in the slow query list, causing some confusion. Is it possible to have it reflect immediately.

Thanks!

**Comment by bheemreddy181** [comment]
Can we make that time more configurable?

**Comment by ankane** [comment]
I don't think there's significant benefit from adding an option.

**Comment by abhishek77in** [comment]
I fixed a slow query like a month ago. It still shows up, only the avg. query time goes down.

<img width="824" alt="PgHero___Overview" src="https://user-images.githubusercontent.com/749134/106708069-4b175280-6618-11eb-832a-1c7f18dbd2a6.png">

**Comment by ankane** [comment]
They default threshold is 20 ms. You can customize this in `pghero.yml` ([relevant docs for Rails](https://github.com/ankane/pghero/blob/master/guides/Rails.md#customization--multiple-databases)).

**Comment by abhishek77in** [comment]
As per the info text I am looking at **"Slow queries take 20 ms or more on average and have been called at least 100 times."**
If it possible to look at slow queries in a particular time frame, like last 3 days, right now it shows for the lifetime.

Some of the queries showing up in the list are not relevant anymore as I have change my query technique. 

Attaching the image to give you more content:
<img width="776" alt="PgHero___Overview" src="https://user-images.githubusercontent.com/749134/107616913-ecd01c80-6c74-11eb-9686-908a2882904b.png">

**Comment by ankane** [comment]
Hey @abhishek77in, please see my comment above. It looks at the last three hours, not lifetime, and there's an option to customize the threshold if you need it.

**Comment by abhishek77in** [comment]
Hey @ankane for some reason I don't think it's showing data for queries run in last 3 hours as the call count is stying the same (OR I am missing something obvious here). I will dig in further to get a better understanding. Thanks again for your reply.

**Comment by ankane** [comment]
My bad, it looks like it'll show lifetime if you're not using historical query stats. You'll need to enable them to see the last 3 hours.

**Comment by abhishek77in** [comment]
Thanks for clarifying. I think we can close this issue now. @ankane

**Comment by abhishek77in** [comment]
@ankane Heroku scheduler lets me run the job every 10mins with a very simple setup. Can I run `rake pghero:capture_query_stats` this every 10 mins instead of 5 mins. I am guessing the answer is yes, but just making sure.

Also, where would the slow queries for last 3 hours appear, on the queries page or on the overview page?

**Comment by abhishek77in** [comment]
My slow queries section under overview is showing only 1 query. Thanks a ton for making the gem, it's a life saver.
