### ISSUE TITLE
[Idea] Write stats to multiple databases separately

### ISSUE THREAD

**Issue by charlie-wasp** [ankane/pghero#360]
At the moment, all stats for multiple databases are written to the primary one, and there is no way to change this behavior (please, correct me here if I am wrong). I have a case when I would like to write each database stats separately.

I have a Rails engine with a dedicated database, and it will become a standalone service eventually. And when it happens, it will have its own PgHero dashboard with no data because it was left in the primary db.

Do you consider introducing a config option to support writing stats to different databases? I could work on the implementation.

**Comment by bheemreddy181** [comment]
+1

**Comment by ankane** [comment]
Hey @charlie-wasp, thanks for the suggestion and offer to help. However, I don't think it's worth the extra complexity.

For the specific case above, you should be able to use a tool like [pgsync](https://github.com/ankane/pgsync) to move the historical data when it becomes a standalone service.

**Comment by charlie-wasp** [comment]
Got it! Thanks for the quick reply
