### ISSUE TITLE
[Question] : Mask PII from Live Queires

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/pghero#361]
Is there a way we can mask PII from Live Queries ?

**Comment by ankane** [comment]
Hey @bheemreddy181, there's an experimental `filter_data` option for this - https://github.com/ankane/pghero/pull/291. You can set `filter_data: true` in `pghero.yml` or set the `PGHERO_FILTER_DATA=1` environment variable.

**Comment by bheemreddy181** [comment]
How does this filer data work ? i still see data in the queries 
<img width="867" alt="Screen Shot 2021-02-10 at 8 17 20 AM" src="https://user-images.githubusercontent.com/3464623/107521709-7fd75c80-6b78-11eb-897f-867355444fec.png">

**Comment by bheemreddy181** [comment]
Here is a query which masks all the PII for the pg_stats table, if you want I will try creating a PR

```
SELECT datid,datname,pid,usesysid,usename,application_name,client_addr,client_hostname,client_port,backend_start,xact_start,query_start,state_change,wait_event_type,wait_event,state,backend_xid,backend_xmin,
    regexp_replace(regexp_replace(regexp_replace(regexp_replace(
    regexp_replace(regexp_replace(regexp_replace(regexp_replace(
    lower(query),
    '\s+',                          ' ',           'g'   ),
    $$\\'$$,                        '',            'g'   ),
    $$'[^']*'$$,                    $$''$$,        'g'   ),
    $$''('')+$$,                    $$''$$,        'g'   ),
    '=\s*NULL',                     '=0',          'g'   ),
    '([^a-z_$-])-?([0-9]+)',        '\1'||'0',     'g'   ),
    '([^a-z_$-])0x[0-9a-f]{1,10}',  '\1'||'0x',    'g'   ),
    'in\s*\([''0x,\s]*\)',          'in (...)',    'g'   ) AS query,
backend_type
FROM pg_stat_activity;
```

**Comment by ankane** [comment]
From the screenshot, it looks like the option isn't enabled. Also make sure you're on version 2.5.0 or greater.

**Comment by bheemreddy181** [comment]
I have the `PGHERO_FILTER_DATA=1` as an environment variable

**Comment by ankane** [comment]
I'd try forking and debugging to see what's going on.

**Comment by bheemreddy181** [comment]
Ah cool , looks like the env variable didn't take effect I added the pghero.yml variable which seems to be working now. Thanks for this :-)
