### ISSUE TITLE
[Suggestion] : Killing queries as an option for pghero

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/pghero#365]
Hi Ankane,

I really appreciate how many various open-source tools you provide for a wider audience around the world. Thanks a ton.

I want to hear your thoughts on making the KILL long-running queries ( typical KILL button ) as an option using a flag and hiding the button in the UI if that value is set. As we try to push this tool out, we see people fearing to see those KILL buttons on the UI.

Want to hear your thoughts on this?

**Comment by ankane** [comment]
Hey @bheemreddy181, sounds good. Feel free to submit a PR.

**Comment by bheemreddy181** [comment]
@ankane Can i get a review for the PR ?
