### ISSUE TITLE
Mastodon unused indices error: Remove them with a migration for faster writes

### ISSUE THREAD

**Issue by LETRA** [ankane/pghero#368]
Hi, Could you be a little more specific with this? There are some instructions to fix an unused indices error and it advises "Remove them with a migration for faster writes". And then the line: "rails generate migration remove_unused_indexes". But that line cannot be run in cli. I tried to find a solution but could not. Many novice users surely have the same problem. Thank you for any help.

**Comment by ankane** [comment]
Hey @LETRA, it may make sense for Mastodon to set `Pghero.show_migrations = false` to remove those instructions if users aren't working with Rails directly. If Mastodon manages the database, there probably isn't anything for users to do (it's a relatively minor notice).
