### ISSUE TITLE
The reset no longer works after upgrading db to 12 and using pg_stat_statements_reset(userid, dbid, queryid)

### ISSUE THREAD

**Issue by stedliu** [ankane/pghero#373]
Hi,

Before creating an issue, please check out the Contributing Guide:

https://github.com/ankane/pghero/blob/master/CONTRIBUTING.md

Thanks!

**Comment by stedliu** [comment]
My setup:
I am running version 281 of pghero, the most recent one. The database version is Postgresql 12.2 and pg_stat_statements extension is 1.7. 

I have implemented a dedicated pghero user/role and used the new version of pghero.pg_stat_statements_reset function as below.

-- improved query stats reset for Postgres 12+ - delete for earlier versions
CREATE OR REPLACE FUNCTION pghero.pg_stat_statements_reset(userid oid, dbid oid, queryid bigint) RETURNS void AS
$$
  SELECT public.pg_stat_statements_reset(userid, dbid, queryid);
$$ LANGUAGE sql VOLATILE SECURITY DEFINER;

The pg_stat_statements_reset(userid, dbid, queryid) is working fine via psql or pgadmin as the pghero user.

The issue:
When I clicked on Reset button in the Queries tab, it did nothing. When I switched back to the old version of function spec, the Reset button works, which removes the whole thing.
-- query stats reset
CREATE OR REPLACE FUNCTION pghero.pg_stat_statements_reset() RETURNS void AS
$$
  SELECT public.pg_stat_statements_reset();
$$ LANGUAGE sql VOLATILE SECURITY DEFINER;

**Comment by ankane** [comment]
Hey @stedliu, you'll still need the version without any arguments, since that's what PgHero currently uses. The version with arguments was added to the docs since it'll be the default for PgHero 3 (to save some users the time of going back and adding it later).

**Comment by stedliu** [comment]
Hi Andrew,

Thank you very much for your clarification.

Ted
