### ISSUE TITLE
FrozenError in PgHero::HomeController#index

### ISSUE THREAD

**Issue by brettdawkins** [ankane/pghero#374]
New Rails6 app with a remote data source using PG

Im getting FrozenError in PgHero::HomeController#index

Not sure if this is a bug, or just an oversight myside. 

Any help appreciated

**Comment by ankane** [comment]
Hey @brettdawkins, can you paste the full stack trace?

**Comment by brettdawkins** [comment]
Here goes (password, host and db masked)

    FrozenError in PgHero::HomeController#index
    can't modify frozen Hash: {:adapter=>"postgresql", :pool=>5, :username=>"rails", :password=>"X", :timeout=>5000, :database=>"x", :host=>"x", :port=>5432}
    Extracted source (around line #80):
    78            url = "#{url}#{url.include?("?") ? "&" : "?"}connect_timeout=5" unless url.include?("connect_timeout=")
    79          when Hash
    80            url[:connect_timeout] ||= 5
    81          end
    82          establish_connection url if url
    83        end

    Rails.root: /home/x/x
    Application Trace | Framework Trace | Full Trace
    pghero (2.3.0) lib/pghero/database.rb:80:in `block in connection_model'
    pghero (2.3.0) lib/pghero/database.rb:72:in `initialize'
    pghero (2.3.0) lib/pghero/database.rb:72:in `new'
    pghero (2.3.0) lib/pghero/database.rb:72:in `connection_model'
    pghero (2.3.0) lib/pghero/methods/basic.rb:79:in `connection'
    pghero (2.3.0) lib/pghero/methods/basic.rb:36:in `select_all'
    pghero (2.3.0) lib/pghero/methods/query_stats.rb:43:in `query_stats_readable?'
    pghero (2.3.0) lib/pghero/methods/query_stats.rb:35:in `query_stats_enabled?'
    pghero (2.3.0) app/controllers/pg_hero/home_controller.rb:346:in `set_query_stats_enabled'
    activesupport (6.1.3.1) lib/active_support/callbacks.rb:427:in `block in make_lambda'
    activesupport (6.1.3.1) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
    actionpack (6.1.3.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
    activesupport (6.1.3.1) lib/active_support/callbacks.rb:199:in `block in halting'
    activesupport (6.1.3.1) lib/active_support/callbacks.rb:512:in `block in invoke_before'
    activesupport (6.1.3.1) lib/active_support/callbacks.rb:512:in `each'
    activesupport (6.1.3.1) lib/active_support/callbacks.rb:512:in `invoke_before'
    activesupport (6.1.3.1) lib/active_support/callbacks.rb:115:in `block in run_callbacks'
    actiontext (6.1.3.1) lib/action_text/rendering.rb:20:in `with_renderer'
    actiontext (6.1.3.1) lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
    activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `instance_exec'
    activesupport (6.1.3.1) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
    activesupport (6.1.3.1) lib/active_support/callbacks.rb:137:in `run_callbacks'
    actionpack (6.1.3.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
    actionpack (6.1.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
    actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
    activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `block in instrument'
    activesupport (6.1.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    activesupport (6.1.3.1) lib/active_support/notifications.rb:203:in `instrument'
    actionpack (6.1.3.1) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
    actionpack (6.1.3.1) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
    activerecord (6.1.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
    actionpack (6.1.3.1) lib/abstract_controller/base.rb:165:in `process'
    actionview (6.1.3.1) lib/action_view/rendering.rb:39:in `process'
    actionpack (6.1.3.1) lib/action_controller/metal.rb:190:in `dispatch'
    actionpack (6.1.3.1) lib/action_controller/metal.rb:254:in `dispatch'
    actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
    actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:33:in `serve'
    actionpack (6.1.3.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
    actionpack (6.1.3.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
    actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
    actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
    actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
    actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
    railties (6.1.3.1) lib/rails/engine.rb:539:in `call'
    railties (6.1.3.1) lib/rails/railtie.rb:207:in `public_send'
    railties (6.1.3.1) lib/rails/railtie.rb:207:in `method_missing'
    actionpack (6.1.3.1) lib/action_dispatch/routing/mapper.rb:20:in `block in <class:Constraints>'
    actionpack (6.1.3.1) lib/action_dispatch/routing/mapper.rb:49:in `serve'
    actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
    actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `each'
    actionpack (6.1.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'
    actionpack (6.1.3.1) lib/action_dispatch/routing/route_set.rb:842:in `call'
    rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
    rack (2.2.3) lib/rack/etag.rb:27:in `call'
    rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
    rack (2.2.3) lib/rack/head.rb:12:in `call'
    actionpack (6.1.3.1) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
    actionpack (6.1.3.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
    rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
    rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
    actionpack (6.1.3.1) lib/action_dispatch/middleware/cookies.rb:689:in `call'
    activerecord (6.1.3.1) lib/active_record/migration.rb:601:in `call'
    actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
    activesupport (6.1.3.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
    actionpack (6.1.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
    actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
    actionpack (6.1.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
    actionpack (6.1.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
    web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
    web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
    web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
    web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
    actionpack (6.1.3.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
    railties (6.1.3.1) lib/rails/rack/logger.rb:37:in `call_app'
    railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `block in call'
    activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
    activesupp
ort (6.1.3.1) lib/active_support/tagged_logging.rb:37:in `tagged'
    activesupport (6.1.3.1) lib/active_support/tagged_logging.rb:99:in `tagged'
    railties (6.1.3.1) lib/rails/rack/logger.rb:26:in `call'
    sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
    actionpack (6.1.3.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
    actionpack (6.1.3.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
    rack (2.2.3) lib/rack/method_override.rb:24:in `call'
    rack (2.2.3) lib/rack/runtime.rb:22:in `call'
    activesupport (6.1.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
    actionpack (6.1.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
    actionpack (6.1.3.1) lib/action_dispatch/middleware/static.rb:24:in `call'
    rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
    actionpack (6.1.3.1) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
    rack-mini-profiler (2.3.1) lib/mini_profiler/profiler.rb:373:in `call'
    webpacker (5.2.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
    rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
    railties (6.1.3.1) lib/rails/engine.rb:539:in `call'
    puma (5.2.2) lib/puma/configuration.rb:248:in `call'
    puma (5.2.2) lib/puma/request.rb:76:in `block in handle_request'
    puma (5.2.2) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
    puma (5.2.2) lib/puma/request.rb:75:in `handle_request'
    puma (5.2.2) lib/puma/server.rb:431:in `process_client'
    puma (5.2.2) lib/puma/thread_pool.rb:145:in `block in spawn_thread'

**Comment by brettdawkins** [comment]
Sorry, hectic day at the office. My bad also, the issue was a bit odd, I had installed the gem, 2.8.0, then 

    PG::UndefinedColumn: ERROR: column "total_plan_time" does not exist LINE 1: ... query, queryid AS query_hash, rolname AS user, ((total_plan..

Tried ALTER EXTENSION pg_stat_statements UPDATE; command to upgrade but I can see version 1.8 - and still no luck the column is missing still. Running postgres 13.2

I then tried to downgrade versions (sequentially) of the gem, but then ran into the FrozenError. 

I've also seen in github repo - https://github.com/postgres/postgres/blob/master/contrib/pg_stat_statements - reference to ALTER EXTENSION pg_stat_statements UPDATE TO '1.9'
 but this returns 

    extension "pg_stat_statements" has no update path from version "1.8" to version "1.9"

I dont have a column total_plan_time at all

**Comment by petrprikryl** [comment]
Make sure you are running the `ALTER EXTENSION pg_stat_statements UPDATE;` on the right database (`DATABASE_URL`). I was facing the same error.

**Comment by brettdawkins** [comment]
Bingo. Cant see the wood through the trees. Totally overlooked that this was database specific. Did the job perfecto Petr!

**Comment by ankane** [comment]
Thanks @petrprikryl!
