### ISSUE TITLE
Scaling pg_hero?

### ISSUE THREAD

**Issue by joshuabaird** [ankane/pghero#375]
This is more of a general question than an issue - my apologies if this is the wrong place for that.

I'm considering running a multi-tenant Rails-engine based deployment of pg_hero to monitor 150+ databases.  With adequate compute resources and horizontal scaling (this will be running on ECS/k8s so we can run multiple replicas), will this be an issue performance wise?

One potential issue that I can see is the UI/UX for displaying multiple databases could be improved.  With such a large number of databases, the left hand column of the pg_hero UI could be very long.  We are considering replacing this UI with a filterable drop-down box.

Any suggestions/feedback would be appreciated!

**Comment by ankane** [comment]
Hey @joshuabaird, PgHero only looks at one database at a time, so don't think there should be any performance issues. The database selector UI isn't something I'd like to change right now, but an autocomplete/dropdown menu makes sense for that many DBs. Feel free to share what you come up with.

**Comment by joshuabaird** [comment]
@ankane Thanks!  Would you be open to a PR that improves the database selector UI?

**Comment by ankane** [comment]
It's not something I'd like to change right now, so there's a good chance it wouldn't be merged, but feel free to submit what you come up with.
