### ISSUE TITLE
Support pg_stat_statements 1.8 / postgresql 13

### ISSUE THREAD

**Issue by zeha** [ankane/pghero#376]
Hi,

pg_stat_statements as included in postgresql 13 has renamed/split a few fields, notably `total_time`.

I.e. in pg_stat_statements 1.8 (postgresql 13):
```
 total_plan_time     │ double precision │           │          │         │ plain    │
 total_exec_time     │ double precision │           │          │         │ plain    │
```

Where in pg_stat_statements 1.7 (postgresql 12 and lower):
```
 total_time          │ double precision │           │          │         │ plain    │
```

I am not sure how to support this in pghero without breaking backwards compatibility...

Please consider supporting 1.8/13 :-) 

Thanks,
Chris

**Comment by ankane** [comment]
Hey @zeha, PgHero already supports this (try upgrading if you're seeing errors).

**Comment by zeha** [comment]
Hi @ankane. Thanks for the very timely reply. It appears I locally broke the docker image update process - when I thought I was running the latest version, in fact I was using some older build. Works as expected after properly updating.

Thank you for making & maintaining pghero!

**Comment by maxsumrall** [comment]
> Hi @ankane. Thanks for the very timely reply. It appears I locally broke the docker image update process - when I thought I was running the latest version, in fact I was using some older build. Works as expected after properly updating.
> 
> Thank you for making & maintaining pghero!

Can you share what issues you ran into to properly update? I'm also having some issues "properly updating" to the latest docker image and can't seem to figure out why I still get this error on seemingly the latest docker image

**Comment by zeha** [comment]
> Can you share what issues you ran into to properly update? I'm also having some issues "properly updating" to the latest docker image and can't seem to figure out why I still get this error on seemingly the latest docker image

This setup has a very peculiar way of updating images, so almost none of that will be relevant to you.

It boiled down to: I had *two* images, one named `ankane/pghero:latest` and one `pghero:latest` (which I overlooked). And while I thought `ankane/pghero:latest` was being updated, the other, outdated, image actually ran.

**Comment by maxsumrall** [comment]
Ah ha, thanks. It seems like upgrading to PG 13 required an extra step to make query stats work, with an error that in passing looked like the same one you posted originally. This FAQ item had the answer: 
https://github.com/ankane/pghero/blob/master/guides/Query-Stats.md#error-column-total_plan_time--queryid-does-not-exist


ALTER EXTENSION pg_stat_statements UPDATE;
