### ISSUE TITLE
Provide a homebrew formula

### ISSUE THREAD

**Issue by nheeren** [ankane/pghero#38]
PgHero looks awesome. Is there any chance to make it available on OS X for noobs like me, e.g. by means of a [homebrew formula](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md)?

**Comment by thotmx** [comment]
Is this useful for you?
https://github.com/bmorton/pghero_solo

**Comment by ankane** [comment]
Interesting idea @nheeren. Someone is welcome to do this, but going to close as outside the scope of the gem.
