### ISSUE TITLE
[Idea] More customization points

### ISSUE THREAD

**Issue by andyatkinson** [ankane/pghero#380]
To adopt pghero at work, we are looking at hiding the "Kill All Connections" button, and on the Explain screen, the Analyze and Visualize buttons. Using the template approach, I made options for those and was thinking to reference them in the ERB templates. I added those options to the template generator with values of true, but commented out. On our template, I added the options and set the values to false. Confirmed the intended things are hidden. Added a PR: https://github.com/ankane/pghero/pull/379

Thoughts?

**Comment by ankane** [comment]
Future readers: see #379
