### ISSUE TITLE
Query stats unavailable on RDS

### ISSUE THREAD

**Issue by culov** [ankane/pghero#382]
Hello,

Thank you for this great gem, I've been having some trouble getting the query stats piece to work. I've followed [the instructions](https://github.com/ankane/pghero/blob/master/guides/Query-Stats.md) to enable query stats on RDS.

However, when I visit the dashboard (I've restarted the database a couple times), I continue to see the HTML block indicating that I need to enable `pg_stat_statements` before it can work. 
![image](https://user-images.githubusercontent.com/170303/121264239-b9408000-c86b-11eb-9e80-31c45c0417e7.png)

When I run the query below directly in psql, it returns a count of 1, indicating that `pg_stat_statements` is enable

```SELECT COUNT(*) AS count FROM pg_available_extensions WHERE name = 'pg_stat_statements';```

I've hit a wall trying to tease out why the gem doesn't recognize the extension in the RDS database, and was hoping someone might have hints on where to look next.

Thank you!

**Comment by ankane** [comment]
Hey @culov, from the error message, it looks like `pg_stat_statements` is missing from `shared_preload_libraries`. Be sure the update it in the parameter group for your database instance and restart the database instance after it's applied. Check out the Contributing Guide for where to get additional help.
