### ISSUE TITLE
Error when pulling docker image from docker hub

### ISSUE THREAD

**Issue by ganeshan** [ankane/pghero#383]
docker pull ankane/pghero

reports the following error:
====================
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/ankane/pghero/manifests/sha256:292ed571a0d76dd2a023f383cccb6ba59a7b7c336433c8e9502010ca1f1b4294: unexpected EOF

**Comment by ankane** [comment]
Hey @ganeshan, that seems like it could be a network issue.

**Comment by ganeshan** [comment]
Thanks @ankane , you are correct. I tried it on another machine, and it downloaded fine.
