### ISSUE TITLE
Explain issue (PG::UnableToSend: server closed the connection unexpectedly)

### ISSUE THREAD

**Issue by AlekseiSaff** [ankane/pghero#388]
Hi,

facing the weird issue with explain functionality. PGHero gives an error
"PG::UnableToSend: server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request."

Not sure how to debug this explain analyze from psql or pgadmin works well

Alex

**Comment by ankane** [comment]
Hey @AlekseiSaff, unfortunately, I'm not sure how to reproduce. Could something external be canceling long running transactions (since PgHero runs explain inside a transaction)?
