### ISSUE TITLE
why are all SELECT queries slow queries in pghero?

### ISSUE THREAD

**Issue by encryptblockr** [ankane/pghero#395]
Why is it that this query always show up as slow query in pghero?

```
SELECT * from users WHERE enabled=True
```

this simple query that completes in milliseconds ALWAYS show up in pghero as slow live queries/long running queries..WHY is this? and what can one do to fix this?

The query is not long running and is not slow..it complete in like 300 milliseconds or so..even with returning 4000 rows at that

**Comment by ankane** [comment]
Hey @encryptblockr, you can customize the thresholds with `slow_query_ms` and `slow_query_calls` ([Docker docs](https://github.com/ankane/pghero/blob/master/guides/Docker.md#customization--multiple-databases)). The default is 20 ms and 100 calls.
