### ISSUE TITLE
Run pghero under different folder

### ISSUE THREAD

**Issue by dchimeno** [ankane/pghero#398]
The default docs says about running pghero under / in nginx like:

```bash
server {
  listen          80;
  server_name     "";
  location / {
    proxy_pass    http://localhost:3001;
  }
}
````

I would like it to serve under a different folder, says /pghero/, so I could serve other apps under the same domain.

```bash
server {
  listen          80;
  server_name     "";
  location /pghero/ {
    proxy_pass    http://localhost:3001/;
  }
}
````

This works for the root page, but not for others like /queries.

Is it possible to pass a variable to pghero to make it serving under a subfolder?

I've tried ROOT_PATH, but seems that is for another thing.

**Comment by ankane** [comment]
Hey @dchimeno, check out #145.

**Comment by ankane** [comment]
Added to docs.

**Comment by dchimeno** [comment]
This is great, thanks a lot.
