### ISSUE TITLE
Question: What does it mean a blank connection name?

### ISSUE THREAD

**Issue by leoplct** [ankane/pghero#405]
If I go to /pghero/connections

I got this blank group of 4 connections. What does it mean?
![Screenshot 2022-01-06 at 19 56 37](https://user-images.githubusercontent.com/1176145/148436348-f560e8fe-fef6-41df-bf4d-41ec8751787f.png)

**Comment by ankane** [comment]
Hey @leoplct, these are most likely Postgres server processes.

You can check with:

```sql
SELECT backend_type FROM pg_stat_activity WHERE usename IS NULL;
```

Example output

```text
    backend_type     
---------------------
 autovacuum launcher
 background writer
 checkpointer
 walwriter
(4 rows)
```
