### ISSUE TITLE
TypeError (no implicit conversion of nil into String):

### ISSUE THREAD

**Issue by joshuakp** [ankane/pghero#406]
I got this error in the docker logs while trying to run v2.8.2 using postgres 14.1-alpine database.How do I fix it?

TypeError (no implicit conversion of nil into String):

activesupport (6.0.4.4) lib/active_support/security_utils.rb:27:in `digest'
activesupport (6.0.4.4) lib/active_support/security_utils.rb:27:in `secure_compare'
actionpack (6.0.4.4) lib/action_controller/metal/http_authentication.rb:79:in `block in http_basic_authenticate_or_request_with'
actionpack (6.0.4.4) lib/action_controller/metal/http_authentication.rb:99:in `authenticate'
actionpack (6.0.4.4) lib/action_controller/metal/http_authentication.rb:89:in `authenticate_with_http_basic'
actionpack (6.0.4.4) lib/action_controller/metal/http_authentication.rb:85:in `authenticate_or_request_with_http_basic'
actionpack (6.0.4.4) lib/action_controller/metal/http_authentication.rb:78:in `http_basic_authenticate_or_request_with'
actionpack (6.0.4.4) lib/action_controller/metal/http_authentication.rb:73:in `block in http_basic_authenticate_with'
activesupport (6.0.4.4) lib/active_support/callbacks.rb:428:in `instance_exec'
activesupport (6.0.4.4) lib/active_support/callbacks.rb:428:in `block in make_lambda'
activesupport (6.0.4.4) lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
actionpack (6.0.4.4) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (6.0.4.4) lib/active_support/callbacks.rb:201:in `block in halting'
activesupport (6.0.4.4) lib/active_support/callbacks.rb:513:in `block in invoke_before'
activesupport (6.0.4.4) lib/active_support/callbacks.rb:513:in `each'
activesupport (6.0.4.4) lib/active_support/callbacks.rb:513:in `invoke_before'
activesupport (6.0.4.4) lib/active_support/callbacks.rb:134:in `run_callbacks'
actionpack (6.0.4.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.4.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.4.4) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.4.4) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.4.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.4.4) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.4.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.4.4) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.4.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.4.4) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.4.4) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.4.4) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.4.4) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.4.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.4.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.4.4) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
actionpack (6.0.4.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.4.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.4.4) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.4.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.4.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
railties (6.0.4.4) lib/rails/engine.rb:527:in `call'
railties (6.0.4.4) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.4.4) lib/rails/railtie.rb:190:in `method_missing'
actionpack (6.0.4.4) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.4.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.4.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.4.4) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.4.4) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.4.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.4.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/cookies.rb:654:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.4.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.4.4) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.4.4) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.4.4) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.4.4) lib/action_dispatch/middleware/host_authorization.rb:97:in `call'
railties (6.0.4.4) lib/rails/engine.rb:527:in `call'
rack (2.2.3) lib/rack/urlmap.rb:74:in `block in call'
rack (2.2.3) lib/rack/urlmap.rb:58:in `each'
rack (2.2.3) lib/rack/urlmap.rb:58:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

**Comment by ankane** [comment]
Hey @joshuakp, it looks like `PGHERO_PASSWORD` is set without `PGHERO_USERNAME`.
