### ISSUE TITLE
Docs or strategy clarification request: Active Record and PG version compatibility

### ISSUE THREAD

**Issue by andyatkinson** [ankane/pghero#407]
Hello,

I'm wondering if you think it's worth clarifying the runtime Rails (Active Record) version compatibility matrix with PgHero? And with PostgreSQL versions?

It seems tag `v2.8.2` depends on Rails 5 or newer, and then `master` branch has upgraded to Rails/AR 7. I have a few questions: Is there a hard requirement on something in version 7 for newer PgHero? Could that be relaxed to Version 6 potentially? Will there be a AR 6 compatible released version?

Will some changes be back-ported to the 2.8.x world / AR version 5+ of PgHero? The main app I work on is Rails 5 at the moment. Looks like 5.2 is end of life June 2022. https://endoflife.date/rails and 6.0 is June 2023 so it would be nice to support those for a while.

Or alternatively I know there is a Docker version of PgHero. Does it need a "host" app and if so, would or could that be the strategy for older versions? E.g. we're running Rails 5 and PG 13. If we wanted to run latest PgHero - we could have a small generated host Rails 7 app for PgHero in a container and configured to utilize the PG 13 database?

Currently though we bundle PgHero 2.8.2 with the main Rails app and deploy it that way. Something like:

| PgHero      | Active Record | PostgreSQL |
| ----------- | ----------- | ----------- |
| v2.8.2      | 5.0+       | ? | 
| ? (master)   | 7.0+        | ? |

Thanks!

**Comment by andyatkinson** [comment]
Hi @ankane - LMK what you think. Thank you for taking a look.

**Comment by ankane** [comment]
Hey @andyatkinson, PgHero currently supports Active Record 5.0+ (even on master - see gemspec and CI). The current plan is to drop support for Active Record < 5.2 with PgHero 3, but not sure when that'll be.

**Comment by andyatkinson** [comment]
Oof, I thought I saw `spec.add_dependency "activerecord", ">= 7.0"` but maybe was looking at a different gem? Ok great.  My confusion. Our main app is on Rails 5 and I'm looking to add some features to out fork. For now anyway it's good to know that we can continue to pull in the main branch changes from upstream.

**Comment by andyatkinson** [comment]
The original purpose of this was built on a bad assumption so I'm closing this issue.
