### ISSUE TITLE
system redirect to localhost:3001 after adding second or more databases in pghero.yml

### ISSUE THREAD

**Issue by steven792** [ankane/pghero#409]
After fixing install for debian as current docs fail for release 10 and gpg, I find all working with nginx proxying port 80 to 3001 however after adding multiple databases in pghero.yml the system will do a redirect to http://localhost:3001/(first db name)  rather than a redirect to the $host causing issues.    example:  pghero.mydomain.com  redirects on the host to  http://localhost:3001/pghero    (assuming phhero.yml has the first databases: entry as pghero:) the documentation has no reference to this behavior and I'm having issue finding where to correct this. Other than creating a edge redirect (which hasn't worked yet) I'd like to fix this behavior on the origin itself so it might redirect to the $host rather than localhost.

**Comment by ankane** [comment]
Hey @steven792, try adding `proxy_set_header X-Forwarded-Host $host;` to the nginx config.
