### ISSUE TITLE
[Idea] Dynamic inject config in cloud run

### ISSUE THREAD

**Issue by marcusricardoaguiar** [ankane/pghero#422]
Instead of have to rebuild the image whenever we need to update `pghero.yml`, we could inject the cloud run config data as a secret and use it to deploy the pghero tool.

**Comment by marcusricardoaguiar** [comment]
Using GCP Secrets we can mount a volume and load a file config:
```
       volume_mounts {
          name = "pghero-configmap"
          mount_path = "/app/config/pghero.yml"
        }
```
If we have the possibility to define the environment var with the config path it would solve it. :)

**Comment by ankane** [comment]
Hey @marcusricardoaguiar, thanks for the suggestion. I don't fully understand the details of how this might work from the description, but you can set the location of the config file with the `PGHERO_CONFIG_PATH` environment variable.
