### ISSUE TITLE
PgHero needs a documented shutdown command

### ISSUE THREAD

**Issue by DanRStevens** [ankane/pghero#423]
It took me a day to figure out PgHero can be shutdown with:
```
sudo pghero scale web=0
```

Previously I had resorted to using `kill` to try and terminate it, but it kept coming back with new process ids, and was restarted after a system reboot.

Actually, it's not really clear to me why it needs to be a system service. Would seem reasonable to run it from a terminal without `sudo`, and then just Ctrl+C it when done using it.

**Comment by ankane** [comment]
Hey @DanRStevens, stopping the service is documented in the [Management](https://github.com/ankane/pghero/blob/master/guides/Linux.md#management) section.

**Comment by DanRStevens** [comment]
Might also help to mention it when running the app without arguments. It mentions most other commands there, but not `stop`. It's pretty easy to miss the Management section of the documentation.

> Usage:
>   pghero run COMMAND [options]
>   pghero scale TYPE=NUM
>   pghero logs [--tail|-n NUMBER]
>   pghero config:get VAR
>   pghero config:set VAR=VALUE
>   pghero config:unset VAR
>   pghero configure
>   pghero reconfigure
>   pghero restart
> 
> Details:
>   pghero configure [-f FILE|-]
>     * If using an installer:
>       This command will launch the installer wizard.
>       You can pass the installer seed file as argument or on STDIN.
>    * Without installer:
>       This will execute the configure script at /opt/pghero/packaging/scripts/configure (if any).
>       A file containing environment variables can be given as argument or on STDIN (-f -), and will be saved in the /etc/pghero/conf.d folder.
> 
>   pghero reconfigure
>     This command allows to reconfigure the application. Only useful if using an installer.
> 
>   pghero restart [process]
>     This will restart the application (or the given process), in a distribution-independent manner.
