### ISSUE TITLE
filter_data error

### ISSUE THREAD

**Issue by luizm** [ankane/pghero#429]
Hi there

I'm using the latest version of pghero, and I'm facing a weird error when I enable `filter_data: true` in the config file.. Any guesses why? it will help me a lot to debug it

Thank you in advance 

log
```
ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
    474:     <p>Slow queries take <%= @database.slow_query_ms %> ms or more on average and have been called at least <%= @database.slow_query_calls %> times.</p>
    475:     <p><%= link_to "Explain queries", explain_path %> to see where to add indexes.</p>
    476:
    477:     <%= render partial: "queries_table", locals: {queries: @slow_queries} %>
    478:   </div>
    479: <% end %>
    480:
```

**Comment by ankane** [comment]
Hey @luizm, I'm not sure how to reproduce. Can you paste the complete stack trace? Also, how is PgHero installed (Docker, Linux, Rails)?
