### ISSUE TITLE
Supports Postgres Query Plan Visualization

### ISSUE THREAD

**Issue by hey-jude** [ankane/pghero#43]
Postgres Query Plan Visualization
https://github.com/AlexTatiyants/pev
http://tatiyants.com/postgres-query-plan-visualization/
It's awesome.

**Comment by seanlinsley** [comment]
:+1: this would be great to have

**Comment by ankane** [comment]
Looks awesome. Would need to add it in a way that it doesn't introduce additional dependencies. Feel free to submit a PR for it.

**Comment by seanlinsley** [comment]
I've started working on this, but I'm having trouble building the Node app so that pghero can bundle it.

https://github.com/AlexTatiyants/pev/issues/16

**Comment by ankane** [comment]
Cleaning up issues. Feel free to create a PR once this is in a good place.

**Comment by seanlinsley** [comment]
I would argue against closing tickets that have activity, but as a fellow OSS maintainer I realize you don't owe me any of your time ¯\\\_(ツ)\_/¯

**Comment by ankane** [comment]
Hey @seanlinsley, this doesn't have anything to do with my time - just trying to stay organized. I'll reopen and mark as help wanted.

**Comment by ankane** [comment]
Master now has a "Visualize" button on the Explain page that gives output to paste into the Postgres Explain Visualizer. I think this is a good medium between no integration and full integration.

Commit here: https://github.com/ankane/pghero/commit/2bd34ad8e2c032631197a7cd50eb198f733eb6dc
