### ISSUE TITLE
Change the default clean_query_stats time

### ISSUE THREAD

**Issue by rkelleyrtp** [ankane/pghero#432]
Greetings,

We have pghero running on Debian 11 and noticed the "clean_query_stats" function seems to be hard-coded to 14 days (found in the query_stats.rb file).  In order to test a different value (eg: 1 day), we modified this file and replaced "14.days.ago" to "1.days.ago", restarted pghero, and re-ran the "clean_query_stats" function again.  However, It seems the DB still had historical stats for 14 days.

How can we set the clean_query_stats with a different value?  We prefer to keep the historical stats for 180 days on our servers.

**Comment by ankane** [comment]
Hey @rkelleyrtp, made this configurable in the commit above. With the next release, you'll be able to do:

```sh
DAYS=180 rake pghero:capture_query_stats
```

**Comment by rkelleyrtp** [comment]
Awesome, thanks!
