### ISSUE TITLE
Question about historical space stats scheduling

### ISSUE THREAD

**Issue by ibrahima** [ankane/pghero#433]
Hi! I had a question about the historical space stats capture task. I noticed that in the docs it suggests capturing query stats every 5 minutes, but [space stats only once per day day](https://github.com/ankane/pghero/blob/master/guides/Rails.md#historical-space-stats). Is there a specific reason that space stats should be captured less frequently? Is it likely to put more load on the database, or does PgHero expect them at that specific interval? Thanks!

**Comment by ankane** [comment]
Hey @ibrahima, you can capture them at any interval (the dashboard will always show the 7 day change), but once a day should be enough for most applications.

**Comment by ibrahima** [comment]
Ah okay. Makes sense that you wouldn't really need much finer granularity, and it is going to use more space if you sample more often.

Thanks!
