### ISSUE TITLE
Would it make sense to reset historical stats with the reset button?

### ISSUE THREAD

**Issue by ibrahima** [ankane/pghero#434]
Hi! I am playing around with enabling the historical query stats feature. I noticed that with the feature enabled, the "Reset" button doesn't appear to do anything. Is that because the stats are persisted in the DB table now? Would it make sense to call `PgHero.clean_query_stats` in the [reset controller action](https://github.com/ankane/pghero/blob/702fe4ce4eb5e2e0af90a97df24d57b609e71ac3/app/controllers/pg_hero/home_controller.rb#L371) so that the reset button also resets those stats? Or would it make more sense to add a new button for this? I'd be happy to submit a PR because it does worry me a little bit having this feature without having an easy way to reset the stats. Though I'm not sure if it's "rotating" the stats somehow to maintain constant space usage.

Thank you!

**Comment by ankane** [comment]
Hey @ibrahima, the button resets stats for the current period, but agree it's not very intuitive. I've removed it in the commit above when historical stats are enabled since 1. it's much less useful then and 2. I think historical stats are best managed outside the dashboard.
