### ISSUE TITLE
Dockerfile or arm64 docker image

### ISSUE THREAD

**Issue by cfouche3005** [ankane/pghero#436]
Hi, I have recently discovered pghero and i wanted to deploy it on a raspberry pi but the docker image  doesn't have an arm64 version and the dockerfile (and the files associed with like the entrypoint if one is used) is not disponible on the repo.
Can we have the files so we can build the docker image for arm64 ?

**Comment by ankane** [comment]
Hi @cfouche3005, the Dockerfile is here: https://github.com/pghero/pghero
