### ISSUE TITLE
Cleanup of the historical query table

### ISSUE THREAD

**Issue by jasonumiker** [ankane/pghero#44]
Build a mechanism for the pghero_query_stats table to be cleaned up such that records older than a week get purged as new records are imported by the pghero:capture_query_stats or provide a pghero:cleanup_query_stats kind of function to do it.

**Comment by ankane** [comment]
Going to leave this up to application owners to implement for now.

**Comment by tamaloa** [comment]
+1 For adding this feature. Providing a "batteries included" solution as pghero feels like this should be covered.
Our pghero_query_stats tables are slowly growsing into the GBs and I came here really suprised they are not compacted at some point...

**Comment by ohaddahan** [comment]
@ankane 
I would vote for this too.
I implanted this as a scheduled task, should be trivial to have similar logic run before fetching new data.


 ```
 days_back = ENV.fetch('cleanup_days_back',14).to_i
  class PgheroQueryStat < ActiveRecord::Base ; end
  class PgheroSpaceStat < ActiveRecord::Base ; end
  models_names = %w(PgheroSpaceStat PgheroQueryStat)
  models_names.each do |model_name|
    model = Object.const_get model_name
    model.where('captured_at < ?',DateTime.now - days_back.day).in_batches(of: 10000).delete_all
  end
```

**Comment by seanlinsley** [comment]
I'd generally agree that this should be built into Pghero. Since we already have to run scheduled jobs for `PgHero.capture_space_stats` and `PgHero.capture_query_stats`, why not update those method definitions to automatically prune historical data?
