### ISSUE TITLE
Missing Rubygems Release

### ISSUE THREAD

**Issue by plribeiro3000** [ankane/pghero#449]
I can see that issue #447 was solved by commit b30aeb6b32357e9666717b272e699c321f5b1e6a and there is a tag for version `3.3.1` but there is not such version on rubygems.

**Comment by ankane** [comment]
Hey @plribeiro3000, 3.3.1 [isn't released yet](https://github.com/ankane/pghero/blob/8ef8569cb9944e3eccf8b90a8ddb0470358f9fff/CHANGELOG.md) and there isn't a tag.
