### ISSUE TITLE
Undo enabling query stats

### ISSUE THREAD

**Issue by netinstructions** [ankane/pghero#45]
I tried to enable query stats from the dashboard, but after clicking the button got a 500 server error. I checked the logs and saw `ERROR:  pg_stat_statements must be loaded via shared_preload_libraries`. I decided I don't want to troubleshoot the issue as outlined in the help guide and would rather just turn off query stats.

The problem is I have no idea how to do this. The server replies with a 500 internal server error. I can't access the dashboard at all. I tried uninstalling and re-installing pghero to no avail. Where's the undo button?

**Comment by netinstructions** [comment]
I figured it out. I had to run `DROP EXTENSION pg_stat_statements;` _on the table it was created on_. I was not running it on the correct table, hence the confusion.

An undo button performing this operation would be friendlier than a 500 internal server error though :)

**Comment by ankane** [comment]
Thanks for following up @netinstructions. Feel free to submit a pull request for this.

**Comment by pathikrit** [comment]
@netinstructions : I have the same problem. Where did you find the logs?
