### ISSUE TITLE
Is it possible to list schemas (tables and columns) of a database

### ISSUE THREAD

**Issue by karan2801** [ankane/pghero#454]
Hi,

Before creating an issue, please check out the Contributing Guide:

https://github.com/ankane/pghero/blob/master/CONTRIBUTING.md

Thanks!

**Comment by ankane** [comment]
Hi @karan2801, PgHero's focus is on performance, so you'll want to use another tool to browse the schema.

**Comment by karan2801** [comment]
Thanks @ankane for the clarification.
