### ISSUE TITLE
packager.io broken?

### ISSUE THREAD

**Issue by crmc88** [ankane/pghero#457]
Hello Awesome phhero folks,

I seem to be having an issue install pghero on RHEL 8.5 via the linux method in the readme. 

`https://dl.packager.io/srv/pghero/pghero/master/installer/el/8.5.repo`

Errors out with `Can't detect distribution based on given input: "el/8.5"`

I can manually edit the URL to

`https://dl.packager.io/srv/pghero/pghero/master/installer/el/8.repo`

Then I just end up with timeouts when I attempt to dnf/yum install. Checking into the repo file generated I can manually try to browse to `https://dl.packager.io/srv/rpm/pghero/pghero/master/el/8/x86_64/` where I am greeted by an error `[packager.io] 404 - Resource not found.`

I dont think this has to do with your repo as much as whatever build system is running in packager.io and I am not sure what the best method is to let someone know.

Cheers!

**Comment by ankane** [comment]
Hi @crmc88, there's not a package for RHEL 8 (only 7).
