### ISSUE TITLE
[Idea] Collapse partitions of a partitioned table

### ISSUE THREAD

**Issue by dymk** [ankane/pghero#458]
pghero's "Space" page can become cluttered when a database contains many partitions of a table, using [native declarative table partitioning](https://www.postgresql.org/docs/current/ddl-partitioning.html). I would suggest, by default, that partitions be "rolled up" into a single row consisting of the parent virtual table, with the option to expand it. 

My current issue: I've got a table sharded into 64 partitions. Interestingly enough, the parent table isn't listed, but all the individual partitions are. This clutters up the page quite a bit, and makes it hard to compare them against non-partitioned tables.

Something like a clickable row, titled with the parent table name and summed space consumed by partitions, which expands down into its partitions, is what I'm imagining this could look like.

**Comment by ankane** [comment]
See https://github.com/ankane/pghero/pull/459#issuecomment-1555355019
