### ISSUE TITLE
Systemd Support

### ISSUE THREAD

**Issue by psyonara** [ankane/pghero#46]
When I try to start pghero on Ubuntu 15.10, it gives me this error:
```
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
```
This is evidently because Ubuntu has switched from upstart to systemd in the latest versions. Is there any chance of adding support for systemd? Or is there another way that I can run pghero without installing upstart?

**Comment by ankane** [comment]
Unfortunately, packager.io doesn't currently have support for Ubuntu 15.10. cc @crohr

**Comment by crohr** [comment]
@psyonara you can bypass the init scripts that ship with the package (just don't `pghero scale`). Then any process can be run in the foreground with `pghero run [PROCESS]`, e.g. `pghero run web`. You can use this in your own init scripts if needed.
