### ISSUE TITLE
Expose an indicator based `stddev_exec_time` for too much query variation

### ISSUE THREAD

**Issue by benoittgt** [ankane/pghero#460]
Hello,

It is good to show that we have queries that take lot's of time, but we should show a basic indicator of query "health" based on `stddev_exec_time`. Sometimes, it's a 95% or even 99% that destroy the average response time.

The percentile [is not available yet ](https://www.postgresql.org/message-id/CA%2Br4MrRSiHzXSQj0E8XyLgMYSbusiBQNADFjsO-sQgmGxXwMoQ%40mail.gmail.com). I saw that [some people use `stddev_exec_time` to express it
](https://youtu.be/sou_z-YCzrw?t=331) but it means the we have a normal distribution in our queries execution time which is not the case.

I think we could show a basic hint based on `(stddev_exec_time/mean_exec_time) > 0.3`

> Additionally, if we look at the coefficient of variation column, which is the ratio between the standard deviation and the mean (also called the coefficient of variation), we get 0.612 which is fairly high. In general, if this ratio is above 0.3 then the variation of your data is quite large. Since we find the data is quite varied, it seems to imply that instead of a few outliers skewing the mean, there are a number of execution times taking longer than they should. This provides further confirmation that the execution time for this query should be investigated further.
([source](https://www.timescale.com/blog/identify-postgresql-performance-bottlenecks-with-pg_stat_statements/))

**Comment by benoittgt** [comment]
I think the tooltip could even be base on `stddev_exec_time` then display max and min exec time for a query.

**Comment by ankane** [comment]
Hi @benoittgt, thanks for the suggestion and links! I'm not sure this will be significantly helpful / actionable for most applications, so I'm not sure it's a good fit for PgHero.
