### ISSUE TITLE
Filter System queries and Non-System(User Defined) Queries for Slow queries with markers in code

### ISSUE THREAD

**Issue by priyadarshiniguptan** [ankane/pghero#464]
I am looking at identifying slow queries on my database for only queries created on user defined schemas. is there any specific configuration that needs to be set to ignore Postgres inbuilt schemas such as public, pg_catalog, information_schema and so on? 

Also please let me know how I can put in markers like comments in our user defined queries and if PgHero can identify these and isolate them from system queries.

**Comment by ankane** [comment]
Hi @priyadarshiniguptan, PgHero doesn't have this functionality (and it's not something I'd like to add/support), but you could fork and add it for your application.
