### ISSUE TITLE
Show version details on the overview page

### ISSUE THREAD

**Issue by rkelleyrtp** [ankane/pghero#466]
Hi,

Is it possible to add some versioning info and link to the Github repo on the main page?  We are running a couple of PGHero installs and can't easily identify which version of PGHero is installed and running.  As a bonus, it would be helpful to see a link to the upgrade doc on the same page.

These three options will help us easily keep our PGHero installs up-to-date.

Thank you!

**Comment by ankane** [comment]
Hi @rkelleyrtp, thanks for the suggestion, but I think it'll be noise to most users and not something I'd like to add.
