### ISSUE TITLE
Unable to get query stats

### ISSUE THREAD

**Issue by coder2000** [ankane/pghero#467]
Hey Andrew,

Thanks for all of your hard work on all of your gems, I use a lot of them. Currently I am having issues getting the slow query stats on an app. The database is running in docker, I am running a custom configuration file, I have tried updating the settings through migrations with no errors. The dashboard still says that it needs to be enabled, as the app is using the default superuser I would assume I could just click the button but it gives me an error too. Is there something I am missing or you can help me with?

Thanks

**Comment by ankane** [comment]
Hi @coder2000, check out [this guide](https://github.com/ankane/pghero/blob/master/guides/Query-Stats.md) for enabling query stats.

**Comment by coder2000** [comment]
I did.
