### ISSUE TITLE
How to hide/disable reset option in queries while using docker setup?

### ISSUE THREAD

**Issue by raybittuiq** [ankane/pghero#469]
I was thinking to disable the reset option for users in the queries section, but I could not find anything.
I am using docker setup and I would like to have this option from either environment variable or some other parameters.

**Comment by ankane** [comment]
Hi @raybittuiq, there isn't an option for this (as it shouldn't be an issue in most cases). However, if you enable historical query stats, it'll remove the button from the UI (but doesn't disable the endpoint currently).
