### ISSUE TITLE
multiple database on single machine

### ISSUE THREAD

**Issue by techsachin1** [ankane/pghero#472]
1)i am installing pghero 1st time. i have 80+ postgres database on single machine. when i did 
databases:
  database1:
    url: postgres://username:password@hostaddress/database1
  database2:
    url: postgres://username:password@hostaddress/database2    this set up . its shows multiple database name on connection tag.

2) i dont have rails applications, using pghero for java appliation only. how i can manage this multiple database and pghero.yml file where i have to place if i am running pghero in docker compose file. my docker compose is  

version: "3.7"
services:
  pghero:
    image: ankane/pghero
    container_name: pghero
    network_mode: host
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://user:password@hostaddress:5432
    volumes:
      - /home/username/pghero/pghero.yml:/app/config/pghero.yml

**Comment by ankane** [comment]
Hi @techsachin1, check out the Contributing Guide for where to get help.

**Comment by techsachin1** [comment]
hi have checked but didnt get exact. plz share deatils

**Comment by sp1rs** [comment]
@techsachin1 please check [here](https://github.com/ankane/pghero/blob/b9cb2045cbc304a007bf00ae056d6bb4e0336d13/guides/Rails.md?plain=1#L206)
