### ISSUE TITLE
[Idea] arm64 Docker arch support

### ISSUE THREAD

**Issue by mjgorman** [ankane/pghero#473]
Hello,

We're in the process of migrating our kubernetes infrastructure to Graviton on AWS. Would be great to have arm64 docker architecture supported for this effort. I didn't see a Dockerfile anywhere in the repo or any docker build related items here to create a PR for other wise i would have attempted to contribute that way.

**Comment by ankane** [comment]
Hi @mjgorman, just pushed an image for `linux/arm64` to the `latest` tag.

Ref: https://github.com/pghero/pghero/commit/89584d31d1749e50d20072889f20b50267a58464

**Comment by mjgorman** [comment]
Thank you!
