### ISSUE TITLE
Multi-architecture images for tags other than `latest`

### ISSUE THREAD

**Issue by philipahlberg** [ankane/pghero#482]
Currently the [`ankane/pghero:latest`](https://hub.docker.com/r/ankane/pghero/tags) tag is marked as multi-architecture, while individual versions (e.g. [v3.3.4](https://hub.docker.com/layers/ankane/pghero/v3.3.4/images/sha256-69a1b96fcd9da839537632fc08f2cccc20e421cdbbe59e86794094626a7617af?context=explore)) are not. This means that if you want to use `pghero` across multiple architectures, you're forced to use `:latest` since every other tag is architecture-specific.

Would it be possible to mark versions as multi-architecture as well? I assume they exist already since it works for `:latest`. I would make a PR to suggest a fix, but it doesn't seem to be handled in CI, so I'm not sure how images are built and tagged.

**Comment by ankane** [comment]
Hi @philipahlberg, this change was made after the last version release (#473) and will be part of the next one.

**Comment by philipahlberg** [comment]
Awesome, thanks! Are you planning a release soon by any chance?
