### ISSUE TITLE
GCP Cloud SQL System Stats not enable.

### ISSUE THREAD

**Issue by ginoliang1130** [ankane/pghero#486]
Hi,

I'd like to inquire about something related to system stats. In the error message of pghero, I found:

```
Started GET "/connection_stats?duration=86400&period=600" for [ip-address] at 2023-12-21 09:36:37 +0000
Processing by PgHero::HomeController#connection_stats as */*
  Parameters: {"duration"=>"86400", "period"=>"600"}
Completed 500 Internal Server Error in 87ms (ActiveRecord: 34.8ms | Allocations: 11177)
  
PgHero::NotEnabled (System stats not enabled):
```

My environment is GCP Cloud SQL. I'm quite certain that the corresponding permissions are set correctly.
Uncertain about which part of the process the issue lies, I'd like to inquire if anyone has faced a similar problem.

Thanks.

**Comment by ankane** [comment]
Hi @ginoliang1130, if you're seeing that error after enabling in the config (and the System tab is showing up), there's likely an old process running where it's not enabled.
