### ISSUE TITLE
[Bug] Getting error "wrong constant name" in development

### ISSUE THREAD

**Issue by PikachuEXE** [ankane/pghero#49]
This bug sometimes happens after I visit pghero page in development
Restarting the app seems to solve it

I want to know why and see if anything can be done to solve it permanently

![screen shot 2016-02-26 at 11 18 39 am](https://cloud.githubusercontent.com/assets/1018543/13342283/00fb17bc-dc7b-11e5-8f37-d47a01b129a0.png)

**Comment by jnylen** [comment]
Same here.

**Comment by ankane** [comment]
This is due to the fact that PgHero creates a dynamic class and stores it as an instance variable to manage the PgHero database connections. Not sure how to accomplish this off the top of my head, but happy to accept a PR.

**Comment by ankane** [comment]
This small change fixed the error for me. Let me know if anyone still sees it on master.
