### ISSUE TITLE
[Idea] Live queries parameters 

### ISSUE THREAD

**Issue by talski** [ankane/pghero#495]
Hello, I've noticed that live queries doesn't show query parameters, but in the postgres log, the line right after the query, comes a "DETAIL:  parameters" with all the params used in the query.

It would be nice to know those params, so I could analyze the query .

**Comment by ankane** [comment]
Hi @talski, the data on the Live Queries page comes from [pg_stat_activity](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-ACTIVITY-VIEW), which doesn't include the parameters.
