### ISSUE TITLE
`undefined method 'symbolize_keys'` when running on Rails' main branch

### ISSUE THREAD

**Issue by luizkowalski** [ankane/pghero#500]
hey

I'm getting this error when running `PgHero.capture_query_stats` with Rails main:

```
NoMethodError: undefined method `symbolize_keys' for an instance of ActiveRecord::Result::IndexedRow

(app):1:in `<top (required)>': undefined method `symbolize_keys' for an instance of ActiveRecord::Result::IndexedRow (NoMethodError)

indexed_rows.each(&block)
```

I guess it has something to do with [this commit](https://github.com/rails/rails/commit/10dfdc5eb16f416db6cf01e5b13c2cf2c505b95d).

I will dig a bit more when I get some time

**Comment by ankane** [comment]
Hi @luizkowalski, unreleased versions of Active Record aren't supported, but pushed a fix in the commit above.

**Comment by luizkowalski** [comment]
Thanks, @ankane, much appreciated!
