### ISSUE TITLE
GCP stats not working anymore

### ISSUE THREAD

**Issue by thomasLeclaire** [ankane/pghero#501]
Hi,

It sounds like the api calls to GCP monitoring are not working anymore. 
when trying to display the related views, the calls get a 500 error return code

<img width="567" alt="image" src="https://github.com/ankane/pghero/assets/43581346/b1ba0162-a5e6-412c-a834-fa030f629e90">

<img width="890" alt="image" src="https://github.com/ankane/pghero/assets/43581346/6935abe0-68b9-43f3-8562-2dea97a24f8e">

It was well working during years, but don't know exactly when it started to be broken.. tested the last 2 pghero version and same behavior. 
Also tested to update all the google gems to last version but same error. 

And to confirm, I tested some local curl on the running pod to ensure not authent or network subject, but no these ones are ok. 

thx for help

**Comment by ankane** [comment]
Hi @thomasLeclaire, `Google::Apis::ClientError (Invalid request):` typically means an issue with your GCP permissions.
