### ISSUE TITLE
 PgHero.capture_space_stats fails with "No unique index found for #{name_or_columns}"

### ISSUE THREAD

**Issue by thisIsLoading** [ankane/pghero#503]
Hi,

i was trying to capture space stats but this fails with:

```
irb(main):001> PgHero.capture_space_stats
   (358.5ms)  SELECT n.nspname AS schema, c.relname AS relation, CASE c.relkind WHEN 'r' THEN 'table' WHEN 'm' then 'matview' ELSE 'index' END AS type, pg_table_size(c.oid) AS size_bytes FROM pg_class c LEFT JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname NOT IN ('pg_catalog', 'information_schema') AND n.nspname !~ '^pg_toast' AND c.relkind IN ('r', 'm', 'i') ORDER BY pg_table_size(c.oid) DESC, 2 ASC /*pghero*/
ArgumentError: No unique index found for id

(irb):1:in `<main>': No unique index found for id (ArgumentError)

          raise ArgumentError, "No unique index found for #{name_or_columns}"
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
irb(main):002> 
```

pghero is install via

`gem 'pghero', github: 'ankane/pghero'`

i could imagine that the error might be related to the fact that i am using timescaldb hypertables (which dont have an ID column)?

is there a way to still get those stats?

thanks

**Comment by ankane** [comment]
Hi @thisIsLoading, I'm not really sure how to reproduce the error (the method works fine if I remove the `id` column from `pghero_space_stats`), but in general, using a hypertable to store space stats isn't supported.

**Comment by ankane** [comment]
I'm able to reproduce the error if I delete the `pghero_space_stats` table, so I think that's the actual issue.

**Comment by luizkowalski** [comment]
I see the same error using the pghero from GitHub/main. The database is Fly.io's Postgres

**Comment by alexeevit** [comment]
Just ran into the same issue, but it seems to be a Rails bug (at least Rails 7.1.1, that's my case).

The ActiveRecord `insert_all` method tries to select the unique columns before inserting. So [here](https://github.com/rails/rails/blob/v7.1.1/activerecord/lib/active_record/insert_all.rb#L152) it first uses the model's primary keys (if no other provided) and [here](https://github.com/rails/rails/blob/v7.1.1/activerecord/lib/active_record/insert_all.rb#L158) checks if the selected columns are primary keys. And for some reason the last check fails.

In the first case, it uses the method `model.primary_key`, that returns `id`. But then in the second method it uses `connection.schema_cache.primary_keys(model.table_name)` that returns `nil`.

I checked some other models in my project and both methods returned equal values. How comes that the `pghero_query_stats` is different?
