### ISSUE TITLE
Unique index is marked as duplicate index

### ISSUE THREAD

**Issue by rgmvisser** [ankane/pghero#508]
I have a table with columns `id`, `tenantId`, `name`, `userId`. I have two indexes:
- Normal index on `tenantId`
- Unique index on `tenantId`,`userId`

PGHero now tells me that this is a duplicate index, but from my understanding, this is not true as the unique index on is used when providing both `tenantId` and `userId`?

Could this be a bug or do I maybe miss something here?

**Comment by ankane** [comment]
Hi @rgmvisser, it's saying that you don't need the normal index.

**Comment by rgmvisser** [comment]
Hi @ankane but I also need the normal index as I am also querying just on `tenantId`. 

I am a bit confused as it says it's a duplicate index, but the indexes don't overlap?

**Comment by ankane** [comment]
Postgres can use the multicolumn (unique) index for querying just on `tenantId` since it's the leading column.

**Comment by rgmvisser** [comment]
Ooh interesting, I thought for unique multicolumns it was not able to use the leading column. Good to know!
