### ISSUE TITLE
Auto-create Jira tickets for issues identified by HgHero

### ISSUE THREAD

**Issue by leifericf** [ankane/pghero#510]
I'm wondering whether anyone has successfully integrated HgHero with Jira.

If so, what approach did you use?

The idea is to automatically create Jira tickets for issues uncovered by PgHero. From there, want to pipe the Jira tickets into a dedicated Slack channel as well, to alert people of database issues requiring attention.

If PgHero offers an API (does it?), I suppose it would be relatively straightforward to write an integration.

**Comment by ankane** [comment]
Hi @leifericf, I haven't heard of anyone doing this, but PgHero has a [Ruby API](https://github.com/ankane/pghero/blob/master/guides/Rails.md#methods) you could probably use.
