### ISSUE TITLE
Multi PostgreSQL instances

### ISSUE THREAD

**Issue by pbobrovnikov** [ankane/pghero#55]
Hi,
PGhero supports multi-connections?
Example,
sudo pghero config:set DATABASE_URL=postgres://user:password@hostname1:5432/dbname
sudo pghero config:set DATABASE_URL=postgres://user:password@hostname2:5432/dbname

if not, whether it is possible to make ?

**Comment by sudhirj** [comment]
The process is described here - you need to update a YAML file in the config directory. 

https://github.com/ankane/pghero/blob/master/guides/Rails.md#multiple-databases

If you want to use only ENV variables, I suppose you could use some ERB in the YAML file to output the configurations dynamically.

**Comment by benortiz** [comment]
Hi @sudhirj,

I'm trying to set this up so that the `pghero_query_stats` is on a local postgres db, but all the analysis happens on a remote postgres db. How can I use this configuration information to set it up like this?

**Comment by sudhirj** [comment]
As far as I know, I don't think that's possible. Just to be clear you do have pg_stats enabled on the remote database, but you want to store historical stats for that remote database on your local DB?

**Comment by benortiz** [comment]
That's correct. Local DB being another server. Thank you, I figured as much. I'm kind of at a loss for what to do because I don't want to be adding too many extra tables to our production DB to be monitoring/running analytics. 

Thanks for your help @sudhirj !

**Comment by sudhirj** [comment]
I'd say leave out the historical stats. I run a bunch of fairly large databases, and unless you have some specialized reason to keep track of what performance history was, you're usually more interested in the present and the future than the past. 

Also, `pg_stats` itself stores info in a bunch of tables anyway (PgHero reads these tables to give you the info it does) so I don't think the history tables are going to add that much overhead compared to what you already have.

**Comment by benortiz** [comment]
@sudhirj thanks for the advice, I super appreciate it. I'll follow your strategy going forward.

**Comment by benortiz** [comment]
Actually, @sudhirj, I just noticed in the [Rails Installation docs](https://github.com/ankane/pghero/blob/master/guides/Rails.md#historical-query-stats) there does seem to be a way:

![pghero 2016-03-31 14-35-23](https://cloud.githubusercontent.com/assets/681189/14191654/ec17a96c-f74d-11e5-9970-4b57f8bec35d.png)

**Comment by sudhirj** [comment]
Oh, nice. See if that works and close the issue if it does?

**Comment by arcturial** [comment]
Since the answer provided was for the rails installation, is this also possible for the standalone Linux installation? How would you accomplish this?

**Comment by ankane** [comment]
@arcturial for standalone installation, you can use:

```sh
sudo pghero config:set PGHERO_STATS_DATABASE_URL=postgres://...
```
