### ISSUE TITLE
Apache proxy error

### ISSUE THREAD

**Issue by lpossamai** [ankane/pghero#63]
Hi there,

I've installed pghero in a Centos 6.7, following the docs.

Also, I'm using Apache as web server.

httpd.conf:
```
NameVirtualHost *:80

<VirtualHost *:80>
ProxyPreserveHost On
ProxyPass / http://localhost:6000/
ProxyPassReverse / http://localhost:6000/

DocumentRoot / 
ServerName 10.208.7.32
</VirtualHost>
```

When I open the browser to connect into pghero, I got the following error:

```
(70007)The timeout specified has expired: proxy: error reading status line from remote server localhost
 proxy: Error reading from remote server returned by /
```

```
[root@localhost]# curl -v http://localhost:6000/
* About to connect() to localhost port 6000 (#0)
*   Trying ::1... Connection refused
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 6000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: localhost:6000
> Accept: */*

```

Do you guys have any idea about how can I solve that one? 
Cheers

**Comment by ankane** [comment]
Hey @lpossamai, does `curl -v http://localhost:6000/` return a response?

**Comment by lpossamai** [comment]
@ankane I already posted the return of the command `curl -v http://localhost:6000/`...

however, this issue is old and it's already solved. I don't remember what I did though
