### ISSUE TITLE
Wrong suggested index

### ISSUE THREAD

**Issue by lpossamai** [ankane/pghero#64]
Hi there,

I've installed pghero into my DB server, to get some additional information about it.

Pghero is showing me that I should create an index, that already exists.

`CREATE INDEX CONCURRENTLY ON ja_customers (clientid)`

I've got this index in my DB:
`CREATE INDEX ix_clientid_customers ON ja_customers ("clientid");`

The query that is presented to me, is this one:
`SELECT id, name_first, name_last, company FROM ja_customers WHERE  clientid=? AND deleted = ?  ORDER BY company, name_last, name_first ASC`

If I run it using explain, I can see the query hitting the index.

Why is pghero showing me that index, if it already exists?

Cheers
Lucas

<img width="741" alt="screen shot 2016-05-26 at 9 40 45 am" src="https://cloud.githubusercontent.com/assets/17607576/15557294/632532c8-2326-11e6-9688-96da62b53ff2.png">

**Comment by ankane** [comment]
Can you run the following in a `psql` console and paste the output?

```sql
\d+ ix_clientid_customers
```

**Comment by lpossamai** [comment]
Sure..


 ```
\d+ ix_clientid_customers
   Index "public.ix_clientid_customers"
  Column  |  Type  | Definition | Storage 
----------+--------+------------+---------
 clientid | bigint | "clientid" | plain
btree, for table "public.ja_customers"
```

**Comment by ankane** [comment]
Give master a shot.

**Comment by lpossamai** [comment]
Sorry @ankane - But I've used yum to install pghero into my server...

Can I edit those files manually? If so, can you please give me the path?

cheers

**Comment by ankane** [comment]
Sorry @lpossamai, just saw this. Will be pushing out a new package in a bit.
