### ISSUE TITLE
500 on pghero dashboard when query stats enabled

### ISSUE THREAD

**Issue by tomymehdi** [ankane/pghero#65]
After running
```
PgHero.disable_query_stats
```
the dashboard works okey

After running
```
PgHero.enable_query_stats 
```
the dasboard give the following error

```
NoMethodError: undefined method `[]' for nil:NilClass
- 157 non-project frames 
1
File "/app/vendor/bundle/ruby/2.1.0/gems/pghero-1.2.4/lib/pghero/methods/suggested_indexes.rb" line 121 in block (2 levels) in best_index_helper
2
File "/app/vendor/bundle/ruby/2.1.0/gems/pghero-1.2.4/lib/pghero/methods/suggested_indexes.rb" line 121 in map
3
File "/app/vendor/bundle/ruby/2.1.0/gems/pghero-1.2.4/lib/pghero/methods/suggested_indexes.rb" line 121 in block in best_index_helper
4
File "/app/vendor/bundle/ruby/2.1.0/gems/pghero-1.2.4/lib/pghero/methods/suggested_indexes.rb" line 103 in each
5
File "/app/vendor/bundle/ruby/2.1.0/gems/pghero-1.2.4/lib/pghero/methods/suggested_indexes.rb" line 103 in best_index_helper
6
File "/app/vendor/bundle/ruby/2.1.0/gems/pghero-1.2.4/lib/pghero/methods/suggested_indexes.rb" line 17 in suggested_indexes_by_query
```

It's important to says it's a production environment of heroku. Using a postgresql version 9.3

**Comment by ankuriitk** [comment]
Its happening to us too!

**Comment by ankuriitk** [comment]
NoMethodError: undefined method `[]' for nil:NilClass
  pghero/methods/suggested_indexes.rb:121:in `block (2 levels) in best_index_helper'
    columns = (where + sort).map { |c| c[:column] }.uniq
  pghero/methods/suggested_indexes.rb:121:in `map'
    columns = (where + sort).map { |c| c[:column] }.uniq
  pghero/methods/suggested_indexes.rb:121:in `block in best_index_helper'
    columns = (where + sort).map { |c| c[:column] }.uniq
  pghero/methods/suggested_indexes.rb:103:in `each'
    parts.each do |statement, structure|
  pghero/methods/suggested_indexes.rb:103:in `best_index_helper'
    parts.each do |statement, structure|
...
(104 additional frame(s) were not displayed)

**Comment by deevil828** [comment]
I am also experiencing this issue.

**Comment by ankane** [comment]
I'm having trouble reproducing without the specific query it's trying to parse, but I found a potential cause.  Try `master` to see if it fixes the error.

**Comment by deevil828** [comment]
Still having the same error.  The last query executed is below, which returns results when I run it manually:

SELECT schemaname AS schema, tablename AS table, attname AS column, null_frac, n_distinct FROM pg_stats WHERE tablename IN (NULL, 'list', 'of', 'some', 'table', 'names') AND schemaname = 'public' ORDER BY 1, 2, 3

**Comment by ankane** [comment]
Try the `debug_suggested_indexes` branch. It'll output the statement it's trying to parse.

**Comment by deevil828** [comment]
Actually, whatever you did must have worked.  I cloned the repo when you commented about trying master, and restarted rails, and it was still throwing the error.. I re-pulled and checked out the debug_suggested_indexes branch, and saw it work, realized all you added was a "puts" and checked out master, restarted rails again, and now it's working there too! =)
