### ISSUE TITLE
Setup with RDS: Error saving: Cannot modify a default parameter group. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue

### ISSUE THREAD

**Issue by ACPK** [ankane/pghero#66]
When I try setting the value of shared_preload_libraries to pg_stat_statements in our Parameter Group, I get:

    Error saving: Cannot modify a default parameter group. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: ff5b3371-26b2-11e6-8709-e93cdd73ea37)

**Comment by ACPK** [comment]
I now get:

    FATAL: remaining connection slots are reserved for non-replication superuser connections

**Comment by ankane** [comment]
For the first error, try creating a new parameter group in the AWS console, modifying that one, and changing your RDS instance to use it.

The 2nd error indicates you have too many database connections.  Try killing some and connecting again.

**Comment by ACPK** [comment]
@ankane - Thanks for the quick reply and I got the second one fix. In regards to the first issue, your solution worked so thanks!
