### ISSUE TITLE
ERROR:  relation "pghero_query_stats" does not exist

### ISSUE THREAD

**Issue by lpossamai** [ankane/pghero#68]
Hi there,

I've installed pghero in my CentOS from YUM and I created the table as mentioned on the docs:

However, I created the pghero_query_stats table in another SCHEMA. And now I'm getting that error when performing:

ERROR:
`ERROR:  relation "pghero_query_stats" does not exist`

`sudo pghero run rake pghero:capture_query_stats`

Is there anything I need to do to allow pghero to see the other SCHEMA?

Cheers

**Comment by ankane** [comment]
Try:

```
sudo pghero config:set PGHERO_STATS_DATABASE_URL=postgres://user:pass@host:5432/dbname?schema_search_path=other-schema
```

**Comment by lpossamai** [comment]
Yep.. that worked. Cheers.
