### ISSUE TITLE
AWS - NoMethodError: undefined method `match' for nil:NilClass\nDid you mean

### ISSUE THREAD

**Issue by ACPK** [ankane/pghero#69]
When I try to view the RDS CPU info using my PGHERO_ACCESS_KEY_ID, PGHERO_SECRET_ACCESS_KEY and PGHERO_DB_INSTANCE_IDENTIFIER, I get:

    ["note_type", "Error"], ["note", "NoMethodError: undefined method `match' for nil:NilClass\nDid you mean?  catch"], ["action", "pg_hero/home#connection_stats"], ["status", 500]

**Comment by ACPK** [comment]
Here's the logs:

Started GET "/admin/database/load_stats" for ::1 at 2016-06-17 20:13:48 -0400
Completed 500 Internal Server Error in 816ms (ActiveRecord: 348.9ms)

NoMethodError (undefined method `match' for nil:NilClass
Did you mean?  catch):
  aws-sdk-core (2.3.9) lib/aws-sdk-core/endpoint_provider.rb:67:in `block in partition_matching_region'
  aws-sdk-core (2.3.9) lib/aws-sdk-core/endpoint_provider.rb:66:in `each'
  aws-sdk-core (2.3.9) lib/aws-sdk-core/endpoint_provider.rb:66:in `find'
  aws-sdk-core (2.3.9) lib/aws-sdk-core/endpoint_provider.rb:66:in `partition_matching_region'
  aws-sdk-core (2.3.9) lib/aws-sdk-core/endpoint_provider.rb:55:in `get_partition'
  aws-sdk-core (2.3.9) lib/aws-sdk-core/endpoint_provider.rb:26:in `endpoint_for'
  aws-sdk-core (2.3.9) lib/aws-sdk-core/endpoint_provider.rb:10:in `resolve'
  aws-sdk-core (2.3.9) lib/aws-sdk-core/endpoint_provider.rb:80:in `resolve'
  aws-sdk-core (2.3.9) lib/aws-sdk-core/plugins/regional_endpoint.rb:24:in `block in <class:RegionalEndpoint>'
  aws-sdk-core (2.3.9) lib/seahorse/client/configuration.rb:64:in `call'
  aws-sdk-core (2.3.9) lib/seahorse/client/configuration.rb:199:in `block in resolve_defaults'
  aws-sdk-core (2.3.9) lib/seahorse/client/configuration.rb:57:in `each'
  aws-sdk-core (2.3.9) lib/seahorse/client/configuration.rb:57:in `each'
  aws-sdk-core (2.3.9) lib/seahorse/client/configuration.rb:198:in `resolve_defaults'
  aws-sdk-core (2.3.9) lib/seahorse/client/configuration.rb:194:in `value_at'
  aws-sdk-core (2.3.9) lib/seahorse/client/configuration.rb:183:in `block in resolve'
  /Users/acpk/.rbenv/versions/2.3.1/lib/ruby/2.3.0/set.rb:306:in `each_key'
  /Users/acpk/.rbenv/versions/2.3.1/lib/ruby/2.3.0/set.rb:306:in `each'
  aws-sdk-core (2.3.9) lib/seahorse/client/configuration.rb:183:in `resolve'
  aws-sdk-core (2.3.9) lib/seahorse/client/configuration.rb:171:in `apply_defaults'
  aws-sdk-core (2.3.9) lib/seahorse/client/configuration.rb:144:in `build!'
  aws-sdk-core (2.3.9) lib/seahorse/client/base.rb:68:in `build_config'
  aws-sdk-core (2.3.9) lib/seahorse/client/base.rb:19:in `initialize'
  aws-sdk-core (2.3.9) lib/seahorse/client/base.rb:105:in `new'
  pghero (1.2.4) lib/pghero/methods/system.rb:28:in `rds_stats'
  pghero (1.2.4) lib/pghero/methods/system.rb:9:in `connection_stats'
  pghero (1.2.4) app/controllers/pg_hero/home_controller.rb:110:in `connection_stats'
  actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.6) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.6) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  pghero (1.2.4) app/controllers/pg_hero/home_controller.rb:197:in `set_database'
  activesupport (4.2.6) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.6) lib/active_support/callbacks.rb:312:in `block in halting'
  activesupport (4.2.6) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.6) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  marginalia (1.3.0) lib/marginalia.rb:77:in `record_query_comment'
  activesupport (4.2.6) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.6) lib/active_support/callbacks.rb:312:in `block in halting'
  activesupport (4.2.6) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.6) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  /Users/acpk/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/audited-aa54c430cc7b/lib/audited/sweeper.rb:11:in `around'
  activesupport (4.2.6) lib/active_support/callbacks.rb:455:in `public_send'
  activesupport (4.2.6) lib/active_support/callbacks.rb:455:in `block in make_lambda'
  activesupport (4.2.6) lib/active_support/callbacks.rb:312:in `block in halting'
  activesupport (4.2.6) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.6) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.6) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.6) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.6) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.6) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.6) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.6) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
  rack-attack (4.4.1) lib/rack/attack.rb:107:in `call'
  dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
  p3p (1.2.0) lib/p3p/middleware.rb:9:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `catch'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  client_side_validations (4.2.3) lib/client_side_validations/middleware.rb:15:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.6) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.6) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  rack-timeout (0.4.2) lib/rack/timeout/core.rb:122:in `block in call'
  rack-timeout (0.4.2) lib/rack/timeout/support/timeout.rb:19:in `timeout'
  rack-timeout (0.4.2) lib/rack/timeout/core.rb:121:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (3.1.1) lib/web_console/middleware.rb:131:in `call_app'
  web-console (3.1.1) lib/web_console/middleware.rb:28:in `block in call'
  web-console (3.1.1) lib/web_console/middleware.rb:18:in `catch'
  web-console (3.1.1) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
  ahoy_matey (1.4.0) lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  notable (0.1.0) lib/notable/middleware.rb:11:in `call'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  rack-timeout (0.4.2) lib/rack/timeout/core.rb:122:in `block in call'
  rack-timeout (0.4.2) lib/rack/timeout/support/timeout.rb:19:in `timeout'
  rack-timeout (0.4.2) lib/rack/timeout/core.rb:121:in `call'
  activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  honeybadger (2.6.0) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
  honeybadger (2.6.0) lib/honeybadger/config.rb:198:in `with_request'
  honeybadger (2.6.0) lib/honeybadger/rack/error_notifier.rb:30:in `call'
  dragonfly (1.0.12) lib/dragonfly/cookie_monster.rb:9:in `call'
  honeybadger (2.6.0) lib/honeybadger/rack/user_feedback.rb:28:in `call'
  honeybadger (2.6.0) lib/honeybadger/rack/user_informer.rb:18:in `call'
  slowpoke (0.1.2) lib/slowpoke/middleware.rb:8:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (3.4.0) lib/puma/configuration.rb:224:in `call'
  puma (3.4.0) lib/puma/server.rb:569:in `handle_request'
  puma (3.4.0) lib/puma/server.rb:406:in `process_client'
  puma (3.4.0) lib/puma/server.rb:271:in `block in run'

**Comment by ankane** [comment]
Try setting `ENV["AWS_REGION"]` - will update the instructions.

**Comment by ankane** [comment]
Also, added a fix on master.  Thanks for reporting!
