### ISSUE TITLE
identify redundant indexes

### ISSUE THREAD

**Issue by drewda** [ankane/pghero#70]
Perhaps worth adding functionality to identify redundant indexes, such as when a column is covered by both a compound key and an individual key.

The active_record_doctor Rubygem does this: https://github.com/gregnavis/active_record_doctor#removing-extraneous-indexes

**Comment by ACPK** [comment]
+1

**Comment by ankane** [comment]
PgHero has a `duplicate_indexes` method for this.  It used to be part of the dashboard, but was removed to cut down on noise (since it's just a space saver).  It may come back in on a page for reducing space in the future.

**Comment by drewda** [comment]
Good to know. Thanks for the info, @ankane 

I do think it's worth surfacing in the UI at some point, but I'll try that method in the meantime.

**Comment by ankane** [comment]
Restored on master behind a query parameter. You can use `?duplicate_indexes=true` to show.
