### ISSUE TITLE
PgHero 2.0

### ISSUE THREAD

**Issue by ankane** [ankane/pghero#75]
Breaking
- [x] Fix typecasting for all queries and methods
- [x] Raise error when config file exists but invalid
- [x] Add user to query stats
- [x] Use keyword arguments
- [x] Require `pg_query >= 0.9.0`
- [x] Remove `locks` method
- [x] Remove options from `connection_sources`
- [x] Remove `with` method
- [x] Field name consistency

Non-breaking
- [x] Remove cache hit rate from dashboard
- [x] Add `pghero_space_stats` to see how tables are growing
- [x] Add user to connections page
- [x] Allow config options for each database
- [ ] Better visualization of space (by table)
- [x] Visualize button on explain page (for PEV)
- [x] New config format for `pghero.yml` (no environments)
- [x] Return sizes in bytes for all methods returning sizes (in addition to display size)
- [ ] Add more tests

**Comment by ACPK** [comment]
@ankane - Looks like this is almost ready?

**Comment by ankane** [comment]
Soon :)
