### ISSUE TITLE
Can't install on Debian Jesse

### ISSUE THREAD

**Issue by virusman** [ankane/pghero#76]
```
# apt-get install pghero

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package pghero
```
The Packages file is empty, there's no package at https://deb.packager.io/gh/pghero/pghero

**Comment by ankane** [comment]
Try running `sudo apt-get -y install apt-transport-https` and following the instructions again.

**Comment by ankane** [comment]
Tested in Vagrant.
