### ISSUE TITLE
Installation on Ubuntu 16.04 doesn't work

### ISSUE THREAD

**Issue by peterbe** [ankane/pghero#81]
After having installed it with apt-get, I run:

```
# pghero config:set DATABASE_URL=postgresql://myuser:mypwd@localhost:5432/mydb
```

```
# pghero scale web=1
Scaling up...
/usr/bin/pghero: line 155: initctl: command not found
```
I don't know what `initctl` is. Not something I can install:
```
# apt-cache search initctl
```
(yields no results)

It seems I can run...:
```
# pghero scale
```
without any errors. But nothing gets started.

**Comment by fake-name** [comment]
`initctl` is part of the upstart init system, which has been replaces with shitdemd in 16.04.

The init mechanism will probably need to be updated to fix the issue.

**Comment by fake-name** [comment]
Ok, it seemed to install fine for me on 16.04.

Did you remember to replace `deb https://deb.packager.io/gh/pghero/pghero trusty master` with `deb https://deb.packager.io/gh/pghero/pghero xenial master` when setting everything up?

You want to specify you want the xenial (e.g. 16.04) release builds from packager.io. Apparently, it's building them.

It seems to then come up fine, even with shitdemd:

```

durr@pghero:/lib/systemd$ sudo service pghero status
● pghero.service
   Loaded: loaded (/etc/systemd/system/pghero.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2016-09-29 21:51:40 UTC; 1min 29s ago
 Main PID: 9325 (sleep)
   CGroup: /system.slice/pghero.service
           └─9325 /bin/sleep infinity

```

**Comment by fake-name** [comment]
After a bunch of dicking about, I got to the point where I see https://github.com/ankane/pghero/issues/79 on 16.04, so it looks like it's at least mostly installable.

I'm running Postgres 9.6 beta 4.
