### ISSUE TITLE
mac install instructions?

### ISSUE THREAD

**Issue by contra** [ankane/pghero#82]
anyone figured this out yet?

**Comment by hmistry** [comment]
Try the Docker method which uses [PgHero Solo](https://github.com/bmorton/pghero_solo).

**Comment by contra** [comment]
@hmistry Yep the docker one works fine, I'd like to install it on my localhost though to reduce the overhead + make it easy to connect to my local postgres. Connecting from docker -> host PG is a pain.

**Comment by ankane** [comment]
Not sure of an easy way to do this, but open to ideas.

**Comment by myfreeweb** [comment]
All you need from pghero_solo is the config.ru. Just put it in this repo, add 
```ruby
gem "rails_12factor"
gem "rails", "~> 5.0.0"
```
to the Gemfile, `bundle install` and `DATABASE_URL="postgres://localhost/mybase" bundle exec rackup`

**Comment by ankane** [comment]
An electron-type app would be cool, but doesn't look like this is trivial.

**Comment by venkatd** [comment]
I got it working on my machine. Here is a gist of what I wrote down for my own reference:
https://gist.github.com/venkatd/236470bcb4bc4eab435ec72f20de5c5a

Hope that helps.

**Comment by chetankapoor** [comment]
You can use the following link for installation instructions on Mac.
https://www.installvirtual.com/install-pghero-on-mac/

**Comment by ankane** [comment]
Closing out stale discussions
