### ISSUE TITLE
Port 6000 is blocked by most browsers. Change port?

### ISSUE THREAD

**Issue by abevoelker** [ankane/pghero#86]
Is port 6000 chosen for a reason? `curl` works fine, but opening [http://localhost:6000](http://localhost:6000) in Chrome, Firefox, and Brave fails because they consider port 6000 an unsafe port.

![screenshot from 2016-09-30 11 05 46](https://cloud.githubusercontent.com/assets/153459/18998398/36512c70-86fe-11e6-8a33-cf169420811e.png)

![screenshot from 2016-09-30 11 06 23](https://cloud.githubusercontent.com/assets/153459/18998402/37fe666e-86fe-11e6-90a8-c8b492969989.png)

Secondarily, maybe the version I installed for Ubuntu 14.04 is stale, but `sudo pghero config:set PORT=3001` didn't have any effect for me - pghero kept using port 6000 when I would restart it. I got around the issue by [setting `network.security.ports.banned.override` in Firefox](https://support.mozilla.org/en-US/questions/1083282#answer-780274).

Maybe this is a feature though? I dunno.

**Comment by jessewmc** [comment]
Also Ubuntu 14.04, having same issue (including port config having no effect). Port 6000 is an X11 reserved port which is why it is blocked in browsers.

**Comment by ankane** [comment]
I wasn't aware of this. Thanks for letting me know. Happy to change this in the next major release. For now, you should be able to change the port with:

```ruby
sudo pghero config:set PORT=3001
sudo service pghero restart
```

@abevoelker What does the syslog show when you restart? `tail -f /var/log/syslog`

**Comment by abevoelker** [comment]
Syslog doesn't show anything when I tail it

**Comment by fake-name** [comment]
Huh. I assumed this was an intentional, if enormously annoying attempt to force people to use a Nginx reverse proxy.

**Comment by ankane** [comment]
I added setting the port as part of the installation instructions so others don't run into this.

**Comment by aehlke** [comment]
setting port is not working for me:
```
⟫ sudo pghero config:set PORT=3030
⟫ sudo pghero config:get PORT
6000
⟫ sudo pghero config:set PORT=3030
⟫ sudo service pghero restart
⟫ sudo pghero config:get PORT
6000
```

**Comment by ankane** [comment]
Hey @aehlke, `sudo pghero config:get PORT` will always return 6000 (issue with packager.io I believe), but you should see the new port if you check the logs - `sudo pghero logs`.

**Comment by aehlke** [comment]
Thanks! Worth adding to the docs in the meantime? Lost time on that one.

**Comment by leimao** [comment]
This is ridiculous. I thought there are some problems with my program. Thank you.
