### ISSUE TITLE
Assets not loading when mounted as Rails Engine in production environment

### ISSUE THREAD

**Issue by ckuwanoe** [ankane/pghero#87]
Hello,

I've installed the gem and mounted as an engine, however I am getting an unstyled page and 404 errors with the assets on my production instance. 

<img width="417" alt="screenshot 2016-09-30 15 24 42" src="https://cloud.githubusercontent.com/assets/161009/19008787/9008e4e6-8722-11e6-8b71-babb31074e21.png">

<img width="1277" alt="screenshot 2016-09-30 15 25 01" src="https://cloud.githubusercontent.com/assets/161009/19008790/93b38830-8722-11e6-9eb5-ce2447ae2215.png">

This is on a Ubuntu 14.04 server with Rails 4.1.9 and Ruby 2.1.2. I have the latest gem installed (1.5.1). It renders fine on my development (OSX 10.12.) Am I missing a step? I also have the Sidekiq web interface mounted and no issue with the assets there. I've mounted it in the same authentication block I use for Sidekiq as well.

```
  authenticate :admin_user do
    mount Sidekiq::Web => '/jobs'
    mount PgHero::Engine, at: "pghero"
  end
```

**Comment by ankane** [comment]
Hey @ckuwanoe, make sure the assets are being precompiled during your build process, and `config.serve_static_assets = true` in `config/environments/production.rb`.

**Comment by ckuwanoe** [comment]
I set the config.serve_static_assets = true and still no change. I don't believe the assets are being pre-compiled. Do I have to manually add each to the precompile list?

**Comment by ankane** [comment]
No, the gem should handle that. Make sure you're running `rake assets:precompile` during the build/deploy process.

**Comment by ckuwanoe** [comment]
That's what I thought. I'm definitely running precompile but it's still blank. Not sure what I'm doing wrong here.

**Comment by ckuwanoe** [comment]
These are the config options I have set

```
  # Settings specified here will take precedence over those in config/application.rb.

  # Code is not reloaded between requests.
  config.cache_classes = true

  # Eager load code on boot. This eager loads most of Rails and
  # your application in memory, allowing both threaded web servers
  # and those relying on copy on write to perform better.
  # Rake tasks automatically ignore this option for performance.
  config.eager_load = true

  # Full error reports are disabled and caching is turned on.
  config.consider_all_requests_local       = false
  config.action_controller.perform_caching = true
  config.cache_store = :dalli_store

  # Enable Rack::Cache to put a simple HTTP cache in front of your application
  # Add `rack-cache` to your Gemfile before enabling this.
  # For large-scale production use, consider using a caching reverse proxy like nginx, varnish or squid.
  # config.action_dispatch.rack_cache = true

  # Disable Rails's static asset server (Apache or nginx will already do this).
  config.serve_static_assets = true

  # Compress JavaScripts and CSS.
  config.assets.js_compressor = :uglifier
  # config.assets.css_compressor = :sass

  # Do not fallback to assets pipeline if a precompiled asset is missed.
  config.assets.compile = false

  # Generate digests for assets URLs.
  config.assets.digest = true

  # Version of your assets, change this if you want to expire all your assets.
  config.assets.version = '1.0'

  # Specifies the header that your server uses for sending files.
  # config.action_dispatch.x_sendfile_header = "X-Sendfile" # for apache
  # config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect' # for nginx

  # Force all access to the app over SSL, use Strict-Transport-Security, and use secure cookies.
  #config.force_ssl = false
  config.active_record.schema_format = :sql
```

**Comment by ankane** [comment]
Unsure what it could be. You could try adding `pghero/application.js` and `pghero/application.css` manually to the precompile list.

**Comment by ckuwanoe** [comment]
Added this line and still no change

```
config.assets.precompile += %w(pghero/application.js pghero/application.css)
```

**Comment by ankane** [comment]
I'm out of ideas unfortunately.

**Comment by databyte** [comment]
If you can recreate it with an open source project, others might be able to look at it. That could also provide you the ability to compare a new rails project (or existing open source one) to your current project.

**Comment by ckuwanoe** [comment]
I'm not sure why, but it started working even though I didn't change anything.
