### ISSUE TITLE
[pghero/pghero] docker build fails

### ISSUE THREAD

**Issue by lpfeup** [ankane/pghero#88]
I submitted this issue here since I could not open it at https://github.com/pghero/pghero, so feel free to close it for not being directly related to this repository.

The latest version (rev e94217b), fails to build docker image with:
<code>
Your Ruby version is 2.1.3, but your Gemfile specified 2.3.1
The command '/bin/sh -c bash -l -c "cd /app && bundle install -j4"' returned a non-zero code: 18
</code>

**Comment by ankane** [comment]
@lpfeup I updated the `Dockerfile`. Try the latest version.

**Comment by lpfeup** [comment]
Everythink working great now. I am closing the issue.

Thanks!
