### ISSUE TITLE
Postgres 9.6 Error

### ISSUE THREAD

**Issue by blackstar257** [ankane/pghero#89]
ERROR:  column "waiting" does not exist at character 84

This only happens when im testing against postgres 9.6. It works fine against 9.5

**Comment by blackstar257** [comment]
STATEMENT:  SELECT pid, state, application_name AS source, age(now(), xact_start) AS duration, waiting, query, xact_start AS started_at FROM pg_stat_activity WHERE query <> '<insufficient privilege>' AND state <> 'idle' AND pid <> pg_backend_pid() AND now() - query_start > interval '60 seconds' ORDER BY query_start DESC

**Comment by ankane** [comment]
Hey @blackstar257, thanks for reporting. This has been fixed in the latest release.

**Comment by serggl** [comment]
Getting this error using postgres 9.6 and pghero 1.6.5
```

**Comment by serggl** [comment]
forgot to reboot Rails app after upgrade. Works fine now. Sorry for the noise
