### ISSUE TITLE
Query stats are available but not enabled

### ISSUE THREAD

**Issue by edbond** [ankane/pghero#9]
in postgresql.conf

```
shared_preload_libraries = 'pg_stat_statements'     # (change requires restart)
```

``` sql
CREATE extension pg_stat_statements;
ERROR:  function "pg_stat_statements_reset" already exists with same argument types
```

Still see "Query stats are available but not enabled" in pghero.

psql (9.2.9)
pghero (0.1.3)

**Comment by akaSStalkALEX** [comment]
CREATE EXTENSION pg_stat_statements  shows me ERROR: permission denied to create "pg_catalog.pg_stat_statements". Current user is superuser. what should I do?

**Comment by jbejar** [comment]
https://github.com/ankane/pghero/blob/master/guides/Query-Stats.md
