### ISSUE TITLE
Logs go to /var/log/syslog, despite /var/log/pghero/production.log existing

### ISSUE THREAD

**Issue by fake-name** [ankane/pghero#91]
Basically the title. 

On Ubuntu 16.04, PGHero 1.5.2 (though this was true with 1.5.x too). Using the packager.io install.

Basically, the installer creates `/var/log/pghero/production.log`, and then never uses it for anything. All the actual log output from pghero gets written into `/var/log/syslog`.

This may be the fault of shitdemd, but it's sure confusing. If diverting the logs away from syslog isn't possible, maybe try to not create the `/var/log/pghero` directory.

**Comment by ankane** [comment]
Good point, you can now set:

```ruby
sudo pghero config:set RAILS_LOG_TO_STDOUT=disabled
sudo service pghero restart
```

to write to `/var/log/pghero/production.log` and retrieve them with `sudo pghero logs`. This is also now part of the installation instructions.
