### ISSUE TITLE
Integrate with pev?

### ISSUE THREAD

**Issue by fake-name** [ankane/pghero#93]
This is a completely blue-sky wish item, but I figure I'd at least request it.

The "Explain" view lets you generate data to insert into the pev viewer. It's really cool, I hadn't seen `pev` before.

Looking at https://github.com/AlexTatiyants/pev, it's BSD licensed, and seems to execute entirely client side. It'd be awesome to integrate it into pghero so you don't have to manually cut+paste two different dialogs into another web-page. 

It'd also mean you don't need a internet connection for visualizations, which while it doesn't affect me, would mean that people with privacy concerns would be happy.

**Comment by ankane** [comment]
It's been requested before, but I personally haven't found much practical use for it, so I don't see a strong reason to include it.

**Comment by fake-name** [comment]
It's definitely more of an "oooh shiny" then something I'd actually need. 

OTOH, it already has a dedicated button for generating the input to pev, so it seems kind of silly to do all that, but yet not take the time to just add the js.

I'd have a hack at something myself, but you do NOT want me anywhere near js or ruby.

**Comment by ankane** [comment]
There's a good chance I'll remove the button in a future release, so I don't think anyone should spend their time on this.

**Comment by fake-name** [comment]
That works too!

**Comment by fake-name** [comment]
I must say, as simple as this project *seems*, it's already caught a number of issues in DBs of the projects I've pointed it at. Thanks!
