### ISSUE TITLE
Multiple databases error 

### ISSUE THREAD

**Issue by nicl** [ankane/pghero#95]
This line fails:

https://github.com/ankane/pghero/blob/master/app/controllers/pg_hero/home_controller.rb#L216

with an ArgumentError because the parameters are not sanitised. I think this is because Rails' default behaviour has changed here. (Although I am not a Ruby/Rails programmer.)

An easy fix is to append `.permit!` but this is not very secure. A better solution might be to strip out certain params before calling permit. E.g. see:

https://github.com/rails/rails/issues/26289#issuecomment-243200661

**Comment by voidfiles** [comment]
Funny, I just started getting this this morning as well.

**Comment by nicl** [comment]
Awesome, very sensible fix!

**Comment by jontonsoup** [comment]
Is this updated in the docker image?
