### ISSUE TITLE
Connect to more dbs on same dbserver

### ISSUE THREAD

**Issue by petterl** [ankane/pghero#96]
Like many other web applications we have several databases that is used for the same web application. One for mangement and then several cluster databases.

I would like the possibility to visualize more than one db using one instance of pghero.
This by letting pghero find all dbs on host or by selecting dbs from host.

**Comment by ankane** [comment]
Is this different than the current functionality supported by `config/pghero.yml`? https://github.com/ankane/pghero/blob/master/guides/Rails.md#multiple-databases

**Comment by fake-name** [comment]
It *sounds* like the `config/pghero.yml` thing would work, but how do you do that if you installed it as a package, rather then piecemeal?

**Comment by ankane** [comment]
I've updated the readme [with instructions](https://github.com/ankane/pghero/blob/master/guides/Linux.md#multiple-databases). You'll need to be on version 1.5.3 or above (just released).

**Comment by fake-name** [comment]
FWIW, on ubuntu, the file gets stuck in `/opt/pghero/config/pghero.yml`. 

In the yaml file, do the `primary`/`replica` strings mean anything? Personally, I'm less interested in multiple copies of the same database as I am monitoring the several projects I have in the /same/ pg server, albeit within different databases.

**Comment by ankane** [comment]
You're welcome to name the databases anything you'd like :)

**Comment by petterl** [comment]
I run pghero as a docker container, and then you just pass in the dbname as a variable, would it be possible to add support for multiple databases in that senario as well?

**Comment by ankane** [comment]
Yeah, you can add `/app/config/pghero.yml` file to the container with:

```yml
production:
  databases:
    primary:
      url: postgres://...
    replica:
      url: postgres://...
```
