### ISSUE TITLE
Centos 7 does not work

### ISSUE THREAD

**Issue by cheluskin** [ankane/pghero#98]
Centos 7 does not work

service file 

[Unit]
StopWhenUnneeded=true

[Service]
# this service is just a placeholder
ExecStart=/bin/sleep infinity

[Install]
WantedBy=multi-user.target

**Comment by ankane** [comment]
Hey @cheluskin, you'll need to explain more if you'd like someone to help. "Does not work" is not really helpful. For what it's worth, the latest version has been tested fresh Vagrant machine and works fine.
